### ISSUE TITLE
Using of ExtendedImage.memory crashes

### ISSUE THREAD

**Issue by bambinoua** [fluttercandies/extended_image#103]
I just simply use ExtendedImage.memory to display image and while compiling the project I get a crash and error message related to extended_image_library_1.0.8: The method ExtenedeMemoryImageProvider.load has fewer positional arguments than those of overidedn method 'MemoryImage.load'

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/80 see pinned issue
