### ISSUE TITLE
Image crop from 9:16 to smaller aspect ratio like 4:3 

### ISSUE THREAD

**Issue by HickYeah** [fluttercandies/extended_image#105]
Hi there, 

I am facing the following error when I am trying to Crop a 9:16 or full screen of Samsung Note 9 images to 4:3, 1:1, or 16:9,

`E/flutter (21721): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError (index): Index out of range: index should be less than 3400320: 3400320
`

I am using an Extended Image widget like the following ... 

```body: Builder(
        builder: (context) => SafeArea(
            child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              AspectRatio(
                aspectRatio: 3 / 4,
                child: Stack(
                  children: <Widget>[
                    _image == null
                        ? Center(
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                                Padding(
                                  padding: const EdgeInsets.all(15.0),
                                  child: Text('No image selected.'),
                                ),
                                InkWell(
                                  child: Icon(
                                    Icons.add_a_photo,
                                    size: 70,
                                  ),
                                  onTap: getImage, // Using Image Picker Return _image 
                                ),
                              ],
                            ),
                          )
                        : ExtendedImage.file(
                            _image,
                            fit: BoxFit.contain,
                            mode: ExtendedImageMode.editor,
                            extendedImageEditorKey: editorKey,
                            initEditorConfigHandler: (state) {
                              return EditorConfig(
                                cornerColor: Colors.redAccent,
                                maxScale: 5.0,
                                cropRectPadding: EdgeInsets.all(3.0),
                                hitTestSize: 20.0,
                                cropAspectRatio: _cropAspectRatio,  // _cropAspectRatio = [3 / 4, 1 / 1, 16 / 9]
                              );
                            },
                          ),
                    Positioned(
                      right: 15.0,
                      left: 15.0,
                      bottom: 15.0,
                      child: Row(), ), ],),),),),)
```

**Comment by zmtzawqlp** [comment]
1.only in Samsung Note 9
2.which step

**Comment by zmtzawqlp** [comment]
why use SingleChildScrollView ？
why use AspectRatio(
                aspectRatio: 3 / 4,

**Comment by HickYeah** [comment]
The issue is only happening with Samsung physical device Note 9, I was trying to Crop a 9:16 original ratio to three ratios. Everything worked well on the Andriod emulator but for some reason, I  started getting the error I mentioned on the main issue on Note 9.

I am using SingleChildScrollView to scroll down the page for more content down the screen and using AspectRatio to control the space of the 9:16 images taken from the screen. I tried without it and I got the same issue.

**Comment by HickYeah** [comment]
Also, I am using the following logic to Crop the image 

```
Future<List<int>> cropImageDataWithDartLibrary(
      {ExtendedImageEditorState state}) async {
    print("dart library start cropping");

    ///crop rect base on raw image
    final Rect cropRect = state.getCropRect();

    var data = state.rawImageData;

    final EditActionDetails editAction = state.editAction;

    var time1 = DateTime.now();
    final lb = await loadBalancer;
    Image.Image src =
        await lb.run<Image.Image, List<int>>(Image.decodeImage, data);

    var time2 = DateTime.now();

    print("${time2.difference(time1)} : decode");

    //clear orientation
    src = Image.bakeOrientation(src);

    if (editAction.needCrop)
    src = Image.copyCrop(src, cropRect.left.toInt(), cropRect.top.toInt(),
        cropRect.width.toInt(), cropRect.height.toInt());

    if (editAction.needFlip) {
      Image.Flip mode;
      if (editAction.flipY && editAction.flipX) {
        mode = Image.Flip.both;
      } else if (editAction.flipY) {
        mode = Image.Flip.horizontal;
      } else if (editAction.flipX) {
        mode = Image.Flip.vertical;
      }
      src = Image.flip(src, mode);
    }

    if (editAction.hasRotateAngle)
      src = Image.copyRotate(src, editAction.rotateAngle);

    var time3 = DateTime.now();
    print("${time3.difference(time2)} : crop/flip/rotate");

    src = Image.copyResize(src, width: 800);

    var fileData = await lb.run<List<int>, Image.Image>(Image.encodeJpg, src);

    var time4 = DateTime.now();
    print("${time4.difference(time3)} : encode");
    print("${time4.difference(time1)} : total time");

    return fileData;
  }
```
The error is happening on >>>>  Image.copyCrop

**Comment by HickYeah** [comment]
Tried without SingleChildScrollView, also having the same problem,

**Comment by zmtzawqlp** [comment]
do you try native library?   dart library is from [Image](https://github.com/brendan-duncan/image). maybe you can get help over there

**Comment by HickYeah** [comment]
I don't think the problem with Image library, please look at the test results below, Looks like the extended Image library pass different values to the Image.crop, in two different situations  

As I mentioned I tested the 9:16 ratios on the emulator and it works. I printed those values 

**On emulator** Worked 
I/flutter (25045): Crop left 0
I/flutter (25045): Crop top 222
I/flutter (25045): Crop width 1000
I/flutter (25045): Crop height 1333

When I tested with Note 9 as I mentioned I got the results below 

**On Note 9** Not Working 
I/flutter ( 4016): Crop left 0
I/flutter ( 4016): Crop top 504
I/flutter ( 4016): Crop width 2268
I/flutter ( 4016): Crop height 3024

If you notice that getCropRect return two different widths and heigh.

**Comment by HickYeah** [comment]
For the emulator, I am using Pixel XL

**Comment by zmtzawqlp** [comment]
it's base on your screen size. and what the size of image?

**Comment by HickYeah** [comment]
The size of the 9:16 image that I am testing with t is 1000 × 1778 pixels. 

This one [https://images.unsplash.com/photo-1566895291281-ea63efd4bdbc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80](url)

**Comment by zmtzawqlp** [comment]
use following code to get size of image from your side.  and see different from emulator  and Note 9 
 NetworkImage(
    “xxx”)
        .resolve(ImageConfiguration.empty)
        .addListener(
            ImageStreamListener((ImageInfo imageInfo, bool synchronousCall) {
      print(imageInfo.image);
    }));

**Comment by HickYeah** [comment]
I tried the code above, and the results as the following 

**On emulator** 
I/flutter (25517): ####################>>>>> [1000×1778]

**On Note 8**
I/flutter (17438): ####################>>>>> [1000×1778]

Also, I tried on **Note 10+ :)** 
I/flutter (27158): ####################>>>>> [1000×1778]

**Comment by zmtzawqlp** [comment]
On Note 9 Not Working
I/flutter ( 4016): Crop left 0
I/flutter ( 4016): Crop top 504
I/flutter ( 4016): Crop width 2268
I/flutter ( 4016): Crop height 3024

i think it should not be bigger than 1000* 1778,  i have not note 9 to test. test [codes](https://github.com/fluttercandies/extended_image/blob/master/lib/src/editor/extended_image_editor.dart#L247) at your side if you have time

**Comment by zmtzawqlp** [comment]
it's still problem at your side. Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
