### ISSUE TITLE
预览长图如何滚动？How do I scroll through the long picture?

### ISSUE THREAD

**Issue by zhangweiwei0326** [fluttercandies/extended_image#106]
预览的时候长图不能往下滚动

The long picture can't scroll down when you preview it.

**Comment by zmtzawqlp** [comment]
请提供图片和demo

**Comment by zmtzawqlp** [comment]
reopen if still have problem

**Comment by Tumbler0809** [comment]
I also encountered, how to preview a length, set it as follows in ExtendedImageGesturePageView

**Comment by Tumbler0809** [comment]
ExtendedImage.network(
            url,
            fit: BoxFit.fitWidth,
            loadStateChanged: mLoadStateChanged,
            mode: ExtendedImageMode.gesture,
            initGestureConfigHandler: initGestureConfigHandler,
          )

**Comment by zmtzawqlp** [comment]
plz, provide  runnable demo to show your issue.

**Comment by Tumbler0809** [comment]
![91](https://user-images.githubusercontent.com/13026221/72679445-19554b80-3aea-11ea-9b7f-96760ba2378e.jpeg)

**Comment by Tumbler0809** [comment]
在pageView 中放上这个大长图，如果是微信一开始宽度就会等于屏幕宽，但是这个不是

**Comment by Tumbler0809** [comment]
![36](https://user-images.githubusercontent.com/13026221/72679509-d34cb780-3aea-11ea-804d-1fcc19f25bd0.jpg)

**Comment by Tumbler0809** [comment]
具体可看微信盆友圈的长图，可能在初始化时需要计算一个初始化的放大倍数

**Comment by zmtzawqlp** [comment]
请看demo。这种需要自己设置初始化的scale

**Comment by Tumbler0809** [comment]
InitGestureConfigHandler 只能在ExtendedImage创建的时候就设置进去而不能在ExtendedImage对象实例化完成后再设置，而我们拿宽高需要ExtendedImage创建完毕才能拿到

**Comment by zmtzawqlp** [comment]
@Tumbler0809 认真看demo，是在图片获取到高宽的时候才会回调

**Comment by Tumbler0809** [comment]
![image](https://user-images.githubusercontent.com/13026221/72704087-ae138400-3b92-11ea-9030-058232dbdcb3.png)

**Comment by Tumbler0809** [comment]
求大佬告知，没法在image的到后再设置呀

**Comment by Tumbler0809** [comment]
好像知道了，谢谢

**Comment by Tumbler0809** [comment]
这个能否设置在加载长图是，长图不居中显示，而是居上显示，就是长图在展开的时候，自动滑动到最上面，而不是在中间

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/66

**Comment by Tumbler0809** [comment]
额嗯，看到了，谢谢大佬了
