### ISSUE TITLE
Way to Handle Exception 

### ISSUE THREAD

**Issue by rahuldange09** [fluttercandies/extended_image#107]
How to handle error if image url is not valid. and cache also misses it.
It just throws error in console.. it better to handle error than throwing it.

```
Exception caught by image resource service ════════════════════════════
The following StateError was thrown resolving an image codec:
Bad state: Failed to load https://tteemp.png.

Image provider: ExtendedNetworkImageProvider("https://temmp.png", scale: 1.0)
Image key: ExtendedNetworkImageProvider("https://tempp.png", scale: 1.0)
```

**Comment by zmtzawqlp** [comment]
clearMemoryCacheIfFailed= true and define failed widget by loadstatechanged

**Comment by zmtzawqlp** [comment]
reopen if still have problem

**Comment by rahuldange09** [comment]
I always get such exceptions for invalid image urls or something which stops my app.

> BaseClient._sendUnstreamed (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_client.dart:169)
> <asynchronous gap> (Unknown Source:0)
> BaseClient.get (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/base_client.dart:32)
> HttpClientHelper.get.<anonymous closure> (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/http_client_helper-0.2.1/lib/src/http_client_helper.dart:29)
> RetryHelper.tryRun (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/http_client_helper-0.2.1/lib/src/retry_helper.dart:17)
> HttpClientHelper.get (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/http_client_helper-0.2.1/lib/src/http_client_helper.dart:25)
> ExtendedNetworkImageProvider._loadNetwork (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:152)
> ExtendedNetworkImageProvider._loadCache (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:139)
> <asynchronous gap> (Unknown Source:0)
> ExtendedNetworkImageProvider._loadAsync (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:93)
> ExtendedNetworkImageProvider.load (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:65)
> ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/painting/image_provider.dart:327)
> ImageCache.putIfAbsent (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/painting/image_cache.dart:160)
> ImageProvider.resolve.<anonymous closure>.<anonymous closure> (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/painting/image_provider.dart:325)
> SynchronousFuture.then (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/foundation/synchronous_future.dart:38)
> ImageProvider.resolve.<anonymous closure> (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/painting/image_provider.dart:323)
> _rootRun (dart:async/zone.dart:1126)
> _rootRun (dart:async/zone.dart:0)
> _CustomZone.run (dart:async/zone.dart:1023)
> _CustomZone.runGuarded (dart:async/zone.dart:925)
> ImageProvider.resolve (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/painting/image_provider.dart:315)
> _ExtendedImageState._resolveImage (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.8/lib/src/extended_image.dart:710)
> _ExtendedImageState.didChangeDependencies (/Users/rahul/Projects/dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.6.8/lib/src/extended_image.dart:654)
> StatefulElement._firstBuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4376)
> ComponentElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4201)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> SingleChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5445)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> ComponentElement.performRebuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4243)
> Element.rebuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3947)
> ComponentElement._firstBuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4206)
> ComponentElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4201)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> MultiChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5551)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> MultiChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5551)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> MultiChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5551)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> SingleChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5445)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> SingleChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5445)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> SingleChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5445)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> SingleChildRenderObjectElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:5445)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
> ComponentElement.performRebuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4243)
> Element.rebuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3947)
> ComponentElement._firstBuild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4206)
> ComponentElement.mount (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:4201)
> Element.inflateWidget (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:3194)
> Element.updateChild (/Users/rahul/Projects/dev/flutter/packages/flutter/lib/src/widgets/framework.dart:2988)
>

**Comment by zmtzawqlp** [comment]
those from http, it seems that your image url is not good. maybe it has certificate

**Comment by rahuldange09** [comment]
Yes sometimes image url is not proper. Like it doesn't have http also (like "abcd"). But I want to handle that instead of throwing error. So is it possible?

**Comment by zmtzawqlp** [comment]
it's thrown by http library. and it don't break your ui

**Comment by rahuldange09** [comment]
Yes, but in debug mode it shows exception when unhandled exception is active and in release mode if i want to show some custom error when error then it will show everytime.
If iits http then can it handled by try catch?

**Comment by zmtzawqlp** [comment]
no，take care of your image url.

**Comment by volgin** [comment]
@zmtzawqlp I like your plugins, but this is a bad answer.

I get image URLs from a third party - over 1 million URLs. Some of them may fail at any time (and then start working again). There is no way to make sure that all URLs are always working. There must be a way to catch these errors and change the UI accordingly.

**Comment by zmtzawqlp** [comment]
@volgin In fact，ExtendedNetworkImageProvider already has tried to get data much times.
https://github.com/fluttercandies/extended_image_library/blob/e67006f75cdcdfabfe4890b9b9dd067cc17da48c/lib/src/_network_image_io.dart#L240

Some of them may fail at any time (and then start working again).---- i  think it will work for it.

**Comment by rahuldange09** [comment]
I think a simple flag like `throwErrorOnFail` should be there. If `true` (defaults to true) then it will throw an error or if it is `false` then it will not throw an error, it should just log it.

**Comment by Coffiie** [comment]
How is this issue still closed? We have a large app and the integration tests keep on failing because this package keeps throwing this error. This is unacceptable.

**Comment by GeylanKalafMohe** [comment]
This issue still happens even after :
clearMemoryCacheIfFailed= true and defining failed widget by loadstatechanged 

It still throws errors and there is no way to catch it

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/blob/d2e0a2299601248c55f58486dd90b4384f35f671/lib/src/network/network_image_io.dart#L265

you can set printError = false to ignore the error info to be print

**Comment by GeylanKM** [comment]
it still prints the error, there is no way to catch it with your package and we receive hundreds of reports in firebase please reopen the issue and kindly fix it:

```dart
ImageStreamCompleter.reportError (image_stream.dart:814)
new MultiFrameImageStreamCompleter.<fn> (image_stream.dart:946)

Bad state: Failed to load https://iu.edu.sa/media/%D8%A7%D9%84%D8%B5%D8%AD%D8%A9%20%D8%A7%D9%84%D9%86%D9%81%D8%B3%D9%8A%D8%A9222.jpeg

Instance of 'DiagnosticsProperty<ImageProvider<Object>>' Instance of 'DiagnosticsProperty<ExtendedNetworkImageProvider>'
```

**Comment by violet-dev** [comment]
Is there a proper way to handle this error? I'm using a refresh proxy with `FlutterError.onError`, really stupid.

**Comment by violet-dev** [comment]
To solve this problem, I wrote the following code:
```dart
    final provider = ExtendedNetworkImageProvider(
      c.urlCache[index]!.value,
      headers: c.headerCache[index],
      cache: true,
      retries: 10,
      timeRetry: const Duration(milliseconds: 300),
    );

    final image = Image(
      key: c.imgKeys[index],
      errorBuilder: (context, error, stackTrace) {
        Future.delayed(const Duration(milliseconds: 500), () {
          if (mounted) {
            setState(() {
              provider.evict();
              c.imgKeys[index] = GlobalKey();
            });
          }
        });

        return const SizedBox.shrink();
      },
      image: provider,
    );

    return wrappingGestureDetector(image, index);
```
