### ISSUE TITLE
断网运行example时，选择重新加载图片会一直处于loading状态，不会出现failed状态

### ISSUE THREAD

**Issue by azhezzz** [fluttercandies/extended_image#11]
我尝试在断网的情况下运行example

![WX20190522-112908](https://user-images.githubusercontent.com/31943269/58145495-e4f06d80-7c84-11e9-8f36-304e146a1dbb.png)

点击重新加载图片，于是便一直处于loading状态，而且始终不会变成failed状态，包括在loading中途开启网络

![WX20190522-112930](https://user-images.githubusercontent.com/31943269/58145514-f8033d80-7c84-11e9-844e-5e6a2e27995d.png)

![WX20190522-111526](https://user-images.githubusercontent.com/31943269/58145527-04879600-7c85-11e9-8461-19fe6e4d4584.png)

---------------

请问是本身设计如此还是？

如果是的话，请问如果我想在断网情况下，选择重新加载图片，loading一段时间会变成failed状态的实现思路大概是怎样呢？

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/blob/master/lib/src/extended_network_image_provider.dart  
有重试时间，和重试次数。不可能一直重试。不科学

**Comment by azhezzz** [comment]
断网情况下运行example第一个demo
我这边点击重新加载之后就一直只处于`LoadState.loading`状态。

然后我查了下在[https://github.com/fluttercandies/extended_image/blob/master/lib/src/extended_image.dart](https://github.com/fluttercandies/extended_image/blob/master/lib/src/extended_image.dart)中，在执行`reLoadImage()`时会执行到`_updateSourceStream()`
```dart
  void _updateSourceStream(ImageStream newStream, {bool rebuild = false}) {
    .......
    if (_imageStream?.key == newStream?.key) return;
    //print("_updateSourceStream");
    if (_isListeningToStream) _imageStream.removeListener(_handleImageChanged);
    .......
    _imageStream = newStream;
    if (_isListeningToStream) _imageStream.addListener(_handleImageChanged);
  }
```
最后一行重新添加监听器时没有添加onError。

我把onError加上
```dart
if (_isListeningToStream) _imageStream.addListener(_handleImageChanged, onError: _loadFailed);
```

然后再点击重新加载后，当超过规定条件的时候，状态就能变更成`LoadState.failed`了

**Comment by zmtzawqlp** [comment]
你好，我看一下代码，确实是我少加了监听，已经更新了代码，谢谢你的研究。。
