### ISSUE TITLE
Error: 'DecoderCallback' isn't a type

### ISSUE THREAD

**Issue by qq329401134** [fluttercandies/extended_image#110]
/D:/Program%20Files/Flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {

我用的是v1.9.1+hotfix.6 windows

**Comment by qq329401134** [comment]
版本  extended_image-0.6.8   extended_image_library-0.1.9

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/89

**Comment by qq329401134** [comment]
flutter v1.9.1+hotfix.6 windows
yaml指定下面即可
extended_image: 0.6.7
extended_image_library: 0.1.8
