### ISSUE TITLE
Bug + suggestion for zooming

### ISSUE THREAD

**Issue by Martibis** [fluttercandies/extended_image#111]
I have a vertical list view with a carousel with extended images. The carousel is in a fixed 4/3 AspectRatio widget. When pinching to zoom in there seems to be a weird issue where it jumps from one touchpoint to the other one. See video: https://youtu.be/tfNX9VRCobc

A suggestion not directly related to the bug, but in regards to zoom, would be to add a way to zoom on an extended image and make the image come out of its container.

**Comment by zmtzawqlp** [comment]
it's better to provide a simple demo and steps for this issue. i can't get any idea from your video.

**Comment by zmtzawqlp** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
