### ISSUE TITLE
Type 'DecoderCallback' not found

### ISSUE THREAD

**Issue by jiongjarjar** [fluttercandies/extended_image#112]
------------------------------------------------------------
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
------------------------------------------------------------
0.6.5 ~ 0.6.8四个版本都试过，同样的错，不知道什么原因
------------------------------------------------------------

Launching lib\main.dart on hm 1s in debug mode...

Compiler message:
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:63:41: Error: Type 'DecoderCallback' not found.
      ExtendedNetworkImageProvider key, DecoderCallback decode) {
                                        ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:87:41: Error: Type 'DecoderCallback' not found.
      ExtendedNetworkImageProvider key, DecoderCallback decode) async {
                                        ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_image_provider.dart:14:23: Error: Type 'DecoderCallback' not found.
      Uint8List data, DecoderCallback decode) async {
                      ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:46: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                                             ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:19:48: Error: Type 'DecoderCallback' not found.
  Future<ui.Codec> _loadAsync(MemoryImage key, DecoderCallback decode) {
                                               ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:44: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                                           ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:23:46: Error: Type 'DecoderCallback' not found.
  Future<ui.Codec> _loadAsync(FileImage key, DecoderCallback decode) async {
                                             ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:54: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:52:32: Error: Type 'DecoderCallback' not found.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:105:32: Error: Type 'DecoderCallback' not found.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:24: Error: The method 'ExtendedMemoryImageProvider.load' has more required arguments than those of overridden method 'MemoryImage.load'.
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:596:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(MemoryImage key) {
                       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:24: Error: The method 'ExtendedFileImageProvider.load' has more required arguments than those of overridden method 'FileImage.load'.
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:528:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(FileImage key) {
                       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:24: Error: The method 'ExtendedExactAssetImageProvider.load' has more required arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:447:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:24: Error: The method 'ExtendedAssetImageProvider.load' has more required arguments than those of overridden method 'AssetBundleImageProvider.load'.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:447:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(AssetBundleImageKey key) {
                       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:62:24: Error: The method 'ExtendedNetworkImageProvider.load' has more required arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(
                       ^
/D:/flutter/packages/flutter/lib/src/painting/image_provider.dart:383:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key);
                       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.6.8/lib/src/gesture/extended_image_gesture.dart:97:19: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
          context.findAncestorStateOfType<ExtendedImageGesturePageViewState>();
                  ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.6.8/lib/src/gesture/extended_image_gesture.dart:108:19: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
          context.findAncestorStateOfType<ExtendedImageGesturePageViewState>();
                  ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.6.8/lib/src/extended_image.dart:659:19: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
          context.findAncestorStateOfType<ExtendedImageSlidePageState>();
                  ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.6.8/lib/src/extended_image.dart:681:14: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
            .findAncestorStateOfType<ExtendedImageSlidePageState>();
             ^^^^^^^^^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:63:41: Error: 'DecoderCallback' isn't a type.
      ExtendedNetworkImageProvider key, DecoderCallback decode) {
                                        ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_network_image_provider.dart:87:41: Error: 'DecoderCallback' isn't a type.
      ExtendedNetworkImageProvider key, DecoderCallback decode) async {
                                        ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_image_provider.dart:14:23: Error: 'DecoderCallback' isn't a type.
      Uint8List data, DecoderCallback decode) async {
                      ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:12:46: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(MemoryImage key, DecoderCallback decode) {
                                             ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:19:48: Error: 'DecoderCallback' isn't a type.
  Future<ui.Codec> _loadAsync(MemoryImage key, DecoderCallback decode) {
                                               ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:44: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                                           ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:23:46: Error: 'DecoderCallback' isn't a type.
  Future<ui.Codec> _loadAsync(FileImage key, DecoderCallback decode) async {
                                             ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:52:32: Error: 'DecoderCallback' isn't a type.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:105:32: Error: 'DecoderCallback' isn't a type.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^
Compiler failed on D:\flutter_projects\demo02\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by zmtzawqlp** [comment]
看看 这个https://github.com/fluttercandies/extended_image/issues/89

**Comment by brhomapps** [comment]
i have the same problem

**Comment by zmtzawqlp** [comment]
check version  for flutter sdk
