### ISSUE TITLE
Zoom gets locked into horizontal only (ExtendedImageGesturePageView)

### ISSUE THREAD

**Issue by sethchhim** [fluttercandies/extended_image#114]
Steps to reproduce:

1. Zoom into center of the image
2. Perform a `horizontal swipe` to pan the image
3. While keeping your finger down, attempt to pan vertically
4. Observe vertical pan is not allowed because it is locked in horizontal

```
import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class TestWidget extends StatelessWidget {
  const TestWidget();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: _buildPageView(),
      ),
    );
  }

  Widget _buildPageView() {
    return ExtendedImageGesturePageView.builder(itemBuilder: (context, index) {
      return ExtendedImage.network(
        'https://i.imgur.com/P9IVqkS.jpg',
        fit: BoxFit.contain,
        mode: ExtendedImageMode.gesture,
        initGestureConfigHandler: (ExtendedImageState state) => GestureConfig(
          inPageView: true,
        ),
      );
    });
  }
}
```

**Comment by zmtzawqlp** [comment]
as design , you can't zoom(two fingers) with moving vertical/horizontal , it's flutter gesture arena.

**Comment by sethchhim** [comment]
@zmtzawqlp Hello, thanks for response. I am talking about single finger moving. I will try to be more clear.

1. Zoom into center of image with two fingers.
2. Release two fingers and zoom is complete
3. Perform a `vertical swipe` with single finger to start moving around
4. Pan is working as intended in all directions :heavy_check_mark:
5. Perform a `horizontal swipe` with single finger to start moving around
6. Any pan in vertical direction is now blocked :x:

It seems this bug only happens inside `ExtendedImageGesturePageView` and when pan is initiated with a `horizontal swipe`, otherwise it works correctly.

**Comment by zmtzawqlp** [comment]
i didn't reproduce it with your code.  horizontal swipe???  did you set ExtendedImageGesturePageView  to horizontal??

**Comment by sethchhim** [comment]
I am not referring to scrollDirection.

If your initial pan is of horizontal nature, it will be locked and can not go vertical until you release and try again from a different angle. 

I will try to record a video for you.

**Comment by zmtzawqlp** [comment]
i got it , it's flutter gesture arena. flutter will tell what gesture is now. you can't change type until you release previous.

**Comment by sethchhim** [comment]
Ok, I recorded video of the swipe action if you still need it. Thanks for listening.

**Comment by zmtzawqlp** [comment]
if gesture  is start as horizontal , then it can't be vertical before pointer release.  a simple demo can prove it.

    GestureDetector(
      onHorizontalDragUpdate: (_) {
        print("onHorizontalDragUpdate");
      },
      onVerticalDragUpdate: (_) {
        print("onVerticalDragUpdate");
      },
    );

**Comment by sethchhim** [comment]
<details><summary>Vertical initial pan</summary>
<p>

![success](https://user-images.githubusercontent.com/11790350/70878441-757afc00-1f8f-11ea-9d27-2e9ee93cfeea.gif)
</p>

</details>

<details><summary>Horizontal initial pan</summary>
<p>

![fail](https://user-images.githubusercontent.com/11790350/70878323-06050c80-1f8f-11ea-9e75-792a32caa52d.gif)

</p>
</details>

**Comment by sethchhim** [comment]
Going to close this because I don't think zoom and next page gesture are really compatible from a design standpoint. There are too many moving parts when trying to pan around and consume the slide if page turn is activated.

I'm just using a regular PageView now and plan to add a tab that fades in when edge scroll is detected. The tab can then be pulled to activate page turn.

**Comment by fenchai23** [comment]
was there ever a solution for this? I have had to use another package (photo_view) to go around this issue. Honestly I would prefer if this package was able to move around freely so I just need to use 1 package.
