### ISSUE TITLE
在LoadStateChanged的图片加载完成后，如何将图片先压缩再显示呀

### ISSUE THREAD

**Issue by wuyuhang** [fluttercandies/extended_image#116]

**Comment by zmtzawqlp** [comment]
you can create new provider and extends it with ExtendedProvider, and override instantiateImageCodec method. so that you can handle image raw data here (compress image).

**Comment by zmtzawqlp** [comment]
``` dart
class MyImageProvider extends ExtendedNetworkImageProvider {
  MyImageProvider(String url) : super(url);

  @override
  Future<ui.Codec> instantiateImageCodec(
      Uint8List data, DecoderCallback decode) async {
    /// compress image here
    //data=await compressImage(data);
    return super.instantiateImageCodec(data, decode);
  }
}
```

**Comment by gggitpl** [comment]
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui show Codec, ImmutableBuffer;

import 'package:extended_image/extended_image.dart';
import 'package:extended_image_library/src/network/network_image_io.dart' as network_image;
import 'package:flutter/material.dart';

import '../config/ciphers.dart';

class MyExtendedNetworkImageProvider extends network_image.ExtendedNetworkImageProvider {
  MyExtendedNetworkImageProvider(super.url);

  @override
  Future<ui.Codec> instantiateImageCodec(Uint8List data, ImageDecoderCallback decode) async {
    var newData = Uint8List.fromList(await decryptFile(data));
    if (cacheRawData) {
      rawImageDataMap[this] = newData;
    }
    final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(newData);
    return await decode(buffer);
  }
}

class MyExtendedImage extends ExtendedImage {
  MyExtendedImage({super.key, required super.image, super.fit, super.opacity});
}

**Comment by gggitpl** [comment]
```
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui' as ui show Codec, ImmutableBuffer;

import 'package:extended_image/extended_image.dart';
import 'package:extended_image_library/src/network/network_image_io.dart' as network_image;
import 'package:flutter/material.dart';

import '../config/ciphers.dart';

class MyExtendedNetworkImageProvider extends network_image.ExtendedNetworkImageProvider {
  MyExtendedNetworkImageProvider(super.url);

  @override
  Future<ui.Codec> instantiateImageCodec(Uint8List data, ImageDecoderCallback decode) async {
    var newData = Uint8List.fromList(await decryptFile(data));
    if (cacheRawData) {
      rawImageDataMap[this] = newData;
    }
    final ui.ImmutableBuffer buffer = await ui.ImmutableBuffer.fromUint8List(newData);
    return await decode(buffer);
  }
}

class MyExtendedImage extends ExtendedImage {
  MyExtendedImage({super.key, required super.image, super.fit, super.opacity});
}
```
