### ISSUE TITLE
Does it support SVG?

### ISSUE THREAD

**Issue by hanabi1224** [fluttercandies/extended_image#118]

**Comment by zmtzawqlp** [comment]
this is not the responsibility for extended_image, decoder is the same as official

**Comment by hanabi1224** [comment]
@zmtzawqlp That makes it inconvenient for scenarios that ppl use svg and other image formats together. It will be great to have the capability of registering custom image provider

**Comment by zmtzawqlp** [comment]
https://github.com/dnfield/flutter_svg   there is already issue about this.

**Comment by zmtzawqlp** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
