### ISSUE TITLE
Image cache doesn't actually cache image

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [fluttercandies/extended_image#12]
Hi, When I set cache to true for ExtendedImage.network, it still doesn't cache the image. To test this, I replaced the widget with a CachedNetworkImage and it works while offline, but not with ExtendedImage.
Here's a video demo.
https://streamable.com/cj9j5
Code:
```dart
ExtendedImage.network(
                    url,
                    cache: true,
                    shape: BoxShape.rectangle,
                    borderRadius: BorderRadius.circular(15),
                  ),
```

**Comment by zmtzawqlp** [comment]
please provide full demo,

**Comment by zmtzawqlp** [comment]
@ThinkDigitalRepair can't reproduce, reopen it when you provide demo for this issue
