### ISSUE TITLE
引入extended_image到主项目中，报错

### ISSUE THREAD

**Issue by yfm-pliny** [fluttercandies/extended_image#120]
flutter版本 1.9.1+hotfix.6 ，是我用到方式不对吗？
报错日志：
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_memory_image_provider.dart:19:48: Error: 'DecoderCallback' isn't a type.
  Future<ui.Codec> _loadAsync(MemoryImage key, DecoderCallback decode) {
                                               ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:13:44: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(FileImage key, DecoderCallback decode) {
                                           ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_file_image_provider.dart:23:46: Error: 'DecoderCallback' isn't a type.
  Future<ui.Codec> _loadAsync(FileImage key, DecoderCallback decode) async {
                                             ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:35:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:52:32: Error: 'DecoderCallback' isn't a type.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:88:54: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AssetBundleImageKey key, DecoderCallback decode) {
                                                     ^^^^^^^^^^^^^^^
/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.9/lib/src/extended_asset_bundle_image_provider.dart:105:32: Error: 'DecoderCallback' isn't a type.
      AssetBundleImageKey key, DecoderCallback decode) async {
                               ^^^^^^^^^^^^^^^

**Comment by zmtzawqlp** [comment]
double check https://github.com/fluttercandies/extended_image/issues/89
