### ISSUE TITLE
Loading image from cache takes up to 1.5 seconds

### ISSUE THREAD

**Issue by chosti34** [fluttercandies/extended_image#121]
How can I decrease time of loading image from cache? There is no point in caching if image can be downloaded faster from the internet than from cache.

**Comment by zmtzawqlp** [comment]
it's the same.  download=>decode. i think you should decrease your image size..

**Comment by chosti34** [comment]
Thanks for the reply, yes, caching work very fast if image size is not too big, but on large images (4k for example), it takes some time.
