### ISSUE TITLE
有设置图片当前缩放大小的属性吗

### ISSUE THREAD

**Issue by gneL1** [fluttercandies/extended_image#126]
有些app里面的图片是双击放大，extended_image 是拖拽放大，我想在onDoubleTap()里面实现双击放大，extended_image 有个属性scale似乎没有效果

**Comment by gneL1** [comment]
谢谢，已解决

**Comment by savage-lin** [comment]
> 谢谢，已解决

哥，你是怎么解决的？

**Comment by BoyYangyang** [comment]
你好，请问怎么解决的,我也碰到这个问题
