### ISSUE TITLE
建议增加全局配置LoadState

### ISSUE THREAD

**Issue by YaoShuwei** [fluttercandies/extended_image#127]
有修改loading和failed的需求，但是现在需要每个组件配置一次，希望能增加全局配置项。

**Comment by zmtzawqlp** [comment]
自己封装一次就好了。不管什么项目。都不是拿来就能满足全部要求的。肯定需要用户自己进行封装。

**Comment by cv0cv0** [comment]
@zmtzawqlp 属性太多了。

**Comment by zmtzawqlp** [comment]
对于一个项目来说。你使用到的属性只有几个。封装一下就好了。静态配置破环了代码结构

**Comment by YaoShuwei** [comment]
谢大佬，我尝试自己封装一下
