### ISSUE TITLE
How can I save cropped image in application directory?

### ISSUE THREAD

**Issue by NTMS2017** [fluttercandies/extended_image#13]
I need to use crop and save the image. So, How can I save cropped image in application directory?

**Comment by zmtzawqlp** [comment]
you can save it as widget. some codes like following. get the crop data, and save them with save image picker.

 RenderRepaintBoundary boundary = scr.currentContext.findRenderObject();
  var image = await boundary.toImage();
  var byteData = await image.toByteData(format: ImageByteFormat.png);
  var pngBytes = byteData.buffer.asUint8List();
