### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YemaneZewdu** [fluttercandies/extended_image#131]
Hi there,
I wanted to use Load State but couldn't figure out what type of variable  "_controller" is. 

Thank you!

**Comment by zmtzawqlp** [comment]
enum LoadState {
  //loading
  loading,
  //completed
  completed,
  //failed
  failed
}

**Comment by YemaneZewdu** [comment]
Thanks for your reply. I was trying to point to:
case LoadState.loading:
        **_controller**.reset();
not the enum.

Thanks
