### ISSUE TITLE
How to add OnScaleChange listener?

### ISSUE THREAD

**Issue by emvaized** [fluttercandies/extended_image#146]
I want to execute some function as soon as user does a pinch-to-zoom gesture to scale up.
How can I achieve this? Thanks.

**Comment by cyucelen** [comment]
I need to prevent slide out page when zoomed in, so I need to track scale too.

**Comment by emvaized** [comment]
@cyucelen 
That's exactly one of the reasons why I need this feature

**Comment by emvaized** [comment]
@zmtzawqlp Any updates on it?

**Comment by zmtzawqlp** [comment]
more detail: 
https://github.com/fluttercandies/flutter_candies_demo_library/blob/master/lib/src/widget/pic_swiper.dart  
please update latest version, tell me if any other problem

**Comment by emvaized** [comment]
@zmtzawqlp 
Great, thanks a lot!
I'll give it a try, and reopen this issue if any problem.
