### ISSUE TITLE
能不能支持真实的下载进度

### ISSUE THREAD

**Issue by Hentioe** [fluttercandies/extended_image#147]
例如 `Image` 的 `loadingBuilder` 回调提供了一个 `ImageChunkEvent` 对象，其中包括当前下载的大小（字节数）和文件总大小，这样就可以算出 Indicator 的 value 了。

我从教程中没有看到 ExtendedImage 提供有类似的东西，是不支持吗？

**Comment by Unicellular-SU** [comment]
有同样的需求

**Comment by zmtzawqlp** [comment]
正在处理中
