### ISSUE TITLE
ExtendedImage.network("网络图片url"),报错

### ISSUE THREAD

**Issue by 826327700** [fluttercandies/extended_image#148]
![image](https://user-images.githubusercontent.com/23014381/76155534-165cfb80-6128-11ea-8440-92257d4367da.png)

**Comment by zmtzawqlp** [comment]
请提供有意义的日志信息

**Comment by zmtzawqlp** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
