### ISSUE TITLE
mark pointers on image

### ISSUE THREAD

**Issue by sanrixue** [fluttercandies/extended_image#149]
用户在图片上进行点击操作红色的点 就得在图上标记出 这个 点的位置 ；图片放大后 用户点击 标记一个点   用户缩小 点的位置也得相应的缩小；

**Comment by sanrixue** [comment]
//这是在图片上标记点 并 可以跟随放大缩小的部分代码 可复用 
 Widget imageWidget() {
    return Zoom(
      key: Key('ZoomKey'),
      width: _imageWidth, //图片宽度
      height: _imageHeight,//图片高度
      initZoom: 0.0,
      canvasColor: HexColors('#ffffff'),
      backgroundColor: HexColors('#ffffff'),
      scrollWeight: 10.0,
      centerOnScale: true,
      enableScroll: false,
      zoomSensibility: 2.3,
        child: GestureDetector(
          onLongPressEnd: (LongPressEndDetails e) {
              //获取的是图片的localPosition
            double _dx = e.localPosition.dx; 
            double _dy = e.localPosition.dy;
            setState(() {
                _touchImagePointList.add(new Positioned(
                  left: _dx - adaptWdith(20),
                  top: _dy - adaptWdith(20),
                  key: Key('pointsKey$_dx$_dy'),
                  child: CircleAvatar(
                    backgroundColor: HexColors('#FE9A00'),
                    radius: adaptWdith(20),
                  ),
                ));
            });
          },
          child: Stack(
            children: _touchImagePointList,
          ),
        ),
    );
  }

**Comment by zmtzawqlp** [comment]
谢谢分享

**Comment by sanrixue** [comment]
List<Widget> _touchImagePointList = [];
//底层图片
 Image image = Image.network(
    '****',
    fit: BoxFit.contain,
  );
  image.image.resolve(new ImageConfiguration()).addListener(new ImageStreamListener((ImageInfo info, bool _) {
    //获取到image的信息
      _imageWidth = info.image.width.toDouble();
      _imageHeight = info.image.height.toDouble();
      setState(() {
        _touchImagePointList.add(image);
      });
    }));
