### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by bagintz** [fluttercandies/extended_image#150]
Is there any planned support for Flutter Web and if so is there an ETA?

Thank you!

**Comment by zmtzawqlp** [comment]
already support

**Comment by zmtzawqlp** [comment]
https://fluttercandies.github.io/extended_image/

**Comment by bagintz** [comment]
Ok, I just didn't see the "web" badge on pub.dev, thanks!

**Comment by SergeShkurko** [comment]
https://github.com/fluttercandies/extended_image_library/issues/25
