### ISSUE TITLE
缩放功能不好用，提个建议

### ISSUE THREAD

**Issue by benzhan** [fluttercandies/extended_image#151]
对比微信的 图片滑动、缩放， extended_image 在翻页图片后，缩放功能 经常 无效。

发现是：翻页图片的动画 比较久，差不多1秒左右。在这1秒内，缩放手势会当做滑动处理。

有没有参数调整 翻页效果的速度？
能不能实现像微信那边翻页跟缩放不冲突？

**Comment by zmtzawqlp** [comment]
flutter 手势冲突，as design

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/152  可以看看这个。这是个workaround
