### ISSUE TITLE
Can't zoom immediately after page switched (ExtendedImageGesturePageView) 切换图片后无法立即缩放图片

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/extended_image#152]
As default page scroll physics defined and Flutter's gesture arena, gestures cannot take effect on widgets that user suppose to take, before `PageView` stopped scrolling. A simple example is long press after scrolled.
由于默认的滚动特性定义以及Flutter的手势竞技场影响，在查看图片的`PageView`没有停止滚动时，用户的触摸事件无法作用于用户期望的部件上。比较典型的操作为滑动后立即长按。

Here we provide a workaround, which is to make the scrolling of the `PageView` stop more quickly. A custom scroll physics with a larger `stiffness` makes the scroll duration less than default. By increasing the `stiffness`, it will spring to pages with a larger velocity.
我们在这里提供一种解决方案，可以减少`PageView`从滚动到停止滚动的耗时。一个更大系数的自定义滚动特性可以让耗时更短，滚动时更快地结束。

Construct a class like the code below:
构建方法如下：

iOS (`BouncingScrollPhysics` as default scroll physics):
```Dart
class CustomScrollPhysics extends BouncingScrollPhysics {
  const CustomScrollPhysics({ScrollPhysics parent}) : super(parent: parent);

  @override
  CustomScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomScrollPhysics(parent: buildParent(ancestor));
  }

  @override
  SpringDescription get spring => SpringDescription.withDampingRatio(
    mass: 0.5,
    stiffness: 300.0, // Increase this value as you wish.
    ratio: 1.1,
  );
}
```

Android (`ClampingScrollPhysics` as default scroll physics):
```Dart
class CustomScrollPhysics extends ClampingScrollPhysics{
  const CustomScrollPhysics({ScrollPhysics parent}) : super(parent: parent);
 
  @override
  CustomScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomScrollPhysics(parent: buildParent(ancestor));
  }
 
  @override
  SpringDescription get spring => SpringDescription.withDampingRatio(
    mass: 0.5,
    stiffness: 300.0, // Increase this value as you wish.
    ratio: 1.1,
  );
}
```

Then use the `CustomScrollPhysics` like the code below:
将`CustomScrollPhysics`应用到部件上：

```Dart
ExtendedImageGesturePageView.builder(
  physics: const CustomScrollPhysics(),
  /* ... */
)
```
----
More detail about the `PageScrollPhysics`:
`PageScrollPhysics` has a `_kDefaultSpring` defined as:
```Dart
static final SpringDescription _kDefaultSpring = SpringDescription.withDampingRatio(
  mass: 0.5,
  stiffness: 100.0,
  ratio: 1.1,
);
```
These properties can control the `SpringSimulator` built in scroll physics. You can change these properties to achieve your purposal.

**Comment by zmtzawqlp** [comment]
close with https://github.com/fluttercandies/extended_image/commit/f625d3ed2c6ba346620ef20346d74a603bf28d7f

**Comment by zmtzawqlp** [comment]
close with https://github.com/fluttercandies/extended_image/commit/f625d3ed2c6ba346620ef20346d74a603bf28d7f
