### ISSUE TITLE
对获取缓存数据文件总大小的支持

### ISSUE THREAD

**Issue by Hentioe** [fluttercandies/extended_image#154]
首先表示感谢。已在项目中用上这个库，很不错省了不少力。

给 App 添加清理图片缓存的功能，虽然能通过这个库提供的顶级 API 轻松做到，但还不够完美。一般相关功还会显示缓存数据的大小，让用户判断是否到了要清理的时候。

虽然我可以用 Java 代码间接的做到，但我觉得此功能应该由本库提供，毕竟它也算一个比较基本的需求。

**Comment by zmtzawqlp** [comment]
一般不是根据时间，来清除吗，会通过大小？？ 一张网络图片，今天你看到，明天看到，后天你就有可能刷不到了。

**Comment by Hentioe** [comment]
@zmtzawqlp 我的意思是在设置中提供「清理缓存」功能时，会顺带显示缓存占用大小。

例如知乎的设置：

![Screenshot_20200323-094353](https://user-images.githubusercontent.com/13946976/77271967-00843480-6ceb-11ea-830e-e74b6a8f3879.jpg)

你说的按时间有些类似开发层面的自动优化缓存的机制。当提供用户手动清理功能的时候，会提供一些缓存大小信息。

**Comment by Hentioe** [comment]
例如同类库 flutter_advanced_networkimage 就提供了相关 API：https://pub.flutter-io.cn/documentation/flutter_advanced_networkimage/latest/advanced_provider/DiskCache/cacheSize.html

虽然实现很简单，就是获取缓存目录大小。不过我可能要稍微看一下这个库的细节。所以我认为这类功能应该由本库提供。

**Comment by zmtzawqlp** [comment]
好的，明白你的意思了。会在后续支持
