### ISSUE TITLE
加载长图时，最开始时，图片没有顶部显示，而是居中的

### ISSUE THREAD

**Issue by oyh819** [fluttercandies/extended_image#159]
在加载长图时，图片没有顶部显示，而是居中的。设置了Alignment.topCenter也不起作用，但是这个字段对不是长图的有作用。sdk版本1.12.13+hotfix.8 

ExtendedImage.network(
                  item,
                  fit: BoxFit.contain,
                  enableSlideOutPage: true,
                  mode: ExtendedImageMode.gesture,
                  alignment: Alignment.topCenter,
                  ......
                )

**Comment by zmtzawqlp** [comment]
reopen if the latest version still has problem.

**Comment by oyh819** [comment]
还是有这个问题，现在版本都是最新的（3.0.0）

**Comment by zmtzawqlp** [comment]
请提供一个能复现问题的demo，以及图片

**Comment by longer96** [comment]
+ 1

比如传一张长图给该代码，[代码文件](https://github.com/fluttercandies/extended_image/blob/master/example/lib/common/widget/pic_swiper.dart)

是宽度100%，居中的显示的。无法设置为顶部显示，或者fit: BoxFit.cover

长图片路径：https://ziyoubao.oss-cn-chengdu.aliyuncs.com/test/img/16076652265555e69134018.jpg

感谢~

**Comment by zmtzawqlp** [comment]
fit: BoxFit.contains  这个是根据缩放来设置的。你最好看看demo

**Comment by 18335180686** [comment]
我也有这个问题，请问怎么解决呢？

**Comment by zmtzawqlp** [comment]
请参考demo的写法

**Comment by 18335180686** [comment]
> 请参考demo的写法

是的，demo就有这个问题。如果是长图在打开详情的时候，目前demo中只是把图片缩小到手机屏幕可以完全显示出来，而不是将图片的宽度放大到屏幕的宽度，图片的高度等比例放大，并从图片的头开始显示。

**Comment by zmtzawqlp** [comment]
demo 只考虑了 高比宽 大很多的情况，会把宽度放到屏幕宽度，并且高度等比例放大的，我还是没有重现你说的问题

**Comment by Orichy** [comment]
打开长图的时候，不是显示长图的顶部，而是显示长图中间部分，很难理解吗？

**Comment by jinyuanqing** [comment]
我也一样.项目中有个小需求,一侧图片,一侧文字.都靠容器的顶部显示,结果文字正常.图片无法显示在容器的顶部,而是居中.
![chrome_YrR6osvjTa](https://github.com/fluttercandies/extended_image/assets/12565969/2136779d-71aa-4ceb-bae3-f06153365919)
