### ISSUE TITLE
is it possible to support HEIC format which commonly used on iOS

### ISSUE THREAD

**Issue by zinwalin** [fluttercandies/extended_image#164]
appreciate your help.

**Comment by zmtzawqlp** [comment]
it's base on image code, i think your should get a help from flutter team.

**Comment by my6521** [comment]
你好，我也遇到同样的问题，flutter官方提供的 ImagePicker.pickImage只可以读取HEIC格式的图片，但使用这个插件就无法显示读取出来的FILE。希望能得到您的解决
