### ISSUE TITLE
How can i use zooming with image in a tab bar view?

### ISSUE THREAD

**Issue by febg11** [fluttercandies/extended_image#165]
I want to use this with a tab bar view but the zoom gestures do not work correctly as the tab bar horizontal swipes take over.

**Comment by zmtzawqlp** [comment]
that's flutter gesture arena.

ExtendedImageGesturePageView will done for it.

check code from 
https://github.com/fluttercandies/flutter_candies_demo_library/blob/master/lib/src/widget/pic_swiper.dart
