### ISSUE TITLE
加载某些图片会卡死

### ISSUE THREAD

**Issue by leielyq** [fluttercandies/extended_image#166]
在iOS 13的设备 加载多张图片就会卡死。
flutter 1.12.13 hotfix8或者9
新项目测试这个问题依旧可以复现。
下面是代码：
[
           ExtendedImage.network('https://img.jimmychat.com/data/users/10/head/2CDF36E4283D4EC0.png',cache: false,),
           ExtendedImage.network('https://img.jimmychat.com/data/topic/2020032114105115.jpeg',cache: false,),
           ExtendedImage.network('https://img.jimmychat.com/data/topic/2020032118285119.jpeg',cache: false,),
           ExtendedImage.network('https://img.jimmychat.com/data/topic/2020032114105151.jpeg',cache: false,),
          ]
可以帮忙测试一下吗？不使用cache是因为这样每次都会重新加载，加载卡死的问题就会出现。File存储的问题

**Comment by zmtzawqlp** [comment]
不会重新加载，内存里面还存的有，你这个图片太大了。内存爆炸了吧

**Comment by leielyq** [comment]
有可能唉，可是Android上面运行就没有问题。有点不知道怎么处理

**Comment by leielyq** [comment]
找到问题了 http的问题

**Comment by asd451398533** [comment]
http是什么问题啊 大佬

**Comment by zmtzawqlp** [comment]
ios http 证书好像会导致ui 卡住

**Comment by leielyq** [comment]
> http是什么问题啊 大佬

@asd451398533  我这边是证书问题，需要后台重新配置，flutter这边http直接忽略证书错误好像也不行，你可以试试

**Comment by asd451398533** [comment]
ios http 证书好像会导致ui 卡住  大佬能说详细点吗      是http的什么问题啊

**Comment by BestYun** [comment]
> ios http 证书好像会导致ui 卡住 大佬能说详细点吗 是http的什么问题啊
网上看到的
https://jhuo.ca/post/ocsp-stapling-letsencrypt/

ios13.3.1请求某些证书的https证书时会出现整个app卡死现象 #703
https://github.com/flutterchina/dio/issues/703
