### ISSUE TITLE
Error: No named parameter with the name 'animation'.             animation: animation,

### ISSUE THREAD

**Issue by vishalsaini9** [fluttercandies/extended_image#169]
flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.17.0 at /Users/vishal.saini/Downloads/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vishal.saini/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270

[✓] Connected device (3 available)
    • iPhone 6   • c0445b8f5e0548712bc1c733c6826fb8f39ac13f • ios            • iOS 12.4.4
    • Chrome     • chrome                                   • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server                               • web-javascript • Flutter Tools

• No issues found!

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/167
