### ISSUE TITLE
Can we get image height and width from network before the image is complete? I mean the image size in loading state.

### ISSUE THREAD

**Issue by karnadii** [fluttercandies/extended_image#172]

**Comment by zmtzawqlp** [comment]
see demo ，onstateChange
extendedImageInfo

**Comment by karnadii** [comment]
extendedImageInfo is always null when in LoadState.loading; I want to get the size for loading placeholder.

**Comment by zmtzawqlp** [comment]
can't get size before decode is finished

**Comment by karnadii** [comment]
ok, i thought i can get the size beforehand. thanks
