### ISSUE TITLE
change Color of Slide out image page?

### ISSUE THREAD

**Issue by fenchai23** [fluttercandies/extended_image#174]
is it possible to change the color of the slide out image page? what I see is only white.

I am using the transparent page route transition.

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/80310357-bcfe7800-880c-11ea-94db-b6f0e2aa5f80.png)

**Comment by fenchai23** [comment]
thank you

**Comment by fenchai23** [comment]
I am trying to use the same example as on the readme but it says The argument type 'Color' can't be assigned to the parameter type 'Color Function(Offset,Size)' 

So if I remove the Color from the function

it then says The method 'withOpacity' was called null.

I searched for an example of this but no results

**Comment by zmtzawqlp** [comment]
``` dart 
 return ExtendedImageSlidePage(
      slidePageBackgroundHandler:(Offset offset, Size pageSize)
      {
        return Colors.blue;
      }
    )
```
you  can change color base on offset and pageSize

**Comment by fenchai23** [comment]
thanks that was very simple, I'm an idiot 🤦
