### ISSUE TITLE
Request to add cacheHeight and cacheWidth params

### ISSUE THREAD

**Issue by humazed** [fluttercandies/extended_image#175]
My app always crashes with out of memory errors.
I can't reduce the image sizes from the server because I don't have control over it.
I had to use `Image.network` only because of `cacheHeight` and `cacheWidth`

**Comment by zmtzawqlp** [comment]
why don't use as  following: 
```dart
    ExtendedImage(
        image: ResizeImage.resizeIfNeeded(
            100,
            100,
            ExtendedNetworkImageProvider(
              '',
              scale: 1.0,
            )));
```
