### ISSUE TITLE
1.17.0 编译不通过了

### ISSUE THREAD

**Issue by cv0cv0** [fluttercandies/extended_image#178]
Launching lib/main.dart on sdk gphone x86 64 arm64 in debug mode...

Compiler message:
../../../../Library/Flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../Library/Flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
../../../../Library/Flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../Library/Flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
FAILURE: Build failed with an exception.
* Where:
Script '/Users/hzlx/Library/Flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/hzlx/Library/Flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by talhabalaj** [comment]
Same issue here

**Comment by RoryHyman** [comment]
加一

**Comment by zinwalin** [comment]
一样。

`Launching lib/main.dart on Redmi K30 in release mode...
                                                                        
Compiler message:                                                       
../flutter/.pub-cache/git/extended_image-6c27312ba1f96df566ff9a28cbd347d7fbe38e52/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,                                           
        ^^^^^^^^^                                                       
../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({                                 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/michael/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/michael/Development/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 35s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      36.2s
Gradle task assembleRelease failed with exit code 1`

**Comment by cv0cv0** [comment]
@zinwalin @talhabalaj @hrongyong

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/160

**Comment by zmtzawqlp** [comment]
extended_image: 0.7.3-dev
