### ISSUE TITLE
Disable auto zoom or auto center on editor

### ISSUE THREAD

**Issue by fenchai23** [fluttercandies/extended_image#181]
Is there a way to prevent auto center or auto zoom when cropping?

I would like to just crop without the auto zoom while moving the corners.

I tried changing the animation duration to 0 but that didn't work

**Comment by zmtzawqlp** [comment]
auto center must be done, it relates to algorithm

**Comment by fenchai23** [comment]
I see what about ability to custom ratios instead of fixed ratios? would be nice to be able to change the 4 corners manually instead of having to rely on fixed ratios and only being able to zoom in and out.

**Comment by zmtzawqlp** [comment]
don't support for now
