### ISSUE TITLE
loadingProgress always equals null 

### ISSUE THREAD

**Issue by unknown1101** [fluttercandies/extended_image#186]
loadStateChanged: (ExtendedImageState state) {
                            print(state.loadingProgress); 

                           }
         

as Title of question Loading Progress property always equals null

**Comment by zmtzawqlp** [comment]
more code

**Comment by yleencc** [comment]
Solution: add "handleLoadingProgress: true" in ExtendedImage.network().

The handleLoadingProgress is closed by default in the source of ExtendedImage.network().
Full code: 
```dart
ExtendedImage.network(
    imageUrl,
    handleLoadingProgress: true,
    loadStateChanged: (ExtendedImageState state) {
        print(state.loadingProgress);
    }
}
```

加上`handleLoadingProgress: true`就能正常获取loadingProgress了，对于ExtendedImage.network()这一项默认是关闭的...
