### ISSUE TITLE
添加仿微信图片滑动退出页面效果后，放大图片 滑动到垂直方向边缘后不能往回滑动了

### ISSUE THREAD

**Issue by sabernwj** [fluttercandies/extended_image#188]
demo里的photoview里也有同样的问题，好像是触发了ExtendedImageSlidePage里的slideOffsetHandler后图片原有的拖拽滑动失效了，能否自己判定是否

**Comment by zmtzawqlp** [comment]
不能重现

**Comment by sabernwj** [comment]
![QQ图片20200518185256](https://user-images.githubusercontent.com/22236457/82205229-d04ac200-9938-11ea-86b9-91b9ed9cf867.gif)

**Comment by zmtzawqlp** [comment]
去群里。找alex看看

**Comment by sabernwj** [comment]
暂时解决了，在extended_image_gesture.dart里的_handleScaleUpdate里添加了一句
`if(_gestureDetails.totalScale>1.0) updateGesture=false;`
