### ISSUE TITLE
Implement circular crop

### ISSUE THREAD

**Issue by visual-velocity** [fluttercandies/extended_image#193]
First of all thank you publish this library but We need circular crop feature inside this library.
Can you suggest me how can we implement this feature in our production app because we need it asap.

**Comment by zmtzawqlp** [comment]
shape | BoxShape.circle and BoxShape.rectangle,If this is [BoxShape.circle] then [borderRadius] is ignored.
-- | --


does it what you want??

**Comment by visual-velocity** [comment]
hi

I want to show a cropped area in a circular shape, and am sharing the
sample.

**Comment by visual-velocity** [comment]
Help me,i need it and implement on profile page of my production app.

**Comment by visual-velocity** [comment]
<img width="771" alt="Screenshot 2020-05-20 at 4 57 03 PM" src="https://user-images.githubusercontent.com/63794674/82447924-960f2b00-9ac6-11ea-99d4-1dc41b394a10.png">

**Comment by zmtzawqlp** [comment]
you can do it with CustomPaint. paint mask and clear circular

**Comment by visual-velocity** [comment]
I'm trying this, but i'm failed and I need it urgently because my
organization wants to release the production app at the end of this month.
So I request that you give the code please.

**Comment by AlexVincent525** [comment]
To be clear, is there a specific area (e.g. crop 60x60 in a 120x120 image with 10 px left and 10 px top) or just make them as circles without any details?

**Comment by visual-velocity** [comment]
If it is possible to specify the area by user end then it's very useful to us.

**Comment by AlexVincent525** [comment]
> If it is possible to specify the area(custom) by user end then it's very useful to us.

As I thought, user end doesn't have a request to specify a custom area to make a circle or something. If you're thinking about a cover photo like the one in Facebook, then I have to tell you that this should be done in the back end side rather than on the client side, upload a cropped image with a proper area, with detailed crop info.

A single implementation for a circle avatar without extra code would be:
```dart
CircleAvatar(
  backgroundImage: NetworkImage('your_image_link'),
)
```

At the end, a circular crop is nothing related to this package, so closing it because it's unrelated. Feel free to ask more about your implementation.

**Comment by visual-velocity** [comment]
HI,
Can you tell me how to make or draw and show the circular cropping area
above the image like a rectangular cropping area because i'm unable to
create a code for a circular area.As per your library and example we show
only rectangular cropping area.
[image: image.png]

**Comment by AlexVincent525** [comment]
> Can you tell me how to make or draw and show the circular cropping area above the image like a rectangular cropping area because i'm unable to create a code for a circular area.

Ref:
* [ClipRRect](https://api.flutter.dev/flutter/widgets/ClipRRect-class.html)
* [ClipOval](https://api.flutter.dev/flutter/widgets/ClipOval-class.html)

**Comment by zmtzawqlp** [comment]
It's better to ask such question in so.

``` dart
  return LayoutBuilder(
      builder: (BuildContext c, BoxConstraints d) {
        Rect crop = Offset.zero & Size(d.maxWidth, d.maxHeight);
        crop = crop.deflate(100.0);
        return SizedBox(
          width: d.maxWidth,
          height: d.maxHeight,
          child: CustomPaint(
            child: Image.network(
              'https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2534506313,1688529724&fm=26&gp=0.jpg',
              fit: BoxFit.fill,
            ),
            foregroundPainter: MyCustomPainter(crop),
          ),
        );
      },
    );


class MyCustomPainter extends CustomPainter {
  MyCustomPainter(this.crop);
  final Rect crop;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.saveLayer(Offset.zero & size, Paint());
    //paint mask

    canvas.drawRect(
        Offset.zero & size,
        Paint()
          ..color = Colors.grey.withOpacity(0.5)
          ..style = PaintingStyle.fill);

    ///clear
    canvas.drawRect(crop, Paint()..blendMode = BlendMode.clear);
    //line
    canvas.drawRect(
        crop,
        Paint()
          ..color = Colors.white
          ..style = PaintingStyle.stroke
          ..strokeWidth = 3);
    canvas.restore();
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    if (oldDelegate.runtimeType != runtimeType) {
      return true;
    }
    return crop != (oldDelegate as MyCustomPainter).crop;
  }
}



```

**Comment by kiaxseventh** [comment]
@prasantco
@zmtzawqlp
@AlexV525

are you found a solution ? can you share example code ?   thanks

**Comment by zmtzawqlp** [comment]
here are the demo. https://github.com/fluttercandies/extended_image/blob/978092941fbe5e241221ba885f88263d3344c51b/example/lib/pages/complex/image_editor_demo.dart#L495
