### ISSUE TITLE
dynamic initialAlignment on ExtendedImageGesturePageView

### ISSUE THREAD

**Issue by ynixt** [fluttercandies/extended_image#194]
I'm using ExtendedImageGesturePageView and I need that when I go next my page the value of InitialAlignment be InitialAlignment.topCenter, but when I go back the value be InitialAlignment.bottomCenter.

Theres somehow to do this?

My big problem is that initGestureConfigHandler is called before than onPageChanged, so I can't create a logical like 'swiping down'.

**Comment by zmtzawqlp** [comment]
'swiping down' ？？ what do you want really?

**Comment by ynixt** [comment]
The 'swiping down' that I want to say is when scrollDirection is setting to Axis.vertical and I can swipping down or up to change page. But when I swipping up (previous page) I need that the initial aligment change do bottomCenter because this way it will be more intuitive for the user since the image that will appear will be at the point it was before he changed pages.

**Comment by zmtzawqlp** [comment]
why set it when pagechange？ we can set it when item is building

**Comment by ynixt** [comment]
I have tried this but sometimes the pageChange is called after initGestureConfigHandler and correct me if I'm wrong, but the only place that I can set initialAlignment is on GestureConfig of initGestureConfigHandler, correct?

**Comment by zmtzawqlp** [comment]
why set it at page change?? i didn't get your point. small demo will be better

**Comment by ynixt** [comment]
Today I realized that setting cacheGesture to true is enough to me. Thanks anyway

**Comment by zmtzawqlp** [comment]
ok, remember to clear them at right time.
