### ISSUE TITLE
ExtendedImageGesturePageView 预先加载图片问题

### ISSUE THREAD

**Issue by gaoyong06** [fluttercandies/extended_image#195]
这个问题在[https://github.com/fluttercandies/extended_image/issues/24](url)
有问过，然后我使用precacheImage测试了一下，发现并没有预先加载到

我的做法大概是这样, 关键代码是下面这样，删掉了一些无关的代码：

`

    //这是原图(大图)Url组成的列表
    List<String> originalImageUrlList = [......];

    ...
    
    @override
    Widget build(BuildContext context) {

    // 预先加载图片
    //页面build时，循环originalImageUrlList列表，把所有的原图预加载一遍
    originalImageUrlList.forEach((element) {
      precacheImage(CachedNetworkImageProvider(element), context);
    });
    
    ....
    
    //这里显示原图中的一个
    var originalImageItem = originalImageUrlList[index];
    ExtendedImage.network(originalImageItem,

            fit: BoxFit.cover,
            mode: ExtendedImageMode.gesture,
            cache: true,

           //图片加载进度
           handleLoadingProgress: true,
           loadStateChanged: (ExtendedImageState state){
              switch (state.extendedImageLoadState) {
                case LoadState.loading:
                  ImageChunkEvent loadingProgress = state.loadingProgress;
                  double progress = loadingProgress?.expectedTotalBytes != null
                    ? loadingProgress.cumulativeBytesLoaded /
                        loadingProgress.expectedTotalBytes
                    : 0;
                  print("加载进度：${progress * 100 }");

              }
              break
    ...

`

请问这是我是哪里搞错了?

**Comment by zmtzawqlp** [comment]
你为啥用别人的provider？？
CachedNetworkImageProvider

肯定要用extended image的啊。。不然内存里面存的是CachedNetworkImageProvider

**Comment by zmtzawqlp** [comment]
有其他问题的话。再开新的issue
