### ISSUE TITLE
和NestedScrollView搭配时平移缩放时灵时不灵

### ISSUE THREAD

**Issue by cdhigh** [fluttercandies/extended_image#196]
我希望全屏查看图像时能自动隐藏AppBar，提高可视面积，所以使用了 NestedScrollView
差不多类似这样：
build() {
    return NestedScrollView(
        headerSliverBuilder: buidSliverHeader,
        body: ExtendedImage.file(...)
}
但是发现手势不灵敏，时灵时不灵，改成Scaffold则一切正常，但是就一直有AppBar，我试过去掉AppBar，但是发现体验不好，返回不方便。

这应该是和 NestedScrollView的手势有冲突，这个问题有办法解决吗？

**Comment by zmtzawqlp** [comment]
改成Scaffold则一切正常，但是就一直有AppBar
建议这类问题去问百度google或者so

**Comment by cdhigh** [comment]
已经解决，不能和NestedScrollView一起使用，还得是Scaffold。
谢谢，组件很好用
