### ISSUE TITLE
OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by visual-velocity** [fluttercandies/extended_image#199]
I cannot upload image from gallery. This is my logcat
FileSystemException: Cannot open file, path = '/storage/emulated/0/DCIM/s9camera/Pic_2020_06_04_19_36_15.jpg' (OS Error: Permission denied, errno = 13).Android - 29
I'm using permission_handler package for handle permission. Storage and Access Media Location permission has already granted by user but the issue is generated every time when pick image or video from external storage. Inside manifest file we have added android:requestLegacyExternalStorage="true"
Suddenly i get issue on the production app , please support us

**Comment by AlexVincent525** [comment]
Can you provide a minimal usage about what feature/method/function you are calling, and which part has this issue?

**Comment by visual-velocity** [comment]
Hi,
Thank you for your response. I used *file_picker* and
*permission_handler*(latest
version) for getting permission of Storage and Media location permission of
Android Platform and used* Android SDK version 29*(compileSDK and
TargetSDK) *minimum sdk version 21*. File_Picker library has also included
Storage and Media location permissions. I tested my production app with
permission_handler and without permission_handler.
Once I get granted both permission, I use to pick a single image file and
pass it to an example that's given inside your package. Then I got this
exception.

**Comment by AlexVincent525** [comment]
I'm confusing what relationship is your case related to ours, but neither `file_picker` nor `permission_handler` belong to our organizations. So I'm closing this because it's unrelated.

If there's something related that didn't mentioned, please provide more information.

**Comment by visual-velocity** [comment]
I'm finding the issue please upgrade your library with Android 29.
Upgrade
compileSdkVersion 28 to compileSdkVersion 29
targetSdkVersion 28 to
targetSdkVersion 29 in build file
android:requestLegacyExternalStorage="true" in Manifest file

**Comment by AlexVincent525** [comment]
> please upgrade your library with Android 29

The `extended_image` didn't have the part which integrated with **Android** platform.

**Comment by visual-velocity** [comment]
I'm so sorry Please ignore my last message or comment. Thank you for your
support. It's really appreciated.
