### ISSUE TITLE
Wrong in handling picture swiper's gesture.

### ISSUE THREAD

**Issue by AlexVincent525** [fluttercandies/extended_image#2]
When one of the pictures' scale greater than 1.0, swipe on the left or right edge of this picture, as expected swiper will switch to next or previous picture. But at this time if user drag reverse direction, the picture which has been scaled will be scrolled, and the pageview stuck.

Expectaion: The picture which has been scaled won't be scrolled when swiping.

当图片序列中有一张图片的缩放>1，从此图片的左右进行拖动切换图片，设计中将正常切换到下一张或上一张图片，但当手势反向时，该图片将被拖动，pageview卡在原位。

期望：被缩放的图片滑动切换时不被拖动。

**Comment by zmtzawqlp** [comment]
@AlexVincent525 hi，guy，fix it with ad18afa69a880f50e21e6b6202efde53f170b2b6 ,please update version to 0.2.6, please let me konw if it has fixed.

**Comment by AlexVincent525** [comment]
Thanks anyway. :)
