### ISSUE TITLE
ExtendedImage.asset 在 ExtendedImageSlidePage 中出现 hero 动画消失

### ISSUE THREAD

**Issue by gitKun** [fluttercandies/extended_image#203]
在使用 ExtendedImage.asset 加载本地图片展示照片浏览界面时，hero 动画会出现 push 消失， pop 正常的 BUG，使用  ExtendedImage.network 时正常

使用 ExtendedImage.network 正常
![bug1](https://user-images.githubusercontent.com/11701187/83989806-321bac00-a97a-11ea-9b0b-3b9b3e8d51e3.gif)

使用  ExtendedImage.asset 

![bug2](https://user-images.githubusercontent.com/11701187/83989837-45c71280-a97a-11ea-9af9-0c06c6084a20.gif)

示例项目地址： [demo](https://github.com/gitKun/ExtendedImage_BUG)

**Comment by zmtzawqlp** [comment]
简单的复现demo，没有那么多时间看这么多代码
