### ISSUE TITLE
[Feature request] Ability to rotate an image on custom angle using fingers

### ISSUE THREAD

**Issue by stepanov-standy** [fluttercandies/extended_image#204]
It is awesome and powerful library, but looks like it doesn't have so important and I hope simple in implementation feature to be able to rotate image on custom angle using fingers. There are lots of use cases when user wants to crop image and slightly rotate it.

Is it possible to add such functionality in future releases?

**Comment by zmtzawqlp** [comment]
It' hard to implement. The algorithm is not only for how to crop but UI,  i have no idea for now.

**Comment by stepanov-standy** [comment]
Thank you for the quick response. I will try to search for possible solutions and provide my insights on this. Do you mean it is hard to implement crop of rotated image on each platform? Or it is hard to reflect rotation in flutter UI?

**Comment by zmtzawqlp** [comment]
I mean flutter UI,I didn't come up with a good idea to calculate boundary after rotate ,and how to convert ui to the arguments for native api.

**Comment by tompg1** [comment]
> Thank you for the quick response. I will try to search for possible solutions and provide my insights on this. Do you mean it is hard to implement crop of rotated image on each platform? Or it is hard to reflect rotation in flutter UI?

Did you find a solution to this?

**Comment by punzar** [comment]
https://github.com/xclud/flutter_crop 
This lib can help you. It calculate boundary after rotate

**Comment by stepanov-standy** [comment]
I have switched to this library that can do all required things - https://pub.dev/packages/photo_view
