### ISSUE TITLE
crashlytics report

### ISSUE THREAD

**Issue by NicolasCELLA** [fluttercandies/extended_image#205]
Hello, when an image is not load, i have a report on crashlytics ! 
An idea hoe to stop this ?

**Comment by zmtzawqlp** [comment]
It's in flutter sdk, you don't need care about it

**Comment by NicolasCELLA** [comment]
Yes but it's a real problem with a big app ! All my reports is only fron this problem !

I know "cached_network_image" doesn't have this problem

**Comment by NicolasCELLA** [comment]
if :
```
return Future<ui.Codec>.error(StateError('Failed to load $url.'));
```
is removed, this create some problem ?

**Comment by zmtzawqlp** [comment]
you can create your provider to avoid it.

**Comment by NicolasCELLA** [comment]
sorry, what do you mean by " provider to avoid " ?

**Comment by dvird** [comment]
how you solved it? my crashlytics has 10k errors because of that

**Comment by yyyy-ltd** [comment]
@zmtzawqlp hi can see the above image? we need to improve the error handling
