### ISSUE TITLE
Layout problem  布局问题

### ISSUE THREAD

**Issue by 343629302** [fluttercandies/extended_image#208]
If I need to wrap a Stack on the outer layer of ExtendedImageSlidePage. So how does the gesture penetrate into the ExtendedImage. Because there may be Positioned on it.

如果我需要在ExtendedImageSlidePage 外层套一层Stack，并且Stack 会有Positioned组件。那么手势如何穿透到ExtendedImage 组件里面？

Or is this layout not supported for now?
还是现在暂时不支持这种布局？

**Comment by 343629302** [comment]
![微信图片编辑_20200622142313](https://user-images.githubusercontent.com/48002442/85255040-0e855500-b494-11ea-956f-0f92cfce1504.jpg)

For example, this layout may have two Positioned up and down in the Stack. How to make the gesture penetrate into the ExtendedImage when the Positioned slides left or right or drags up and down

例如这种布局可能Stack 里面有上下2个Positioned 。如何让手势在Positioned 左右滑动或者上下拖拽的时候穿透到ExtendedImage里面

**Comment by zmtzawqlp** [comment]
你看看我的demo，看看对你有帮助没有。。手势这个你只能从image里面拿
