### ISSUE TITLE
[Question] How to access get currentScale 

### ISSUE THREAD

**Issue by Arcrueid** [fluttercandies/extended_image#209]
Hi
First of all, great plugin <3

I need a little more control in the gallery and I wanted to know if is there a way to get the current scale? In the case of single tap on the image?

**Comment by zmtzawqlp** [comment]
you can get  state from extendedImageGestureKey,  scale is in gestureDetails

**Comment by Arcrueid** [comment]
sorry but you can't give me an example since it always returns 1.0
I need create single tap event on image and capture the current scale.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/ed5d496ee8313ded27c8c9eff1ff206335a3840d/example/lib/pages/zoom_image_demo.dart#L24

**Comment by Arcrueid** [comment]
I try to access in GestureDetector but always get null from gestureKey.currentState

[https://github.com/fluttercandies/flutter_candies_demo_library/blob/e27c29f4fe87a7aaf0dfe8a450a952762a58577e/lib/src/widget/pic_swiper.dart#L269](url)

**Comment by zmtzawqlp** [comment]
can you provide a single demo for this ? do you set key as the same as zoom_page_demo.dart??

**Comment by zmtzawqlp** [comment]
you should set key at this place.

https://github.com/fluttercandies/flutter_candies_demo_library/blob/e27c29f4fe87a7aaf0dfe8a450a952762a58577e/lib/src/widget/pic_swiper.dart#L224

**Comment by Arcrueid** [comment]
Yes,
I set:

`final GlobalKey<ExtendedImageGestureState> _gestureKey = GlobalKey<ExtendedImageGestureState>();`

and assign:

` Widget image = ExtendedImage.network(
                item,
                fit: BoxFit.contain,
                enableSlideOutPage: true,
                mode: ExtendedImageMode.gesture,
                extendedImageGestureKey: _gestureKey,`

but in the external GestureDetector always return null for current state

`image = GestureDetector(
                child: image,
                onTap: () {
                  print(_gestureKey.currentState.gestureDetails.totalScale);
                },
              );`

**Comment by zmtzawqlp** [comment]
in my demo,  ExtendedImageGesture is override at https://github.com/fluttercandies/flutter_candies_demo_library/blob/e27c29f4fe87a7aaf0dfe8a450a952762a58577e/lib/src/widget/pic_swiper.dart#L224  , you can set it at this place.

**Comment by Arcrueid** [comment]
yeah now works!

TY!
