### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by kerneltea** [fluttercandies/extended_image#215]
首先不得不承认这个库，是FLUTTER当下比较好的图片处理的库，但是有一点不是很理解，这个库是为了让广大开发者练练手呢，还是想让大家用在自己的项目里呢。一般大型的flutter项目都是在1.16的版本之前，现在想用这个库需要用1.17的版本.。2020年5月刚发的稳定版。。这让很多人都没办法在项目里用呀。。而且除了这个库以外，大型的开发项目都要依赖很多的库。那些库可能并不支持1.17的版本。。这就是去舍留的问题了。。。

**Comment by zmtzawqlp** [comment]
1.版本是跟着stable走。
2.你可以使用固定版本来限制sdk。
3.或者使用特定的branch（比如v1.12.13，功能会同步）。
4.至于太低或者master branch，没有那么多时间维护，抱歉。

**Comment by kerneltea** [comment]
好的谢谢
