### ISSUE TITLE
White filter boundaries sometimes don't scale to the edge of the widget

### ISSUE THREAD

**Issue by Letalus** [fluttercandies/extended_image#220]
I'm not entirely sure, if this is a bug or a feature in your package.
What I was expecting when the user zooms in and out of the image that the (cropped) image always adjusts itself to the ExtendedImage boundaries.

But the current behaviour in the package is that it sometimes adjust itself to the ExtendedImage boundaries und sometimes not. I made a video where this behaviour is highlighted 

https://dayblizz.slack.com/files/UTN7GRUDN/F01725A7C1M/20200721_225303.mp4?origin_team=TTN7GRSHW&origin_channel=Vall_threads

**Comment by zmtzawqlp** [comment]
please provide runnable demo.

**Comment by Letalus** [comment]
nvm this has been fixed. Greets
