### ISSUE TITLE
Possible to use loadStateChanged with ExtendedNetworkImageProvider?

### ISSUE THREAD

**Issue by guit4eva** [fluttercandies/extended_image#221]
I am needing to use a placeholder while loading a background image of a container:

```
DecorationImage(
    image:  ExtendedNetworkImageProvider()
    ...
```

Is there a workaround for that? It seems like loadStateChanged  is only available for ExtendedImage.network().

**Comment by zmtzawqlp** [comment]
why don't use image and stack
