### ISSUE TITLE
CropAspectRatio also rotates when rotating an Image in Image Editor

### ISSUE THREAD

**Issue by eriko13** [fluttercandies/extended_image#222]
When rotating an Image, the CropAspectRatio also rotates with it.

I find this as a bug. Because if you want to use a strict aspect ratio for let's say, a profile cover image(1000px, 200px) you would have a problem at the moment the user rotates the image.  

CropAspectRatio should stay the same after rotating. 
Thanks

**Comment by zmtzawqlp** [comment]
This is as design. It keeps CropRect is all in.

**Comment by dahvlhldle** [comment]
@zmtzawqlp I need to keep CropAspectRatio constant.For example,shooting ID card,Picture direction is vertical.
Can add field?`ExtendedImage(keepCropAspectRatio:true)` 
Thanks
