### ISSUE TITLE
你们组织是真牛逼，不发言，没有说明，直接踢人，禁言

### ISSUE THREAD

**Issue by quanke** [fluttercandies/extended_image#223]
![image](https://user-images.githubusercontent.com/2666952/89001366-97fa3380-d32c-11ea-8b8c-708c9fb39487.png)
![image](https://user-images.githubusercontent.com/2666952/89001375-a0eb0500-d32c-11ea-9061-187def92f09b.png)

![image](https://user-images.githubusercontent.com/2666952/89001462-dee82900-d32c-11ea-9336-73bfea40dd67.png)

这是服了，这么管理，瞎搞，群里发红包，抢红包，被踢了，什么鬼逻辑

**Comment by zmtzawqlp** [comment]
如果你觉得这个群对你有帮助，请按照群公告来，或者能够多做一些贡献。如果一个人在一个群里，半年都没有发言，我只能说，这个群对他来说没有任何意义。在和不在都没有区别
