### ISSUE TITLE
Slide Out Page - Is there any way to setting non-linear offset?

### ISSUE THREAD

**Issue by furkansarihan** [fluttercandies/extended_image#225]
Hello there, I guess this is a future request.

Is there any way to setting non-linear slide offset?

As far as I can see, We need a slide-delta parameter.

This is my current function. It stops when image reaches to %30 of screen height. 
```
slideOffsetHandler: (Offset offset, {ExtendedImageSlidePageState state}) {
          double limit = m.screenH() * 0.3;
          double dy = offset.dy < limit ? offset.dy : limit;
          dy = dy < 0 ? 0 : dy;
          return Offset(0, dy);
        },
```
I want to set the final offset related to slide-delta.

**Comment by zmtzawqlp** [comment]
you can save pre dy ,and delta is now - pre

**Comment by furkansarihan** [comment]
@zmtzawqlp Sorry, I was wrong by saying slide-delta. I can not calculate the total swipe distance.

I mean by total swipe: abs(slideDragStartOffset - currentDragOffset)

With this distance custom slide offset becomes easy for my use case. 

And in my case I can not gather the required variables with another GestureDetector (I guess).

Am I missing something?

**Comment by zmtzawqlp** [comment]
offset is total swipe already

**Comment by furkansarihan** [comment]
@zmtzawqlp Okay, I really can't see what I need. Can you provide an example function for a different behaviour than default?

**Comment by furkansarihan** [comment]
Not an issue

**Comment by furkansarihan** [comment]
-
