### ISSUE TITLE
I want to propose a new feature

### ISSUE THREAD

**Issue by 343629302** [fluttercandies/extended_image#227]
Can I add a placeholder image and a fade-in and fade-out function for the image after loading? It's weird to switch instantly now.

可以增加一个占位图和加载完毕的图片的淡入淡出功能吗？现在占位图和图片瞬间切换。感觉有点怪怪的。

**Comment by zmtzawqlp** [comment]
demo里面不是有教怎么写吗

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/c3e9b9d8d91ea72520670788ed554df661a5fd98/example/lib/pages/simple/custom_image_demo.dart#L87
