### ISSUE TITLE
发生异常：Adreno DequeueBuffer: dequeueBuffer failed

### ISSUE THREAD

**Issue by kokocooler2020** [fluttercandies/extended_image#229]
页面是一个ListView, 每个Item有三张图片，图片使用ExtendedImage显示，ListView大约100行，即300张图片，当快速滑动ListView时，在网络不好的情况下会发生Adreno DequeueBuffer: dequeueBuffer failed, 目前不确定是本插件导致，也可能是app代码性能问题，先贴出来。

Adreno DequeueBuffer: dequeueBuffer failed应该是一个GPU错误，貌似是GPU刷新频率过高或跳帧太多导致的，于是尝试修改此插件源码中的extended_image.dart中的setState()部分，setState函数需要传入的函数在Timer启动前之前直接执行，然后使用Timer延迟调用setState((){})，两次setState()间隔小于5毫秒则cancel掉上一次刷新的Timer, 这样修改无效，依然会发生上述错误，并导致app卡住。

插件版本是目前最新版本：1.1.1

**Comment by zmtzawqlp** [comment]
ListView shrinkWrap : true?
你可以把clearMemoryCacheWhenDispose 设置为true试试
