### ISSUE TITLE
Refresh image url

### ISSUE THREAD

**Issue by ManojMM026** [fluttercandies/extended_image#23]
Can you tell me how can I refresh image cache for particular image URL?
Use case : 

> I upload the image to firebase storage with the same name(which replaces existing image). When I clear app data I get the correct image, It seems that the same URL image is not being downloaded again(Which is intended behavior) but I would like to refresh that image URL manually.

**Comment by zmtzawqlp** [comment]
try clearDiskCachedImage to clear particular url cached
