### ISSUE TITLE
The cache property is specified as false. However, if I replace the image represented by a web address and refresh the image represented by this URL, the image does not change

### ISSUE THREAD

**Issue by LinJinghuidev** [fluttercandies/extended_image#230]
The cache property is specified as false. However, if I replace the image represented by a web address and refresh the image represented by this URL, the image does not change

**Comment by zmtzawqlp** [comment]
cache means cache image into local. but image will cache in memory by image url, it's the same as NetworkImage

**Comment by LinJinghuidev** [comment]
Is there any way to refresh the new pictures with the same address on the current page

**Comment by LinJinghuidev** [comment]
Or do you know what controls can be implemented other than downloading images for display

**Comment by zmtzawqlp** [comment]
you can override image provider, and check cache flag by your self.https://github.com/fluttercandies/extended_image_library/issues/20
