### ISSUE TITLE
重新加载图片，加载失败

### ISSUE THREAD

**Issue by lionnner** [fluttercandies/extended_image#231]
如下场景：加载了一张网络图片此时是404，稍等2s后图片已经存在了，再次进入界面直接报错Fail to load...，都没有进入到进行图片请求那一步。

**Comment by lionnner** [comment]
加载失败后，应该        PaintingBinding.instance.imageCache.evict(key); 不然没杀死APP的前提下，会一直用cache的provider

**Comment by zmtzawqlp** [comment]
clearMemoryCacheIfFailed
