### ISSUE TITLE
retain zoom state after loading

### ISSUE THREAD

**Issue by clragon** [fluttercandies/extended_image#233]
I use lower res picture as widget in loading state.
Just two extended image inside each other, one with high res url and one with low res url.
Low res url one is inside the high res one, returned when loading.

example: 

```
ExtendedImage(
    extendedImageGestureKey: Key(imageID),
    enableLoadState: true,
    loadStateChanged: (state) {
        if (state.extendedImageLoadState == LoadState.loading) {
            return ExtendedImage(
                extendedImageGestureKey: Key(imageID),
                image: CachedNetworkImageProvider(lowres),
            );
        }
        return null;
    },
    image: CachedNetworkImageProvider(highres),
)
```

When the high res image is loaded, zoom resets. Is it possible to retain same zoom after loading?
I tried assigning the same extended image gesture key, but it does nothing.

**Comment by zmtzawqlp** [comment]
as design, we could zoom after image is already loaded, may be we should not zoom with loading state
