### ISSUE TITLE
Can we have 6 or 8 edge cropper?

### ISSUE THREAD

**Issue by sumit03111988** [fluttercandies/extended_image#234]
Hi,

Your work is highly appreciable. It looks amazing.

Can you please guide me to get the 6 or 8 edge cropper instead of 4 only. It would be good in case you can include it or guide me how can I achieve it.

Thanks in advance.

**Comment by AlexV525** [comment]
If you are talking about multiple edge image cropping, it's not supported and might be not supportive in the future. So I'm going to close this with `wontfix`.

Feel free to add more info about your request.
