### ISSUE TITLE
Flickering when zooming out

### ISSUE THREAD

**Issue by Chralu** [fluttercandies/extended_image#235]
Hi, 
Thanks for that great tool !

# How to reproduce issue 

1. Run that code : 
```
void main() async {
  runApp(
    MaterialApp(
      home: ExtendedImage.network(
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/2017-03_Bologna_Mattes_Pana_%2881%29.JPG/1920px-2017-03_Bologna_Mattes_Pana_%2881%29.JPG',
        fit: BoxFit.contain,
        mode: ExtendedImageMode.editor,
        initEditorConfigHandler: (state) {
          return EditorConfig(
              maxScale: 4.0,
              cropRectPadding: EdgeInsets.all(20.0),
              hitTestSize: 20.0,
              cropAspectRatio: 1.5);
        },
      ),
    ),
  );
}
```

2. Pinch out to zoom beyond minimum zoom

Observation : The image flickers a bit. It zooms out beyond limit, then is quickly reset to minimum zoom.

**Comment by zmtzawqlp** [comment]
i can't zoom beyond minimum zoom at my side

**Comment by Chralu** [comment]
Here is how it behaves when pinching out beyond limit.
![zoom_out](https://user-images.githubusercontent.com/375723/94236976-65c11880-ff0e-11ea-971d-56546d4d10f3.gif)

**Comment by zmtzawqlp** [comment]
it didn't look as we do, ScaleUpdateDetails also provide offset and  scale(>1.0) when we zoom out at that monment.

**Comment by zmtzawqlp** [comment]
I/flutter (17909): 1.0
I/flutter (17909): 0.9988947961111486
I/flutter (17909): 0.9988947961111486
I/flutter (17909): 0.9977900020482547
I/flutter (17909): 0.9977900020482547
I/flutter (17909): 0.9958129374301814
I/flutter (17909): 0.9958129374301814
I/flutter (17909): 0.9929633178372261
I/flutter (17909): 0.9929633178372261
I/flutter (17909): 1.0041964297358636
I/flutter (17909): 1.0041964297358636
I/flutter (17909): 1.0001868739590598
I/flutter (17909): 0.9993015553995158
I/flutter (17909): 0.9952925009699909
I/flutter (17909): 0.9944070413042475

**Comment by zmtzawqlp** [comment]
please update to 1.1.2

**Comment by Chralu** [comment]
Wow thanks for that quick fix ! The flickering issue is resolved :)

I'm having another small issue on zoom out : #236
