### ISSUE TITLE
切图不正确

### ISSUE THREAD

**Issue by shenlanchenwei** [fluttercandies/extended_image#238]
1. 当截图的比例设置成NULL (cropAspectRatio: CropAspectRatios.custom)的一个宽图,旋转90度再截图,保存后的图片还是旋转前的宽高,而出现留白,高图好像没有问题,宽图有问题

选定区域

![image](https://user-images.githubusercontent.com/6754634/94504189-cddb6b80-023a-11eb-8979-398ead494bd1.png)

截图保存后的图片

![image](https://user-images.githubusercontent.com/6754634/94504263-f5323880-023a-11eb-8493-c80afa78c7f8.png)

**Comment by zmtzawqlp** [comment]
图+demo

**Comment by zmtzawqlp** [comment]
还有期待现象是什么，宽图。长宽比已经很奇怪了。建议不要使用CropAspectRatios.custom

**Comment by shenlanchenwei** [comment]
期待的样子应该是,没有那块留白

**Comment by shenlanchenwei** [comment]
仅仅只是旋转完就立即保存,就有问题了

**Comment by shenlanchenwei** [comment]
我这里是做一个类似微信截图的功能

**Comment by zmtzawqlp** [comment]
用固定 比例试试，然后请提供 demo +图片

**Comment by shenlanchenwei** [comment]
我发现截图本身没有问题,问题在于那个本地化切图的组件问题,旋转之后,图片的内容旋转了,宽高还是原来的,所以出现了这个问题

**Comment by shenlanchenwei** [comment]
![image](https://user-images.githubusercontent.com/6754634/94640504-8a076580-0311-11eb-886b-4bc7ff8803f3.png)

**Comment by shenlanchenwei** [comment]
Demo我稍后提供您

**Comment by shenlanchenwei** [comment]
[demo.zip](https://github.com/fluttercandies/extended_image/files/5303778/demo.zip)
你旋转90度,直接点预览就可以看到了

**Comment by zmtzawqlp** [comment]
并没有发现啥问题呢

**Comment by shenlanchenwei** [comment]
先旋转90度,再截半边点预览

**Comment by shenlanchenwei** [comment]
![image](https://user-images.githubusercontent.com/6754634/94661093-2f81ff80-0339-11eb-9ab9-790df4c6c61a.png)

**Comment by shenlanchenwei** [comment]
我截的是个长图,但是保存出来是个方的,其实感觉是长宽反了导致的

**Comment by CaiJingLong** [comment]
Just iOS?
Is the problem is happened on android?

**Comment by shenlanchenwei** [comment]
Only IOS will have this error

**Comment by shenlanchenwei** [comment]
![image](https://user-images.githubusercontent.com/6754634/94665045-437c3000-033e-11eb-95a9-cb9d5677dfe4.png)

**Comment by CaiJingLong** [comment]
Upgrade image_editor to 0.7.3. I fixed it.

**Comment by zmtzawqlp** [comment]
> Upgrade image_editor to 0.7.3. I fixed it.

nb
