### ISSUE TITLE
在图片滑动的时候，是否能提供图片预加载功能

### ISSUE THREAD

**Issue by hlj2722** [fluttercandies/extended_image#24]

**Comment by zmtzawqlp** [comment]
什么叫图片滑动。。

**Comment by hlj2722** [comment]
比如 example中的 PhotoViewDemo，在图片左右切换时，预先加载下一张图片

**Comment by zmtzawqlp** [comment]
你可以pageChanged时候，做如下操作,这样就相当于提前在内存中加载
```dart
               onPageChanged: (int index) {
                if (index > currentIndex) {
                  var nextOne = index + 1;
                  if (nextOne < widget.pics.length) {
                    var provider = ExtendedNetworkImageProvider(
                        widget.pics[nextOne].picUrl);
                    provider.resolve(createLocalImageConfiguration(context));
                  }
                }
                currentIndex = index;
                rebuildIndex.add(index);
              },
```

**Comment by hlj2722** [comment]
好的，谢谢

**Comment by zmtzawqlp** [comment]
https://api.flutter.dev/flutter/widgets/precacheImage.html  使用这个方法应该更好。原理是一样的

**Comment by user1121114685** [comment]
[https://github.com/fluttercandies/extended_image/blob/master/example/lib/pages/simple/photo_view_demo.dart#L51](url)

参考代码来了 

`    if (0 <= index && index < images.length) {
      final String url = images[index];

      precacheImage(ExtendedNetworkImageProvider(url, cache: true), context);

      _cachedIndexes.add(index);
    }`
