### ISSUE TITLE
Display image thumbnail from network image saved local.

### ISSUE THREAD

**Issue by Dangtrungphu** [fluttercandies/extended_image#241]
I want to display one thumbnail and 1 full image from the network image and save it locally. Don't know any solution?
Because uploading a lot of images in large sizes will decrease application performance. Thanks.

**Comment by zmtzawqlp** [comment]
you can display one thumbnail on loading state

**Comment by Dangtrungphu** [comment]
Thanks for your prompt. According to your complex presentation, there will be a frame containing many images in it and a page of images silde. My problem is, having girdview many large network images and on Listview will decrease the performance of the application. So I have an idea that, when load an image from the internet, it will be saved locally and at the same time will save a thumbnail. And ExtendedRawImage will have a variable like thumbnail: true / false, to display under Gridview or silde. Thanks

**Comment by zmtzawqlp** [comment]
use small one in list, and raw one in photo view.  you should provide compressed data or use cache width/height.
image will not provide compression function, this is not ExtendedImage's responsibility.

**Comment by Dangtrungphu** [comment]
Thank you I will try to do this
