### ISSUE TITLE
Swipe gestures are conflicting with zoom gestures

### ISSUE THREAD

**Issue by Zchandev** [fluttercandies/extended_image#245]
I use the latest version of Extended Image (1.2.0), flutter 1.22. Tried both on physical and simulator.

1. Sometimes swipe left/right gesture doesn't work. 
Open image from gallery. Try to swipe it right or left with a huge velocity. 

Expected results: image is being changed to the next one.
Actual results: image is being closed like I swiped up or down.

2. When image is zoomed in, it's too easy to accidentally close or swipe it.
Open any image and zoom it. Then, try to move your zoom by swiping it up/down or left/right.

Expected results: zoomed image should move with my gestures
Actual results: image is closed or changed to another one.

My code:
https://github.com/Zchandev/iChan/blob/master/lib/pages/gallery_item_page.dart#L81

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/152

**Comment by Zchandev** [comment]
> #152

Its not a duplicate. I have recorded videos to show you the problem.

#1 - https://yadi.sk/i/M9LU-jXjPujQEw

#2 - https://yadi.sk/i/oaI2XuU82Hlqjg

**Comment by zmtzawqlp** [comment]
please provide an simple runnable demo.

**Comment by Zchandev** [comment]
> please provide an simple runnable demo.

Check it out. I really like your plugin, if you could help me to fix these issues, I would rate it 10/10

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:extended_image/extended_image.dart';

class Media {
  Media({this.url});

  factory Media.fromUrl(String url) {
    return Media(url: url);
  }

  final String url;
}

List<Media> mediaList = [
  Media.fromUrl('https://disco.scrolller.com/media/21551f.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/23d95b.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/2392c2.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/249d85.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/20a361.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/21551f.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/23d95b.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/2392c2.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/249d85.jpg'),
  Media.fromUrl('https://disco.scrolller.com/media/20a361.jpg'),
];

final gestureConfig = GestureConfig(
  initialScale: 1.0,
  minScale: 1.0,
  animationMinScale: 0.9,
  maxScale: 10.0,
  animationMaxScale: 11,
  speed: 1.0,
  inertialSpeed: 100.0,
  inPageView: true,
  cacheGesture: false,
  initialAlignment: InitialAlignment.center,
);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GridView.builder(
      itemCount: mediaList.length,
      gridDelegate:
          SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 3, childAspectRatio: 1 / 1),
      itemBuilder: (_, index) {
        final media = mediaList[index];
        return GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTap: () {
            final pageRoute = FadeRoute(page: ImageItem(index: index));
            Navigator.of(context).push(pageRoute);
          },
          child: ExtendedImage.network(media.url),
        );
      },
    );
  }
}

class ImageItem extends StatefulWidget {
  ImageItem({this.index});

  final int index;

  @override
  _ImageItemState createState() => _ImageItemState();
}

class _ImageItemState extends State<ImageItem> {
  PageController pageController;

  @override
  void dispose() {
    pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    pageController = PageController(initialPage: widget.index);

    return ExtendedImageSlidePage(
      slideAxis: SlideAxis.vertical,
      slideType: SlideType.onlyImage,
      slidePageBackgroundHandler: (offset, pageSize) => defaultSlidePageBackgroundHandler(
          offset: offset,
          pageSize: pageSize,
          color: CupertinoColors.black.withOpacity(0.5),
          pageGestureAxis: SlideAxis.vertical),
      slideEndHandler: (offset, {details, state}) {
        final minDistance = 15.0;
        return offset.dy >= minDistance;
      },
      child: ExtendedImageGesturePageView.builder(
        controller: pageController,
        itemCount: mediaList.length,
        itemBuilder: (context, pos) {
          final nextMedia = mediaList[pos];
          return ExtendedImage.network(
            nextMedia.url,
            fit: BoxFit.contain,
            cache: true,
            mode: ExtendedImageMode.gesture,
            enableSlideOutPage: true,
            filterQuality: FilterQuality.high,
            initGestureConfigHandler: (state) => gestureConfig,
          );
        },
      ),
    );
  }
}

class FadeRoute<T> extends PageRouteBuilder<T> {
  FadeRoute({
    this.page,
  }) : super(
          transitionDuration: const Duration(milliseconds: 300),
          pageBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
          ) =>
              page,
          transitionsBuilder: (
            BuildContext context,
            Animation<double> animation,
            Animation<double> secondaryAnimation,
            Widget child,
          ) =>
              FadeTransition(
            opacity: animation,
            child: child,
          ),
        );

  final Widget page;

  @override
  bool get opaque => false;
}
```

**Comment by zmtzawqlp** [comment]
can't reproduce at my side. and by the way
this code is wrong, you should create it at initState method.
  Widget build(BuildContext context) {
    pageController = PageController(initialPage: widget.index);

**Comment by Zchandev** [comment]
> can't reproduce at my side. and by the way
> this code is wrong, you should create it at initState method.
> 
> ```dart
>   Widget build(BuildContext context) {
>     pageController = PageController(initialPage: widget.index);
> ```

To reproduce, try to do a fast swipe from the corner. You need to swipe it FAST, its only occured in that way. If you swipe slowly, it works.

Thanks for correction, I moved it to initState in my app

**Comment by v1z4** [comment]
I have the same problem. Image is being closed when swiping too fast

**Comment by zmtzawqlp** [comment]
Slide Out Page or Swipe Photo, It's hard to tell the difference

**Comment by Zchandev** [comment]
> Slide Out Page or Swipe Photo, It's hard to tell the difference with FAST operation. The only way is that change Slide Out condition by yourself.

Swipe photo is the main problem

**Comment by zmtzawqlp** [comment]
> > Slide Out Page or Swipe Photo, It's hard to tell the difference with FAST operation. The only way is that change Slide Out condition by yourself.
> 
> Swipe photo is the main problem

It's hard to tell the difference between Slide Out Page and Swipe Photo at that moment. you feel you are swipe page, but flutter tell you this is slide out gesture.

**Comment by Zchandev** [comment]
> > > Slide Out Page or Swipe Photo, It's hard to tell the difference with FAST operation. The only way is that change Slide Out condition by yourself.
> > 
> > 
> > Swipe photo is the main problem
> 
> It's hard to tell the difference between Slide Out Page and Swipe Photo at that moment. you feel you are swipe page, but flutter tell you this is slide out gesture.

Is there an existing issue on flutter's github? I can create it if you provide more details

**Comment by zmtzawqlp** [comment]
read more flutter gesture arena

**Comment by zmtzawqlp** [comment]
HorizontalDrag or onScaleUpdate are not base on your feel. if you swipe not on Horizontal (but you feel it is ), system may thought it's not a horizontal drag behavior,  it's vertical drag  and you swipe quickly , this is reach the condition to Slide Out Page

**Comment by Zchandev** [comment]
> HorizontalDrag or onScaleUpdate are not base on your feel. if you swipe not on Horizontal (but you feel it is ), system may thought it's not a horizontal drag behavior, it's vertical drag, one gesture will not be changed util it's end. And you swipe quickly , it reaches the condition to Slide Out Page.

Thanks. I have created the issue: https://github.com/flutter/flutter/issues/68960

**Comment by wxjrkm520** [comment]
同样的问题
