### ISSUE TITLE
调整调整EditorConfig 中的_aspectRatio后，会再次进行翻转操作

### ISSUE THREAD

**Issue by mrxiaoemo** [fluttercandies/extended_image#248]
如果我在initState中执行了一个延迟操作。如下
    Future.delayed(new Duration(milliseconds: 1000), () {
        editorKey.currentState.flip();
    });

当我调整EditorConfig 中的_aspectRatio时候，又会再次进行翻转操作，但是并没有调用flip函数。但是，多次调整并不会生效。
我想大概是因为 initEditorConfigHandler 中的 EditorConfig 被重置了，导致flip也恢复了原样的缘故。
代码如下：
 Container(
                      color: Colors.black,
                      child: ExtendedImage.file(
                        file,
                        fit: BoxFit.contain,
                        mode: ExtendedImageMode.editor,
                        enableLoadState: true,
                        extendedImageEditorKey: editorKey,
                        initEditorConfigHandler: (ExtendedImageState state) {
                          return EditorConfig(
                              maxScale: 8.0,
                              cropRectPadding: const EdgeInsets.all(20.0),
                              hitTestSize: 100.0,
                              cornerPainter: _cornerPainter,
                              initCropRectType: InitCropRectType.imageRect,
                              cropAspectRatio: _aspectRatio);
                        },
                      )),

**Comment by zmtzawqlp** [comment]
请提供具体的测试步骤和代码
