### ISSUE TITLE
BoxConstraints has a negative minimum height.

### ISSUE THREAD

**Issue by UlanNurmatov** [fluttercandies/extended_image#249]
When I'm rotating the image in Cropper, this error appears sometimes. 

> ════════ Exception caught by widgets library ═══════════════════════════════════
> BoxConstraints has a negative minimum height.
> The relevant error-causing widget was
>     ExtendedImage 

![IMG_8667](https://user-images.githubusercontent.com/41744054/97463132-a2e35500-1969-11eb-994d-abecd85cf9b4.PNG)

**Comment by zmtzawqlp** [comment]
please provide a runnable demo

**Comment by Heedster** [comment]
The error occurs when you drag the crop handlers very close to each other. 

The culprit is either the top/bottom or left/right (depending on the direction you drag the crop handlers) having their width or height < 0

Example, in extended_image_crop_layer, the left handler code is
```
 //left
          Positioned(
            top: cropRect.top + gWidth,
            left: cropRect.left - gWidth,
            child: Container(
              height: cropRect.height - gWidth * 2,
              width: gWidth * 2,
              child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onHorizontalDragUpdate: (DragUpdateDetails details) {
                  moveUpdate(_moveType.left, details.delta);
                },
                onHorizontalDragEnd: (_) {
                  _moveEnd(_moveType.left);
                },
              ),
            ),
          ),
 ```
 Here you can see `cropRect.height - gWidth * 2` could become small when the height is less than 40 (default hitsize * 2 or whatever hitTestSize user passes)
 
 Does this sound right? 
 
 Should I submit a PR with `max(cropRect.height - gWidth * 2, 0)` for all 4 sides?

**Comment by zmtzawqlp** [comment]
i can't reproduce it at my side, maybe you can provide an demo, thanks

**Comment by Heedster** [comment]
https://user-images.githubusercontent.com/3810492/103287362-5a4b2500-4a08-11eb-890b-ab5e0a5fab4d.mp4

I was able to reproduce it by these lines in a hello world app.
I also noted that it doesnt crash on the production build, it just shows the error on debug build, and works normally on prod build, so thats good in a way. 

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // The title text which will be shown on the action bar
        title: Text(title),
      ),
      body: Center(
        child: ExtendedImage.asset(
          "images/cat.jpg",
          mode: ExtendedImageMode.editor,
          fit: BoxFit.contain,
          initEditorConfigHandler: (state) {
            return EditorConfig(
              maxScale: 5.0,
              cropRectPadding: EdgeInsets.all(0.0),
              cornerPainter: ExtendedImageCropLayerPainterNinetyDegreesCorner(
                  color: Theme.of(context).accentColor),
              hitTestSize: 40.0,
            );
          },
        ),
      ),
    );
  }
```

[Stateless-Hello-World (1).zip](https://github.com/fluttercandies/extended_image/files/5750855/Stateless-Hello-World.1.zip)
