### ISSUE TITLE
No named parameter with the name 'nullOk'

### ISSUE THREAD

**Issue by ishangavidusha** [fluttercandies/extended_image#252]
**Build process failed with Exception**
**_extended_image: ^1.3.0_**
**_Flutter Channel dev, 1.24.0-6.0.pre_**

`flutter run -d windows`
> Running "flutter pub get" in image_to_doc_win...                   900ms
Launching lib\main.dart on Windows in debug mode...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/extended_image-1.3.0/lib/src/extended_image.dart(785,44): error GBF4691A2: No named parameter with the name 'nullOk'. [C:\Users\ishan\Desktop\image_to_doc_win\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...                                         
Exception: Build process failed.

`flutter doctor -v`

> [√] Flutter (Channel dev, 1.24.0-6.0.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-6.0.pre at C:\src\flutter
    • Framework revision 13896b3bd1 (2 days ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2) 
    • Android SDK at C:\Users\ishan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30523.141
    • Windows 10 SDK version 10.0.18362.0
[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\ishan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0
[√] Connected device (4 available)
    • SM A805N (mobile) • emulator-5554 • android-x86    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server    • web-javascript • Flutter Tools
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 86.0.622.56

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/251
