### ISSUE TITLE
extended_image测试列子中的waterfall_flow_demo.dart在真实苹果6s手机上多次滑动会出现内存爆涨了，直接闪退了

### ISSUE THREAD

**Issue by ghost** [fluttercandies/extended_image#253]

**Comment by zmtzawqlp** [comment]
enable clearMemoryCacheWhenDispose

**Comment by yaoqi-github** [comment]
我自己按照官方的demo写的demo是有开启clearMemoryCacheWhenDispose的，也出现了内存爆涨，直接闪退了

**Comment by yaoqi-github** [comment]
我看官方的demo也是有开启clearMemoryCacheWhenDispose的

**Comment by zmtzawqlp** [comment]
1.图片太大
2.提供能重现问题的demo

**Comment by yaoqi-github** [comment]
有群吗，我可以加下提供下demo

**Comment by zmtzawqlp** [comment]
看readme

**Comment by zmtzawqlp** [comment]
demo 请提供在issue里面。qq只是方便交流。

**Comment by yaoqi-github** [comment]
import 'package:example/common/data/tu_chong_repository.dart';
import 'package:example/common/data/tu_chong_source.dart';
import 'package:example/common/widget/item_builder.dart';
import 'package:flutter/material.dart';
import 'package:loading_more_list/loading_more_list.dart';
import 'package:ff_annotation_route/ff_annotation_route.dart';
import 'package:extended_image_library/extended_image_library.dart';

@FFRoute(
  name: 'fluttercandies://WaterfallFlowDemo',
  routeName: 'WaterfallFlow',
  description: 'WaterfallFlow with ExtendedImage.',
  exts: <String, dynamic>{
    'group': 'Complex',
    'order': 0,
  },
)
class WaterfallFlowDemo extends StatefulWidget {
  @override
  _WaterfallFlowDemoState createState() => _WaterfallFlowDemoState();
}

class _WaterfallFlowDemoState extends State<WaterfallFlowDemo> {
  TuChongRepository listSourceRepository;

  @override
  void initState() {
    listSourceRepository = TuChongRepository();
    super.initState();
  }

  @override
  void dispose() {
    listSourceRepository?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        children: <Widget>[
          AppBar(
            title: const Text('WaterfallFlowDemo22'),
          ),
          Expanded(
            child: LoadingMoreList<TuChongItem>(
              ListConfig<TuChongItem>(
                /// https://github.com/fluttercandies/extended_image/blob/master/README-ZH.md
                /// https://pub.flutter-io.cn/packages/loading_more_list
                extendedListDelegate: ExtendedListDelegate(
                  collectGarbage: (List<int> garbages) {
                    ///collectGarbage
                    garbages.forEach((index) {
                      final provider = ExtendedNetworkImageProvider(
                        listSourceRepository[index].imageUrl,
                      );
                      provider.evict();
                    });
                    //print("collect garbage : $garbages");
                  },
                  viewportBuilder: (int firstIndex, int lastIndex) {
                    print("viewport : [$firstIndex,$lastIndex]");
                  },
                ),
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  mainAxisSpacing: 5,
                  crossAxisCount: 2,
                  crossAxisSpacing: 5,
                ),
                // extendedListDelegate:
                //     const SliverWaterfallFlowDelegateWithMaxCrossAxisExtent(
                //   maxCrossAxisExtent: 300,
                //   crossAxisSpacing: 5,
                //   mainAxisSpacing: 5,
                // ),
                itemBuilder: buildWaterfallFlowItem,
                sourceList: listSourceRepository,
                padding: const EdgeInsets.all(5.0),
                lastChildLayoutType: LastChildLayoutType.foot,
              ),
            ),
          )
        ],
      ),
    );
  }
}

**Comment by yaoqi-github** [comment]
import 'package:example/common/data/tu_chong_repository.dart';
import 'package:example/common/data/tu_chong_source.dart';
import 'package:example/common/widget/item_builder.dart';
import 'package:flutter/material.dart';
import 'package:loading_more_list/loading_more_list.dart';
import 'package:ff_annotation_route/ff_annotation_route.dart';
import 'package:extended_image_library/extended_image_library.dart';

@FFRoute(
  name: 'fluttercandies://WaterfallFlowDemo',
  routeName: 'WaterfallFlow',
  description: 'WaterfallFlow with ExtendedImage.',
  exts: <String, dynamic>{
    'group': 'Complex',
    'order': 0,
  },
)
class WaterfallFlowDemo extends StatefulWidget {
  @override
  _WaterfallFlowDemoState createState() => _WaterfallFlowDemoState();
}

class _WaterfallFlowDemoState extends State<WaterfallFlowDemo> {
  TuChongRepository listSourceRepository;

  @override
  void initState() {
    listSourceRepository = TuChongRepository();
    super.initState();
  }

  @override
  void dispose() {
    listSourceRepository?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Column(
        children: <Widget>[
          AppBar(
            title: const Text('WaterfallFlowDemo22'),
          ),
          Expanded(
            child: LoadingMoreList<TuChongItem>(
              ListConfig<TuChongItem>(
                extendedListDelegate: ExtendedListDelegate(
                  collectGarbage: (List<int> garbages) {
                    ///collectGarbage
                    garbages.forEach((index) {
                      final provider = ExtendedNetworkImageProvider(
                        listSourceRepository[index].imageUrl,
                      );
                      provider.evict();
                    });
                    //print("collect garbage : $garbages");
                  },
                  viewportBuilder: (int firstIndex, int lastIndex) {
                    print("viewport : [$firstIndex,$lastIndex]");
                  },
                ),
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  mainAxisSpacing: 5,
                  crossAxisCount: 2,
                  crossAxisSpacing: 5,
                ),
                itemBuilder: buildWaterfallFlowItem,
                sourceList: listSourceRepository,
                padding: const EdgeInsets.all(5.0),
                lastChildLayoutType: LastChildLayoutType.foot,
              ),
            ),
          )
        ],
      ),
    );
  }
}

只在官方demo里面加入了垃圾回收机制，其它都没动

**Comment by zmtzawqlp** [comment]
flutter version ，全部组件的version，这边跑过demo，没有你说的问题

**Comment by yaoqi-github** [comment]
你这边把我这个collectGarbage加上去试试，就是我上面发的这段代码替换试试呢

**Comment by BadReese** [comment]
怎么没给个结果就关了

**Comment by zmtzawqlp** [comment]
flutter version ，全部组件的version，这边跑过demo，没有你说的问题

**Comment by zmtzawqlp** [comment]
请提供能够重现问题的demo

**Comment by cr1992** [comment]
根本原因是因为加载的都是原图，内存不够容易闪退，可以通过ResizeImage缩放尺寸。

**Comment by zmtzawqlp** [comment]
请尝试最新的demo 以及 关于内存优化的操作
