### ISSUE TITLE
Image repeatedly flashes with ZoomPageTransition in 1.17

### ISSUE THREAD

**Issue by AlexV525** [fluttercandies/extended_image#255]
## Step to reproduce

1. Using Flutter 1.17.x.
2. Use `ZoomPageTransitionBuilder` as default transition theme for route transition.
3. Page A: `ExtendedImage(...)`, then push to Page B.
4. Image flash.

**Comment by zmtzawqlp** [comment]
close , we are on stable 2.0.0 now
