### ISSUE TITLE
Flutter master SDK build error

### ISSUE THREAD

**Issue by zmtzawqlp** [fluttercandies/extended_image#258]
I will update the dev version to support flutter master branch if  there were any emergency.

**Comment by zmtzawqlp** [comment]
1.3.1-dev for 1.24

**Comment by volgin** [comment]
Version 1.3.0 does not work without this fix in beta channel.

**Comment by zmtzawqlp** [comment]
> Version 1.3.0 does not work without this fix in beta channel.

please use 1.3.1-dev

**Comment by BadReese** [comment]
What about master-v1.25.0 now?

**Comment by zmtzawqlp** [comment]
> What about master-v1.25.0 now?

please use 1.3.1-dev

**Comment by JAICHANGPARK** [comment]
I'm using Flutter 1.24.0-10.2.pre version 
I tried to change  `extended_image: ^1.3.1-dev` 
But still not works for me 

```
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image-1.4.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
```

**Comment by zmtzawqlp** [comment]
make sure you are in 1.3.1-dev

from your log, you are on 1.4.0
AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image-1.4.0/lib/src/extended_image.dart

**Comment by JAICHANGPARK** [comment]
> make sure you are in 1.3.1-dev
> 
> from your log, you are on 1.4.0
> AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/extended_image-1.4.0/lib/src/extended_image.dart

I wonder 1.4.0 version is applied even if dependency_overrides with 1.3.1-dev.

```
dependency_overrides:
  extended_image: ^1.3.1-dev
```

and I tried `flutter clean`

**Comment by zmtzawqlp** [comment]
try with out ^
dependency_overrides:
  extended_image: 1.3.1-dev

**Comment by CelticMajora** [comment]
I might be following this thread wrong, but I am experiencing this on the stable `1.22.5` build. Here is the error I'm seeing:
```
../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-1.3.1-dev/lib/src/extended_image.dart:785:32: Error: Method not found: 'MediaQuery.maybeOf'.
    _invertColors = MediaQuery.maybeOf(context)?.invertColors ??
                               ^^^^^^^
```
I'm currently using the same `dependency_overrides` method JAICHANGPARK is using in order to force 1.3.1-dev. Has this been reported as an issue in non-beta flutter versions yet?

**Comment by zmtzawqlp** [comment]
> I might be following this thread wrong, but I am experiencing this on the stable `1.22.5` flutter sdk. Here is the error I'm seeing:
> 
> ```
> ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-1.3.1-dev/lib/src/extended_image.dart:785:32: Error: Method not found: 'MediaQuery.maybeOf'.
>     _invertColors = MediaQuery.maybeOf(context)?.invertColors ??
>                                ^^^^^^^
> ```
> 
> I'm currently using the same `dependency_overrides` method JAICHANGPARK is using in order to force 1.3.1-dev. Has this been reported as an issue in non-beta flutter versions yet? Should I not be using 1.3.1-dev for the stable flutter sdk?

you should use 1.5.0

**Comment by volgin** [comment]
Same error with 1.5.0. Downgrading to 1.3.1-dev works.

**Comment by zmtzawqlp** [comment]
1.5.0. for.   flutter stable 1.22.5

1.5.0-dev for flutter master

**Comment by houdayec** [comment]
> 1.5.0. for. flutter stable 1.22.5
> 
> 1.5.0-dev for flutter master

1.5.0-dev does not work on flutter master, getting same error as @volgin

**Comment by muarachmann** [comment]
Same here keep getting the same error

**Comment by zmtzawqlp** [comment]
1.5.0 

https://github.com/fluttercandies/extended_image/blob/bfa1a782c837b5d0376e2a7f0feffcc5afc206ff/lib/src/extended_image.dart#L785

1.5.0-dev

https://github.com/fluttercandies/extended_image/blob/7cf821eac3514521ffd34621caa4175f1ee679c0/lib/src/extended_image.dart#L785


make sure you are in right branch

**Comment by panchalAlpit** [comment]
> dependency_overrides:
> extended_image: 1.5.0-dev

It's working for me in the beta channel.
Thanks

**Comment by zmtzawqlp** [comment]
sorry, i have no enough time to support update package on Flutter Master/Dev/Beta branch. i will force on stable branch from now on.
