### ISSUE TITLE
flutter for web 设置headers无效

### ISSUE THREAD

**Issue by cq-z** [fluttercandies/extended_image#259]
flutter for web 设置headers无效

**Comment by zmtzawqlp** [comment]
官方未支持

**Comment by cq-z** [comment]
尝试这个方法：https://blog.csdn.net/waterseason/article/details/104421309
会报这个错，要等官方解决Unsupported operation: Platform._version
https://github.com/flutter/flutter/issues/39998

**Comment by cq-z** [comment]
尝试这个方法：https://blog.csdn.net/waterseason/article/details/104421309
会报这个错，要等官方解决Unsupported operation: Platform._version

**Comment by zmtzawqlp** [comment]
。。。web走的是js的方法。。你用io的方法肯定报错啊

**Comment by cq-z** [comment]
好吧！我以为官方会兼容。

**Comment by cq-z** [comment]
那用package:http/http.dart这个包可以解决这个问题吗？

**Comment by zmtzawqlp** [comment]
官方解码 web走的另外一套，跟什么包没关系啊

**Comment by cq-z** [comment]
了解谢谢了！
