### ISSUE TITLE
Unable to run after upgrading to latest flutter version 1.7.8+hotfix.3

### ISSUE THREAD

**Issue by RajaShanmugamJM** [fluttercandies/extended_image#26]
![Annotation 2019-07-10 153922](https://user-images.githubusercontent.com/27273337/60961053-ed7e2f80-a328-11e9-965d-1eddda4b1ffb.png)

**Comment by zmtzawqlp** [comment]
use following code to link to dev at the moment，

  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: dev

i will push codes for stable 1.7.8 as soon as possible，

close as the same https://github.com/fluttercandies/extended_image/issues/16

**Comment by RajaShanmugamJM** [comment]
Noted with thanks.

Kind Regards,
Raja Shanmugam JM
