### ISSUE TITLE
Image gets cropped when fitted in several ways.

### ISSUE THREAD

**Issue by Jamminroot** [fluttercandies/extended_image#260]
Hey!
Thanks for a great asset ♥

Possibly just a question here.

I've been trying to use it the way I want, but couldn't wrap my head around on how to display image with
```dart
 fit: BoxFit.cover,
```
but so that I could scroll the image later on.

lets say I got image 10 000 x 500, I choose `fit: BoxFit.cover,`, with my screen's aspect ratio 16:9 I get square of 
~889x500 shown, but I can't scroll it vertically to show remaining 9k+ lines; Yet I want to keep page scrolling direction horizontal.

That might be described somewhere - but I didn't really find it in docs; Quick run through issues did not give me the answer either.

Sorry in advance if it's a duplicate.

That's the draft implementation if that helps:

```dart
return Container(
      child: ExtendedImageGesturePageView.builder(
        itemBuilder: (BuildContext context, int index) {
          var item = _pages[index];
          Widget image = ExtendedImage.network(
            item,
            fit: BoxFit.cover,
            mode: ExtendedImageMode.gesture,
            initGestureConfigHandler: (state) {
              return GestureConfig(
                  inPageView: true,
                  initialScale: 1.0,
                  speed: 1,
                  cacheGesture: false);
            },
          );
          image = Container(
            child: image,
            padding: EdgeInsets.all(5.0),
          );
          if (index == currentPage) {
            return Hero(
              tag: item + index.toString(),
              child: image,
            );
          } else {
            return image;
          }
        },
        itemCount: _pages.length,
        onPageChanged: (int index) {
          currentPage = index;
        },
        controller: PageController(
          initialPage: currentPage,
        ),
        scrollDirection: Axis.horizontal,
      ),
    );
```

**Comment by zmtzawqlp** [comment]
It seems that you want to show image at center when initial , and can scroll it up and down later. you can do it with following steps:

1. set initialAlignment,
        GestureConfig(
                  initialAlignment: InitialAlignment.center,
          )
2. set initialScale by 

https://github.com/fluttercandies/extended_image/blob/d81f1dc1a86080d054dba0a7f8b18e18ea9a31d8/example/lib/common/utils/util.dart#L11

This function is from 0.6.6 version.

tell me if any other problem

**Comment by Jamminroot** [comment]
Thanks for quick response.

Here's what I used to test, and gif of what I actually get.

https://ibb.co/0rxcVtK
(Sorry for a redirect,  GH won't allow large attachments).

I can zoom it out a bit, but I can't move it to the bottom of the image past cropped portion of image - what I get when image initially fitted to the container is everything I would be able to view.

On the other hand, I can use `fit: BoxFit.contain`, but I would need to calculate scale manually so that it 'matches' to what `BoxFit.cover` evaluates to.

![Test image](https://i.ibb.co/qWphkCP/Untitled-1.jpg)

**Comment by Jamminroot** [comment]
Oh, misunderstood you, my apologies.
Thank for claring this up for me!

**Comment by armandojimenez** [comment]
Sorry, Im trying to implement this, how do you get the File size to use the utils method mentioned here?

**Comment by feduke-nukem** [comment]
> when image is loaded, you can debug this demo

Is that real with `editor` mode?
