### ISSUE TITLE
[Feature request] Custom shape of cropping area

### ISSUE THREAD

**Issue by mordivgor** [fluttercandies/extended_image#262]
Hello,

One thing which I missed is having custom shape of cropping. Right now (if I understand well) we can change the shape of the whole image in editor mode (from rectangle to circle), but cropping area stays in rectangle shape.

It will be nice for social networks where people has circle photos.

Great plugin, by the way :)

**Comment by zmtzawqlp** [comment]
the ui, you can define by your self by EditorCropLayerPainter, but the data you should handle by yourself

https://github.com/fluttercandies/extended_image/pull/265
