### ISSUE TITLE
Removal of nullOk from MediaQuery.of

### ISSUE THREAD

**Issue by BrayFlex** [fluttercandies/extended_image#263]
Flutter is removing nullOk parameter from MediaQuery.of https://github.com/flutter/flutter/pull/68736 
Currently it is causing an issue for me on the newest beta branch released today.

It is on line 785 of extended_image.dart

```
  void _updateInvertColors() {
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
        SemanticsBinding.instance.accessibilityFeatures.invertColors;
  }
```

propose change to:
```
  void _updateInvertColors() {
    _invertColors = MediaQuery.maybeOf(context)?.invertColors ??
        SemanticsBinding.instance.accessibilityFeatures.invertColors;
  }
```

I've created a PR here: https://github.com/fluttercandies/extended_image/pull/264

**Comment by BrayFlex** [comment]
https://github.com/fluttercandies/extended_image/pull/264

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/258
