### ISSUE TITLE
How to refresh image manually

### ISSUE THREAD

**Issue by fernando-s97** [fluttercandies/extended_image#266]
**Context**

I have an app that fetches a list of URLs of images and displays them on startup. Eventually, the user can press a button to "refresh all" and all the images should be refreshed.

For now, I'm using a single URL to generate random images for me: https://source.unsplash.com/random/356x200

If I open this URL on the browser, it will display an image. If I hit F5, it will display the same image and if I hit CRTL+F5, it will display a new image.

When this code is executed (for each URL in the list)

```dart
ExtendedImage.network(
	url,
	cache: false,
	shape: BoxShape.rectangle,
	borderRadius: BorderRadius.circular(kDefaultSquareRoundedRadius),
	loadStateChanged: (state) =>
	    state.extendedImageLoadState == LoadState.loading
	        ? const Center(child: CircularProgressIndicator())
	        : null,
)
```
the app displays the same image as if I were hitting F5 on chrome.

I've tried setting `cache: false`, but it didn't have any effect. I've also tried `clearDiskCachedImage()` before reloading the images (emitting a new state with BLoC that will replace the list of URLs), which resulted in `true`, but after the loading spinner, the same images kept showing.

**Question**

How can I achieve the same result as hitting CTRL+F5 on chrome, which will lead to different images for each URL?

Just reinforcing that the URL is the same. Example: 

```dart
[
	'https://source.unsplash.com/random/356x200',
	'https://source.unsplash.com/random/356x200',
	'https://source.unsplash.com/random/356x200'
]
```

**Environment**

Lib v1.3.0

$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.22.4 at /opt/libs/flutter
    • Framework revision 1aafb3a8b9 (8 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/fernando/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ASUS X00QD (mobile) • 192.168.1.39:5555 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by zmtzawqlp** [comment]
ExtendedImage.network is do the same thing on web as official. 

https://github.com/flutter/flutter/blob/de56c6ad725d58e98772e37125c8762ec2f643c3/packages/flutter/lib/src/painting/_network_image_web.dart#L91

i don't think it's support. something like  HTTP caching
