### ISSUE TITLE
How to handle orientation change in image_editor? 

### ISSUE THREAD

**Issue by UlanNurmatov** [fluttercandies/extended_image#267]
When changing orientation from portrait to landscape and vice versa, the editor doesn't keep the changes made and image changes its scale (getting bigger or smaller).
What is the best way to handle the orientation change or should it be used only in portrait mode?

![Screenshot_1606063251](https://user-images.githubusercontent.com/41744054/99909624-e08e9000-2d13-11eb-89d6-032a2a75c75a.png)
![Screenshot_1606063263](https://user-images.githubusercontent.com/41744054/99909631-e8e6cb00-2d13-11eb-8116-b479673cf2e7.png)

**Comment by zmtzawqlp** [comment]
not support now
