### ISSUE TITLE
Photo View slide pictures with buttons

### ISSUE THREAD

**Issue by FRANIAZA** [fluttercandies/extended_image#269]
Hi,
I implemented the Photo View. If the app is built for Web I would like to also be able to scroll through the images inside ExtendedImageGesturePageView.builder using two buttons (Next image and previous image) and not only by scrolling.

I saw that ExtendedImageGesturePageView.builder has a controller field of type PageController. 
The PageController class has a nextPage() method and a previousPage() method that scroll to the next/previous image I'm guessing.

Can I use these methods in the buttons' onClick callback to scroll through the photos? If yes, how can I access the  ExtendedImageGesturePageView.builder's controller field so that I can call the nextPage/previousPage methods?

Here is a prototype of what I'm trying to accomplish:

````
Scaffold(
      body: Stack(
        children: [
          Row(
            mainAxisSize: MainAxisSize.max,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              IconButton(icon: Icon(FontAwesomeIcons.chevronLeft), onPressed:() => pageController.previousPage),
              IconButton(icon: Icon(FontAwesomeIcons.chevronRight), onPressed:() => pageController.nextPage),
            ]
          ),
          ExtendedImageGesturePageView.builder(
            controller: PageController(
              initialPage: _currentIndex,
            ),
          )
       ]
    );
````

Thank you for your help

**Comment by zmtzawqlp** [comment]
ExtendedImageGesturePageView.builder(
            controller: pageController,
          )

**Comment by FRANIAZA** [comment]
That doesn't work. 
I'm guessing because the ExtendedImageGesturePageView.builder copies the pageController into it's own local instance and, therefore modifying the pageController after assigning it to the controller parameter has no effect on the local instance that the ExtendedImageGesturePageView.builder created.

**Comment by FRANIAZA** [comment]
Jk, it works, you just need to pass the parameters to the pageController's nextPage/previousPage methods like this pageController.nextPage(duration, curve)
