### ISSUE TITLE
Flutter 1.7 error

### ISSUE THREAD

**Issue by ManojMM026** [fluttercandies/extended_image#27]
Compiler message:
file:///Users/webwerks/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.1/lib/src/extended_image.dart:733:59: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/webwerks/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/webwerks/Desktop/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    if (_isListeningToStream) _imageStream.removeListener(_handleImageChanged);

**Comment by zmtzawqlp** [comment]
please check https://github.com/fluttercandies/extended_image/issues/6
