### ISSUE TITLE
 No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by cardinals** [fluttercandies/extended_image#270]
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.9.0/lib/src/extended_image.dart:743:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/258
