### ISSUE TITLE
Question: for how much time does the library keep the cache?

### ISSUE THREAD

**Issue by robmr88** [fluttercandies/extended_image#272]
Hi, thank you for this library. I was wondering, for how much time does this library hold the cached image?
For example if I open the app now and cache some images and then open the app tomorrow, will the library download the images again tomorrow or will it load the cached image?
Thank you

**Comment by zmtzawqlp** [comment]
you can call when you app launch ,

Future<bool> clearDiskCachedImages({Duration duration})

**Comment by robmr88** [comment]
Actually I would like the cache to keep the images for as long as possible.
Is there some way to set it?

**Comment by zmtzawqlp** [comment]
not support now, but you can clear them by clearDiskCachedImages method

**Comment by robmr88** [comment]
I think I didn't explain myself very well 😅 
I don't want to clear the cache, I want to keep the cache for as long as possible.
So I was just asking for how long does the cache keep the images.
Thanks

**Comment by zmtzawqlp** [comment]
yes forever

**Comment by linhmanh92** [comment]
@robmr88 Has the problem been solved yet?

**Comment by hectorAguero** [comment]
Would be helpful to have this information as a comment in the `cacheMaxAge` or `cache` property

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/blob/ed0d441e84fb49cac86b8847d709763e5e2fb773/lib/src/network/extended_network_image_provider.dart#L64

https://github.com/fluttercandies/extended_image_library/blob/ed0d441e84fb49cac86b8847d709763e5e2fb773/lib/src/network/extended_network_image_provider.dart#L42
