### ISSUE TITLE
ExtendedImage 构造中将handleLoadingProgress的默认值置为false的原因是?

### ISSUE THREAD

**Issue by cherrybiu** [fluttercandies/extended_image#274]
我想在预览的时候使用`ExtendedImage`组件,因为我们需要自己管理内存,所以传入imageProvider进去,但我看您的构造中这里的`handleLoadingProgress`是特意没有放在属性里的,给它了默认值false. 因为在显示的过程中,可能会有需要看到`loading`加载的一个过程的需求, 我看您的`ExtendedImage.network`这个其实最终也是处理成imageProvider的形式,但是这个是可以传入`handleLoadingProgress`的值的,我想问下在`ExtendedImage`里把这个参数去掉,这样处理的原因是什么呢...

```
   : assert(image != null),
        assert(constraints == null || constraints.debugAssertIsValid()),
        constraints = (width != null || height != null)
            ? constraints?.tighten(width: width, height: height) ??
                BoxConstraints.tightFor(width: width, height: height)
            : constraints,
        handleLoadingProgress = false,
        super(key: key);

```

**Comment by zmtzawqlp** [comment]
handleLoadingProgress 只针对network，这个是图片下载进度

**Comment by cherrybiu** [comment]
因为我们现在的需求是我们需要用我们自己的imageProvider去做网络图片请求,这个时候也是需要拿到加载进度的,刚刚我把那个源码修改了下,把handleLoadingProgress属性暴露给了ExtendedImage, 这个值确实是可以实现我们的需求的, 也可以看到实时下载进度

**Comment by zmtzawqlp** [comment]
嗯，主要provider里面也要写相关代码，我下个版本修改下好了

**Comment by cherrybiu** [comment]
嗯嗯, 这个只要他按照imageProvier的协议来写就是没问题的

**Comment by zmtzawqlp** [comment]
done
