### ISSUE TITLE
build 方法里有一串代码看起来是始终不会执行到的

### ISSUE THREAD

**Issue by cherrybiu** [fluttercandies/extended_image#275]
在ExtendedImage的build方法里, 因为returnLoadStateChangedWidget这个值是赋值为false的,这串&&条件代码看着始终是不会走进去的, 这里有点不太理解,看起来去掉它是不是也没影响,
```
Widget current;
    returnLoadStateChangedWidget = false;
    if (widget.loadStateChanged != null) {
      current = widget.loadStateChanged(this);
      if (current != null && returnLoadStateChangedWidget) {
        return current;
      }
    }
```

**Comment by zmtzawqlp** [comment]
returnLoadStateChangedWidget 这个吗？ 这个是给一种场景做的 ，开始设置了宽高500*500， 就是loading的时候 500*500， 但是图片加载成功的时候想变成 400*300， returnLoadStateChangedWidget为true 就会直接返回，不会再走下面去设置 限制了。当然其实包裹一个 UnconstrainedBox 也是可以的

**Comment by cherrybiu** [comment]
我的理解是您是指这个值可以在回调的时候由调用者来修改吗, 这样看的话这一段确实比较隐晦,  感觉一般都可能不太会想到0.0

**Comment by zmtzawqlp** [comment]
对的。demo里面有写呢。readme里面也有写

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/102193602-44f9d500-3ef7-11eb-9654-f449fe1c2279.png)

**Comment by cherrybiu** [comment]
嗯嗯, 这个还是建议在条件那里可以注释一下喔,因为可能在浏览源码的时候,直接看到注解可能更好理解一点
