### ISSUE TITLE
Crop rectangle is rotated when the image is rotated. It should not rotate, only the image should be rotated.

### ISSUE THREAD

**Issue by anamauad** [fluttercandies/extended_image#277]
Aspect is rotated when the image is rotated. It should not rotate, only the image should be rotated.

Steps to reproduce the problem:
1. Select the image
2. Set the aspect ratio to CropAspectRatios.ratio4_3
3. Rotate to right

The image is rotated 90 degrees, but the crop rectangle is also rotated. It turns out to be CropAspectRatios.ratio3_4.

I think that it should not rotate the crop rectangle.

**Comment by zmtzawqlp** [comment]
as design

**Comment by eriko13** [comment]
Why not add a parameter to switch between these two behaviors?

**Comment by eriko13** [comment]
I have the same problem.

**Comment by akadatsky** [comment]
Any solution for this issue?

**Comment by ramtinq** [comment]
any update on this? after 2 years still the problem is left without any solution by the developers. I really like this package and prefer use the official one instead of my own modified version, but these problems need to be solved. Having a parameter for switching this behavior would be great.

**Comment by zmtzawqlp** [comment]
1. This behavior as design. It's the same as many photo app on different smartphone.
2. If crop rectangle is not follow with image, you can't make sure it's right to new image.

**Comment by ramtinq** [comment]
@zmtzawqlp I completely understand that, but how about the case when we want to provide some standard aspect ratios like most editing apps? In that case, rotating the crop rectangle would be opposed to its goal.

I have tried many approaches (without editing the package's source code) to create a workaround with no luck and weird stuff happening.

Strangely, this rotate function works, as provided in the package's example:
```
  void rotate(bool isToRight) async {
    editorKey.currentState?.rotate(right: isToRight);
  }
```
but this one, results in the cropRect to change, but the image will not rotate at all:

```
  void rotate(bool isToRight) async {
    editorKey.currentState?.rotate(right: isToRight);

    setState(() {
      if (_cropAspectRatio != null) {
        _cropAspectRatio = 1.0 / _cropAspectRatio!;
      }
    });
  }
```

I tried many many approaches, calling `setState` with delays, in different orders, ... but no luck. And force-rebuilding the entire `ExtendedImage` widget works but it will be flashy.

Isn't there any workaround to at least both rotate and change `cropAspectRatio`? why this strange behavior happens that the image does not rotate at all when changing `cropAspectRatio`?!

**Comment by Eriickson** [comment]
Has anyone found the solution to this?

**Comment by maRci002** [comment]
@zmtzawqlp is the web demo using `v9.0.0`?

https://fluttercandies.github.io/extended_image/#fluttercandies://imageeditor

When I set crop to `3x4` and rotate the crop changes to `4x3`

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp is the web demo using `v9.0.0`?
> 
> https://fluttercandies.github.io/extended_image/#fluttercandies://imageeditor
> 
> When I set crop to `3x4` and rotate the crop changes to `4x3`

web demo not update，please get latest version, and build by your self
