### ISSUE TITLE
从预览图片页面返回时,hero的效果在最后一瞬间变化

### ISSUE THREAD

**Issue by cherrybiu** [fluttercandies/extended_image#278]
我在您的demo里还有我自己的预览组件里发现, 对图片预览返回的时候, 图片会在最后一瞬间发生形状的变化以展示应有的大小, 但是这样就显得变化有点突兀, 然后我发现您有在一次修复中修改了streching的问题,
```javascript
 flightShuttleBuilder: (BuildContext flightContext,
        Animation<double> animation,
        HeroFlightDirection flightDirection,
        BuildContext fromHeroContext,
        BuildContext toHeroContext) {
      final Hero hero =
          (flightDirection == HeroFlightDirection.pop
              ? fromHeroContext.widget
              : toHeroContext.widget) as Hero;
      return hero;
    },

```
也就是这段代码导致了这种现象, 我查了一下资料,好像是说这个flightShttleBuilder属性只会在start以及end那里变化,而hero原本的中间过渡动画会没有,但是我试了很多方法,始终不能一起解决streching和过渡不自然的两个问题,作者大佬有思路吗0.0

**Comment by zmtzawqlp** [comment]
fit 前后不一样。就会有这种情况。没有啥好办法。除非自己写hero

**Comment by xuning0** [comment]
同样困扰我几天了，希望作者不吝赐教

**Comment by zmtzawqlp** [comment]
> 同样困扰我几天了，希望作者不吝赐教

fit 前后不一样。就会有这种情况。没有啥好办法。除非自己写hero
