### ISSUE TITLE
对于 network 加载网络图片问题

### ISSUE THREAD

**Issue by OHeroJ** [fluttercandies/extended_image#281]
1. 第一次加载 url,  会下载图片，然后会有 loading 的指示器。（正常逻辑）
2. 第二次加载同一个url, 还是会出现 loading 的指示器。这个指示器应该不需要存在，像原生第二次就没有这个指示器。

问题可能出现在怎么判断本地有这张图片。如果是直接用api判断文件是否存在，就会有个异步过程。所以，对于下载过的图片，是否需要用一张表记录下来，key 对应图片的路径。判断图片在本地是否存在的逻辑变成直接从这张表里进行判断即可，表的加载时机放到 main 中，跟 SpUtil 类似这种。

个人愚见，不一定正确

**Comment by zmtzawqlp** [comment]
就算是下载到了本地，flutter 解码也需要时间，你觉得影响很大，是因为你的图片很大

**Comment by OHeroJ** [comment]
```dart
precacheImage(ExtendedNetworkImageProvider('url'), context)
```

将图片预先加载到内存中
