### ISSUE TITLE
请教：想实现类似浏览PDF的功能

### ISSUE THREAD

**Issue by Leadrive** [fluttercandies/extended_image#285]
我在服务器端，把PDF转化成图片，每一页是一张图片。
想用这个组件来实现类似浏览PDF的功能。
1、缓加载功能；
2、上下或左右连续浏览，每页之间留个页边距；
3、比如我在当前页放大到某个比例，移到下一页时，还是保持同样的比例；
4、比如我在当前页左移了5公分，移到下一页时，也是左移5公分；
请问能有类似的demo代码参考吗？谢谢！

**Comment by zmtzawqlp** [comment]
没有，官方有一个zoom的组件。你可以试试
