### ISSUE TITLE
URL变动，图片没有更新

### ISSUE THREAD

**Issue by paintingStyle** [fluttercandies/extended_image#287]
ExtendedImage.network，调试发现url更新后，对应图片没有更新, cache 设置为 false，也不行，使用系统的 Image.network(src) 可以正确显示

```
return ExtendedImage.network(
        image,
        width: width,
        height: height,
        fit: fit,
        cache: true,
      );
```

**Comment by zmtzawqlp** [comment]
url更新后，是指 同一个url ，变成内容吧？

Image.network(src), 这个如果是缓存在内存里面，一样不会变。除非重启应用。
而 ExtendedImage.network 是做了本地缓存的。
