### ISSUE TITLE
The class 'ExtendedCustomProvider' cannot extend 'ExtendedNetworkImageProvider' because 'ExtendedNetworkImageProvider' only has factory constructors 

### ISSUE THREAD

**Issue by jttttttttttttt** [fluttercandies/extended_image#289]
我想自己实现一个provider，关于限制一次性加载次数的方案。 但是extends ExtendedNetworkImageProvider报错了，里面的_network_image_io的我又import不到。

The class 'ExtendedCustomProvider' cannot extend 'ExtendedNetworkImageProvider' because 'ExtendedNetworkImageProvider' only has factory constructors (no generative constructors), and 'ExtendedCustomProvider' has at least one generative constructor.  Try implementing the class instead, adding a generative (not factory) constructor to the superclass ExtendedCustomProvider, or a factory constructor to the subclass.

**Comment by zmtzawqlp** [comment]
copy 复制，这是显示 分了io 和web
