### ISSUE TITLE
Get photo using POST method

### ISSUE THREAD

**Issue by amebrahimi** [fluttercandies/extended_image#292]
Hi, I have an endpoint that is a POST route and I have to send the file name as a parameter to get the picture. I wasn't able to found any solutions in the documentation nor in the issues section.

**Comment by zmtzawqlp** [comment]
you can override ImageProvider

**Comment by amebrahimi** [comment]
@zmtzawqlp could you please give a sample code

**Comment by zmtzawqlp** [comment]
copy all code

https://github.com/fluttercandies/extended_image_library/blob/e67006f75cdcdfabfe4890b9b9dd067cc17da48c/lib/src/_network_image_io.dart#L168

change this line into your code

**Comment by amebrahimi** [comment]
Thank you

**Comment by amebrahimi** [comment]
I changed the part I needed to but I don't find a place to pass my custom provider as an argument.

**Comment by amebrahimi** [comment]
Ok found It I have to pass the provider as an image to the ExtendedImage() constrictor.

```dart
child: ExtendedImage(image: CustomExtendedImage())
```
