### ISSUE TITLE
Loading lag on cached images

### ISSUE THREAD

**Issue by juancki** [fluttercandies/extended_image#294]
Images that are already cached in the device suffer from rendering lag when opened a new screen.

```
ExtendedImage.network(
      url,
      width: width,
      height: height,
      border: boxBorder,
      fit: fit,
      loadStateChanged: (state) {
        if (state.extendedImageLoadState == LoadState.failed) {
          return Center(
            child: Icon(defaultIcon ?? Icons.browser_not_supported),
          );
        }
        return null;
      },
      cache: true,
      headers: h,
      shape: BoxShape.rectangle,
      borderRadius: BorderRadius.all(Radius.circular(3.0)),
    );
  }
```

**Example (with lag).**
Screen A: No image.
Screen B: Screen with image.

If you switch between those two screens you see that the image takes some time to render (in the order of milliseconds).

**Example (without lag)**
Screen A: Screen with image.
Screen B: Screen with same image.

I believe this issue is because in the [initState](https://github.com/fluttercandies/extended_image/blob/bfa1a782c837b5d0376e2a7f0feffcc5afc206ff/lib/src/extended_image.dart#L726) it is directly set to `loading` without checking whether the image is in cache.

**Comment by zmtzawqlp** [comment]
It will take long time to render an big image no matter it's donwloaded, It's as design

**Comment by juancki** [comment]
Having smaller images does helps with the lag, thanks for the input.

**Comment by aquadesk** [comment]
I landed on this issue. It does not make sense I get 'loading' when the cache is hit.
