### ISSUE TITLE
Zoom in and zoom out programmatically

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercandies/extended_image#297]
I am using ExtendedImage package (https://pub.dev/packages/extended_image) for displaying images in Flutter for a desktop application, it's awesome.

Now I need to add zoom-in and zoom-out buttons to app, but ExtendedImage does not have a controller or such a thing to control zoom direction, how can I do that?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/bfa1a782c837b5d0376e2a7f0feffcc5afc206ff/example/lib/pages/simple/zoom_image_demo.dart#L30

**Comment by a-v-ebrahimi** [comment]
@zmtzawqlp 
This will reset the zoom, but I need to zoom-in and zoom-out, step by step, by clicking a button on screen.

**Comment by zmtzawqlp** [comment]
you can set zoom by your self https://github.com/fluttercandies/extended_image/blob/bfa1a782c837b5d0376e2a7f0feffcc5afc206ff/lib/src/gesture/extended_image_gesture.dart#L370

**Comment by zmtzawqlp** [comment]
some code like : gestureKey.currentState = GestureDetails();

**Comment by saigopin** [comment]
@a-v-ebrahimi  any solution?
