### ISSUE TITLE
ExtendedImageSlidePage for other widgets?

### ISSUE THREAD

**Issue by AndreGroeschel** [fluttercandies/extended_image#298]
Hi there,

thanks for the great plugin! We are using it for a gallery in our app and it works great.

In the gallery, we use the ExtendedImageSlidePage to go back from a detail image view to the gallery overview. Since we also have videos in the gallery, there should be the same gesture for returning from a detail video page to the gallery overview. Is this possible with ExtendedImageSlidePage or does this only work in combination with ExtendedImage?

**Comment by zmtzawqlp** [comment]
I have  public ExtendedImageSlidePageHandler. hope it works for you.

https://github.com/fluttercandies/extended_image/blob/4c2c5767b61252424e1f832b29a989d2ea554a20/example/lib/pages/simple/slide_page_demo.dart#L103
