### ISSUE TITLE
Show a long-vertical-scrollable image from asset?

### ISSUE THREAD

**Issue by AverageChau** [fluttercandies/extended_image#299]
I want to display a long vertical image that is convert from a pdf file. The only way I find is do as the code below but calculate the initialScale so the scale up image width fit the screen. However, I can't seem to find a way to get image size...
 

          ExtendedImage.asset(
            'assets/image_sample_2.jpg',
            mode: ExtendedImageMode.gesture,
            fit: BoxFit.contain,
            initGestureConfigHandler: ,
            initGestureConfigHandler: (state) {
              return GestureConfig(
                inertialSpeed: 100.0,
                initialScale: SOME_NUMBER // make it zoom so image width = screen width.,
                inPageView: true,
                initialAlignment: InitialAlignment.topCenter,
              );
            },
          );
          
     

image_sample_2.jpg
![image_sample_2](https://user-images.githubusercontent.com/25887242/108612502-ed5a7700-741b-11eb-8641-dd895575756b.jpg)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/4c2c5767b61252424e1f832b29a989d2ea554a20/example/lib/common/widget/pic_swiper.dart#L151

**Comment by AverageChau** [comment]
> https://github.com/fluttercandies/extended_image/blob/4c2c5767b61252424e1f832b29a989d2ea554a20/example/lib/common/widget/pic_swiper.dart#L151

Perfect!
