### ISSUE TITLE
Question about listener changes of image

### ISSUE THREAD

**Issue by Bes79** [fluttercandies/extended_image#300]
Is any way to listen change of image: flip, rotate, zoom?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/4c2c5767b61252424e1f832b29a989d2ea554a20/example/lib/pages/simple/zoom_image_demo.dart#L55

**Comment by zmtzawqlp** [comment]
flip, rotate is called by yourself， you don't know when ?

**Comment by Bes79** [comment]
Thanks for answer. Abоut flip nd rotate - you right. But then zoom or position you method ( gestureDetailsIsChanged ) not worked (. It just dont called.

**Comment by Bes79** [comment]
My code
return ExtendedImage.memory(
                          fileItems.first.data,
                          fit: BoxFit.contain,
                          mode: ExtendedImageMode.editor,
                          extendedImageEditorKey: imageKey,
                          initEditorConfigHandler: (state) {
                            return EditorConfig(
                                cropAspectRatio: calcW() / calcH(),
                                maxScale: 8.0,
                                // cropRectPadding: EdgeInsets.all(20.0),
                                hitTestSize: 20.0);
                          },
                          initGestureConfigHandler: (ExtendedImageState state) {
                            return GestureConfig(
                              gestureDetailsIsChanged: (GestureDetails details) {
                                print(details.totalScale);
                              },
                            );
                          },
                        );

**Comment by zmtzawqlp** [comment]
call back is in initEditorConfigHandler, please get 2.0.0

**Comment by Bes79** [comment]
Hi. Please say name of event. I install 2.0.0 but not fond any similar for me.
