### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by peterscodee** [fluttercandies/extended_image#304]
This is a request to add support for null safety to this package. See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by peterscodee** [comment]
Closed in favor of [https://github.com/fluttercandies/flutter_candies/issues/5](https://github.com/fluttercandies/flutter_candies/issues/5)

**Comment by peterscodee** [comment]
Since the referenced issue is not on this repository, I decided to let this open until the feature is merged.

**Comment by zmtzawqlp** [comment]
3.0.0 is ready on pub.dev.
