### ISSUE TITLE
extended_image >=2.0.0 depends on extended_image_library ^1.0.1

### ISSUE THREAD

**Issue by sgehrman** [fluttercandies/extended_image#306]
extended_image >=2.0.0 depends on extended_image_library ^1.0.1 which depends on path_provider ^1.1.2, extended_image >=2.0.0 requires path_provider ^1.1.2

  extended_image: 2.0.0

not sure what is happening.

**Comment by zmtzawqlp** [comment]
https://pub.flutter-io.cn/packages/extended_image/changelog

**Comment by houdayec** [comment]
> https://pub.flutter-io.cn/packages/extended_image/changelog

How to fix it?

**Comment by zmtzawqlp** [comment]
i didn't get it

**Comment by houdayec** [comment]
> i didn't get it

We cannot compile our app because of `extended_image_library` depending on `path_provider ^1.1.2`. However path_provider 2.0.0 is necessary for other packages to work in my project, I am migrating to unsound null safety.

**Comment by zmtzawqlp** [comment]
wait for null-safety
