### ISSUE TITLE
No named parameter with the name 'nullOk' Extended_image: ^2.0.0 FLutter 2

### ISSUE THREAD

**Issue by ajosecueto** [fluttercandies/extended_image#307]
No named parameter with the name 'nullOk' Extended_image: ^2.0.0 FLutter 2,

Works removing that named parameter

  void _updateInvertColors() {
    _invertColors = MediaQuery.of(context)?.invertColors ??
        SemanticsBinding.instance.accessibilityFeatures.invertColors;
  }

**Comment by zmtzawqlp** [comment]
use dev version for now . https://github.com/fluttercandies/extended_image/issues/258 
i will support null-safety and non-null-safety later
