### ISSUE TITLE
ExtenedImage Asset Provider

### ISSUE THREAD

**Issue by ManojMM026** [fluttercandies/extended_image#31]
Hello, Thanks for the great library. However, I would like to know is there any way I can have AssetProvider using this library?

Right now I am using native AssetProvider but it seems it doesn't cache image.
```
 decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
                color: Colors.black12,
                offset: Offset(0.0, 3.0),
                blurRadius: 10.0)
          ],
          borderRadius: BorderRadius.circular(10),
        image:  DecorationImage(
          image: new AssetImage('images/room.jpg'),
          fit: BoxFit.fill,
        ),
      ),
```

**Comment by zmtzawqlp** [comment]
you can't use with this. it need provider, not a widget.  may be you can show your case why do you want do this ?

**Comment by ManojMM026** [comment]
I have a container with rounded corner and shadow to it also with a background image. Everything else will be overlayed on that container. Since DecorationImage is already available I don't want to use Stack layout with image and then start overlaying things.

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/61381410-9d313f80-a8dd-11e9-8c2d-ecc10934a8ad.png)
see this

**Comment by ManojMM026** [comment]
I ended up using stack with ExtenedImage.Asset, Any way to pre-cache asset image?

**Comment by zmtzawqlp** [comment]
auto memory cache
