### ISSUE TITLE
Sound null safety – type 'Future<HttpClientResponse?>' is not a subtype of type 'FutureOr<HttpClientResponse>' in type cast

### ISSUE THREAD

**Issue by deguez07** [fluttercandies/extended_image#312]
Happens when using ExtendedImage.network and running with sound null safety
- Can also be due to the usage of http: ^0.13.0

There is no problem when running with flag --no-sound-null-safety
Full output: type 'Future<HttpClientResponse?>' is not a subtype of type 'FutureOr<HttpClientResponse>' in type cast

**Comment by carnevalli** [comment]
Same issue here. The extension can't load any image from network.

Flutter 2.0.1 Stable

**Comment by zmtzawqlp** [comment]
null-safety
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0'
dependencies:
  extended_image: ^3.0.0
non-null-safety
1.22.6 to 2.0, Flutter Api has breaking change，please use non-null-safety if you under 1.22.6.

environment:
  sdk: '>=2.6.0 <2.12.0'
  flutter: '>1.17.0 <=1.22.6'
dependencies:
  extended_image: ^3.0.0-non-null-safety

**Comment by zmtzawqlp** [comment]
2.0 you  can import null-safety package，so why do you need to run   --no-sound-null-safety

**Comment by deguez07** [comment]
Without it I get a "Failed to load image message", along with the following output: type 'Future<HttpClientResponse?>' is not a subtype of type 'FutureOr' in type cast

**Comment by zmtzawqlp** [comment]
extended_image: ^3.0.0 is ready for null-safety

**Comment by deguez07** [comment]
It should be, but I'm getting the error anyways

**Comment by zmtzawqlp** [comment]
i can't reproduce at my side, i suggest you update packages

**Comment by zmtzawqlp** [comment]
ok, i had see it, i will fix it asap

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/commit/7f3d58fb6179258e441652ca23f4b829c28e41e2

**Comment by zmtzawqlp** [comment]
pls, try update extended_image_library to 2.0.2

**Comment by deguez07** [comment]
Ok, thanks!
