### ISSUE TITLE
Documentation needs to be more clear for memory cache

### ISSUE THREAD

**Issue by zaidkazi** [fluttercandies/extended_image#315]
Memory cache is not mentioned at all in the documentation. I spent hours debugging why my cache was not clearing when the key was no where to be found in memory.

PaintingBinding.instance.imageCache.clear(); should be mentioned as a solution to clear all cache in memory.

**Comment by zmtzawqlp** [comment]
raw image data is cached in memory now, i will make it as option in next version.
