### ISSUE TITLE
Call needCrop action on change crop area

### ISSUE THREAD

**Issue by aminbbb92** [fluttercandies/extended_image#317]
Hi
needCrop action only fire when image move,
is it possible get cropped image when crop area change, (not moved) (with corners handles)

**Comment by aminbbb92** [comment]
![Untitled](https://user-images.githubusercontent.com/10178886/111072174-9ca3de80-84ee-11eb-944f-6e92fa845b15.png)

**Comment by zmtzawqlp** [comment]
i will add in next version
