### ISSUE TITLE
How to fill image in given sized and remove image background color ?

### ISSUE THREAD

**Issue by pradeep-gc** [fluttercandies/extended_image#321]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ExtendedImage(dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#2cf13], Directionality, _EffectiveTickerMode], state: _ExtendedImageState#393a2(stream: ImageStream#50a63(MultiFrameImageStreamCompleter#e1a8b, [960×1280] @ 1.0x, 1 listener), pixels: [960×1280] @ 1.0x, loadingProgress: null, frameNumber: 0, wasSynchronouslyLoaded: false)):
Make sure the image is all painted to crop,the fit of image must be BoxFit.contain
'package:extended_image/src/editor/extended_image_editor.dart':
Failed assertion: line 21 pos 16: 'extendedImageState.imageWidget.fit == BoxFit.contain'

![image](https://user-images.githubusercontent.com/67050093/112110368-cdfc6880-8bd8-11eb-849c-a77efe75c1de.png)

**Comment by pradeep-gc** [comment]
How to fit image in given sized, when I fit image as BoxFit.fill then throwing below error.

Make sure the image is all painted to crop,the fit of image must be BoxFit.contain
'package:extended_image/src/editor/extended_image_editor.dart':
Failed assertion: line 21 pos 16: 'extendedImageState.imageWidget.fit == BoxFit.contain'

**Comment by zmtzawqlp** [comment]
Make sure the image is all painted to crop,the fit of image must be BoxFit.contain

so what do you want to do?

**Comment by pradeep-gc** [comment]
I want to show image in given height and width. How to fit image so that no shadow will be shown in top and bottom background. I want to fit in area.

![image](https://user-images.githubusercontent.com/67050093/112250596-a8766a00-8c7f-11eb-8978-406943236583.png)

**Comment by zmtzawqlp** [comment]
This is edit function, why you don't want ??

**Comment by zmtzawqlp** [comment]
you can define editor layer now
