### ISSUE TITLE
Rotate ExtendedImage in GesturePage

### ISSUE THREAD

**Issue by moffatman** [fluttercandies/extended_image#322]
Is there a way to have ExtendedImage.network for example that is rotated right or left? The use case is that I have some images in ExtendedImageGesturePageView, I want to rotate certain images so they will fit better. I tried using RotatedBox around the ExtendedImage but it caused the gestures to be rotated as well, it behaves very strangely. Probably it needs a code change in library, I am happy to help contribute, just wanted to know if you thought of a way to do it existing first. 

It doesn't need to be a rotate gesture, I know in my widget whether to rotate or not, calculated on the aspect ratio.

**Comment by zmtzawqlp** [comment]
i didn't get your point, may be you can override provider and rotate image in https://github.com/fluttercandies/extended_image_library/blob/af713550c678ef17e998ec5614a38e79d99af115/lib/src/extended_image_provider.dart#L52

**Comment by moffatman** [comment]
The purpose is that I have URL to an image, I want to have that image in the slideOutPage gallery, so I can use all the gestures (pinch to zoom, pan, slide to pop), but I want the image to be rotated 90 degrees to the right. I will look at that part of the code, I think it has to be done early so yeah changes in the provider would be the right spot. Custom slideoutpage child isn't appropriate since I don't think gestures could be used then.
