### ISSUE TITLE
不能正常加载图片

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/extended_image#324]
控制台一直循环打印这句话
```
Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: () => Null
```
## 开始是正常的,后来想升级flutter2.0.3,无奈太多的插件不兼容又回退版本,然后就出现图片不能加载出来的问题

**Comment by mdddj** [comment]
用Image.network 可以正常显示

**Comment by zmtzawqlp** [comment]
升级

**Comment by WangNingN** [comment]
我也遇到这个问题了，用Image.network可以显示，但是那些单机双击缩放的事件没办法相应了，得自己去实现这些功能吗？

**Comment by zmtzawqlp** [comment]
升级到最新就好了。

**Comment by WangNingN** [comment]
我们SDK的版本不允许升级到最新。。。。太难了，如果我自己改源码的话，改动大吗

**Comment by WangNingN** [comment]
> 升级到最新就好了。

我们SDK的版本不允许升级到最新。。。。太难了，如果我自己改源码的话，改动大吗

**Comment by zmtzawqlp** [comment]
你出问题的版本已经是 空安全的了，没影响啊。。3.00有这个问题，你升级到4.00就好了

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/116018500-b7807b80-a674-11eb-8a4e-b4ff4b520508.png)

**Comment by zmtzawqlp** [comment]
问题是3.0 迁移空安全出来的。你们升级到最新就好了

**Comment by mdddj** [comment]
...

**Comment by zmtzawqlp** [comment]
能用 3.0，就能用4.0，不用3.0. 就没有这个问题

**Comment by WangNingN** [comment]
> 能用 3.0，就能用4.0，不用3.0. 就没有这个问题

我是2.0.0版本的。。。3.0也用不了

**Comment by WangNingN** [comment]
> 能用 3.0，就能用4.0，不用3.0. 就没有这个问题

请问您一下，如果自己改的话，改动大吗，是哪个地方的bug呢

**Comment by zmtzawqlp** [comment]
> > 能用 3.0，就能用4.0，不用3.0. 就没有这个问题
> 
> 请问您一下，如果自己改的话，改动大吗，是哪个地方的bug呢

你可以告诉我你用的什么版本吗？？

**Comment by WangNingN** [comment]
> > > 能用 3.0，就能用4.0，不用3.0. 就没有这个问题
> > 
> > 
> > 请问您一下，如果自己改的话，改动大吗，是哪个地方的bug呢
> 
> 你可以告诉我你用的什么版本吗？？

您好，我用的2.0.0版本的

**Comment by zmtzawqlp** [comment]
我说 extended image的版本多少，我让你升级。。是升级 组件。。不是sdk

**Comment by WangNingN** [comment]
> 我说 extended image的版本多少，我让你升级。。是升级 组件。。不是sdk

extended_image: ^2.0.0组件就是2.0.0版本的，我们SDK是1.22.5版本的

**Comment by zmtzawqlp** [comment]
那不会报错。没影响啊。。这个问题是空安全迁移报错呀

**Comment by zmtzawqlp** [comment]
你直接用 4.0.1-non-null-safety 吧。功能同步的，支持1.22.6

**Comment by WangNingN** [comment]
> 那不会报错。没影响啊。。这个问题是空安全迁移报错呀

我这边测的是会报错，而且图片显示不出来。1.22.6也用不了，我们所有人都是用的1.22.5版本的，如果我升级了其他人是不是也会报错呀

**Comment by WangNingN** [comment]
请教您一下，如果我自己改2.0.0版本的代码的话，需要改哪里呢

**Comment by zmtzawqlp** [comment]
2.0.0不会报错呀，我哪里知道要改什么地方，你可以开一个新issue吗。。贴上面版本和日志

**Comment by WangNingN** [comment]
> 2.0.0不会报错呀，我哪里知道要改什么地方，你可以开一个新issue吗。。贴上面版本和日志

我现在改成4.0.1版本了，大佬有联系方式么，能加个微信交流一下么，wn1083045410，打扰了

**Comment by zmtzawqlp** [comment]
加群，问群里人
