### ISSUE TITLE
Option to cache reduced image size to disk

### ISSUE THREAD

**Issue by amugofjava** [fluttercandies/extended_image#327]
Hi,

I love how fast this package is at decoding and displaying images. What I think would be really useful would to be able to cache the image to disk at a reduced size rather than the original size. At the moment, any setting of `cacheHeight`/`cacheWidth` only effects the size stored in ram - the original image is stored to disk. If it was possible to also specify a maximum width and/or height when caching it to disk I would image subsequent fetches (for example on next app start) would be even faster.

Thanks.

**Comment by zmtzawqlp** [comment]
you can try maxBytes or compressionRatio

    ExtendedImage.network(
      'imageUrl',  
      compressionRatio: 0.1,
      maxBytes: null,
      cacheWidth: null,
      cacheHeight: null,  
    )

**Comment by zmtzawqlp** [comment]
you can try maxBytes or compressionRatio

    ExtendedImage.network(
      'imageUrl',  
      compressionRatio: 0.1,
      maxBytes: null,
      cacheWidth: null,
      cacheHeight: null,  
    )

**Comment by zmtzawqlp** [comment]
and you can override method in provider 

https://github.com/fluttercandies/extended_image_library/blob/af713550c678ef17e998ec5614a38e79d99af115/lib/src/extended_image_provider.dart#L52

**Comment by amugofjava** [comment]
Thanks for the quick reply @zmtzawqlp. The `compressionRatio` and `maxBytes` - don't they only effect the image stored in RAM? Looking at the `extended_image_library` when it comes to caching to disk it always stores it at the original size? Or do I have the incorrect? Thanks.

**Comment by zmtzawqlp** [comment]
you can override this method as you wish

**Comment by amugofjava** [comment]
OK thank you @zmtzawqlp - I'll try that.

**Comment by zmtzawqlp** [comment]
in fact，why don't reduce image size at service side? it is not reasonable

**Comment by amugofjava** [comment]
I don't have control server side @zmtzawqlp. I've built a podcast player app so all the images come from the podcasters' servers.
