### ISSUE TITLE
Load cropped version of image

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercandies/extended_image#328]
How can I load a cropped area of image, for example load a person face in an image with multiple people.
I need to specify left,top,right,bottom, and ExtendedImage displays that area initially.

Thanks

**Comment by zmtzawqlp** [comment]
I can't get it

**Comment by zmtzawqlp** [comment]
can you provide more info about it?

**Comment by revroad-dev** [comment]
This sounds like what we need to do. We need to be able to load the cropper with an initial crop rect, rotation, and flip that we have saved from a previous crop of the image. Is there any way to do that?

**Comment by zmtzawqlp** [comment]
IMO, you can't make sure the setting is good for editor, and if the width/height of Image are not the same, the previous crop will not right for new one

**Comment by zmtzawqlp** [comment]
close , it's the same as https://github.com/fluttercandies/extended_image/issues/333#issuecomment-876677294
