### ISSUE TITLE
Error: ExtendedImageSlidePageState was disposed with an active Ticker.

### ISSUE THREAD

**Issue by psh90525** [fluttercandies/extended_image#329]
The following error occurs when navigator.pop() is called during slide out.

════════ Exception caught by widgets library ═════════════
The following assertion was thrown while finalizing the widget tree:
ExtendedImageSlidePageState#6e151(ticker active) was disposed with an active Ticker.

ExtendedImageSlidePageState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

════════════════════════════════════════════

I think controller.dispose() must be called before calling super.dispose()

AS-IS
```
@override
void dispose() {
  super.dispose();
  _backAnimationController.removeListener(_backAnimation);
  _backAnimationController.dispose();
}
```

TO-BE
```
@override
void dispose() {
  _backAnimationController.removeListener(_backAnimation);
  _backAnimationController.dispose();
  super.dispose();
}
```

Thanks.

**Comment by zmtzawqlp** [comment]
yes, you are right. i will fix it in next version, thanks
