### ISSUE TITLE
Is it possible to apply a cache rule to keep the cache only for 1 day and free the memory from disk

### ISSUE THREAD

**Issue by sohitEngg** [fluttercandies/extended_image#330]
Right now I am looking for an image cache library which can hold the cache for the image only for certain amount of time(some hours some days) and free the memory then to load the remote fresh image instead of using cache whenever image is required.
Basically want to save disk storage from increasing the memory consumption exponentially.

**Comment by zmtzawqlp** [comment]
you can define a provider by yourself https://github.com/fluttercandies/extended_image_library/issues/20
