### ISSUE TITLE
图片放大后水平滑动时不能垂直或者任意方向拖拽

### ISSUE THREAD

**Issue by weboey** [fluttercandies/extended_image#331]
![image](https://user-images.githubusercontent.com/14002656/113841401-3d22b100-97c4-11eb-8d4c-23fc4df4f290.png)

PageView的滑动和拖拽冲突的问题，放大图片后如果长按图片先垂直方向拖拽然后就可以任意方向拖拽，如果是先水平方向拖拽，这时就不能垂直方向拖拽了，只能一直水平方向滑动。当PageView ScrollPhysics属性使用NeverScrollableScrollPhysics时，放大图片可以任意方向拖拽滑动查看。此问题有解决办法吗？能像微信一样放大图片水平滑动时也能任意方向拖拽滑动！

**Comment by zmtzawqlp** [comment]
不能重现，另外。请参考https://github.com/fluttercandies/extended_image/issues/152

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/293 关闭，一样
