### ISSUE TITLE
How to set initial crop rect

### ISSUE THREAD

**Issue by abc873693** [fluttercandies/extended_image#333]
I use `ExtendedImageMode.editor`, how to set editor crop rect in first time?

**Comment by momoDragon** [comment]
Any answer on this? i have a scenario that required to preload the crop based on saved parameters

**Comment by revroad-dev** [comment]
We also need to set initial crop, rotate, and flip based on a previous crop. Is there any way to do this?

**Comment by zmtzawqlp** [comment]
IMO, you can't make sure the setting is good for editor, and if the width/height of Image are not the same, the previous crop will not right for new one. 

flip, rotate, scale can be set, but not the crop rect, you can't make sure it works.

**Comment by jacob-hutchings** [comment]
I worked on setting initial crop state. Feel free to improve. The solution is kind of ugly, only tested with an aspect ratio of 1, and flashes sometimes on load.

https://github.com/RevRoad/extended_image/tree/initial-crop-state

**Comment by priyesh-bit** [comment]
> I worked on setting initial crop state. Feel free to improve. The solution is kind of ugly, only tested with an aspect ratio of 1, and flashes sometimes on load.
> 
> https://github.com/RevRoad/extended_image/tree/initial-crop-state

Can I initialize layout Rect which I previously set on an image? And is your repo updated with the latest official dependency?

**Comment by priyesh-bit** [comment]
Please refer to below video, this is what I'm facing now
https://user-images.githubusercontent.com/68454954/135403130-4e94c333-29e9-4c27-be67-8bc858c7bdbb.mp4

**Comment by IraDolynska** [comment]
is there any updates with this issue?
I am woking with editing photos, so if user crop it or change align I need to save this values so when user came back to this photo editing he could continue his actions
how I can update editor key with custom values?

**Comment by benyaminbeyzaie** [comment]
I'm working on this feature will update soon ‌✌️

**Comment by benyaminbeyzaie** [comment]
check out this PR guys: https://github.com/fluttercandies/extended_image/pull/462
Using initial aspect ratio you can set a initial aspect ratio for crop on your editor 😋

**Comment by aduval** [comment]
The question was about setting the crop rect values (x, y, width, height), but the PR is about setting an initial crop rect ratio. This is not the same thing. I think this issue should be reopened.

**Comment by jeff-odopass** [comment]
I agree this should definitely be reopened

**Comment by jeff-odopass** [comment]
For those who need this feature and want to implement themselves a temporary solution, you can fork the repository and:
- Add a `Rect? initialCropRect;` property in editor_utils.dart, with necessary code changes
- Update this line of code in editor.dart
<img width="663" alt="Screenshot" src="https://user-images.githubusercontent.com/75745261/225009337-1061c503-d2ff-4439-a4a7-3af022a7cb03.png">

**Be careful with this as it does not check if the provided `initialCropRect` works for the editor, it assume the provided value is correct.**

**Comment by kotchuprik** [comment]
@zmtzawqlp what do you think about adding this feature?

**Comment by qpalzm963** [comment]
請問新版本能夠初始化裁切值了嗎 
有保存ExtendedImageEditorState 不過還是會被重置
