### ISSUE TITLE
How to disable pan and zooming by fingers but allow double tapping to zoom the image

### ISSUE THREAD

**Issue by ahmed951** [fluttercandies/extended_image#334]
I want to disable zooming the image by fingers and allow the user to zoom it only by double tapping it so I can't use `ExtendedImageMode.none` for this .

And Thank you for this awesome package.

**Comment by ahmed951** [comment]
@zmtzawqlp

**Comment by zmtzawqlp** [comment]
not  support for now， you can use GestureDetector to do it.
