### ISSUE TITLE
Fade editor painter in and out when cropping

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_image#338]
Hey,
Currently the painter pop in and out without any smoothing.
It would be great if there was a fade so the lines and mask will show and disappear smoothly.

If this is already possible, please give an example.

Thanks.

**Comment by zmtzawqlp** [comment]
i didn't get it . smoothly? when pointer down show, pointer up disappear. It's a short, quick operation, i don't think it needs animation. 
https://github.com/fluttercandies/extended_image/blob/19f3ca693ce38a5c580348a8051b218565ca142d/example/lib/pages/complex/image_editor_demo.dart#L520

**Comment by naamapps** [comment]
Hi @zmtzawqlp, you are right, it is a quick operation.
But when using a custom mask (circle mask for example), the color change is popping and not easy on the eyes. 
When using the default mask, the lines of the editor also pop in and out. 

It is just a suggestion to improve the UX of the editor.
Hope you understand,
Thanks.
