### ISSUE TITLE
Make the editor less stiff and more bouncy

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_image#339]
Hey,
The editor is a bit stiff to my taste when panning, it stops right when there is no more where to go.

I think it would be nicer on the eyes to make the editor more bouncy (like Instagram).
So when panning around, it doesn't stop the user immediately, but give the possibility to over-pan. 

Would like to hear your opinion about this,
Thanks.

**Comment by zmtzawqlp** [comment]
no plan for now
