### ISSUE TITLE
仿微信图片滑动退出页面效果,下滑退出时，动画能否从下滑到的位置开始，到原有位置结束啊？

### ISSUE THREAD

**Issue by ginoz** [fluttercandies/extended_image#34]
仿微信图片滑动退出页面效果 这个默认是把图片拉伸全屏再缩放到原来位置，没有办法从下拉结束的位置动画到原来位置啊？

**Comment by zmtzawqlp** [comment]
这是hero动画的问题，只能找官方解决

**Comment by ginoz** [comment]
有这个问题官方issues的ID嘛，我好持续关注下

**Comment by AlexVincent525** [comment]
@ginoz https://github.com/flutter/flutter/issues/20510
