### ISSUE TITLE
Editor doesn't let the user to pan and zoom at the same time

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_image#340]
Hey,
Currently the editor let the user to either pan or zoom.

It would be nice to have the ability to pan and zoom simultaneously.

Thanks

**Comment by zmtzawqlp** [comment]
gesture arena

**Comment by naamapps** [comment]
Hi @zmtzawqlp, I don't understand what do you mean by gesture arena?

**Comment by zmtzawqlp** [comment]
flutter gestures have conflicting, it will not fire other one before this one end.

**Comment by naamapps** [comment]
You can actually use the scale details from the gesture detector to determine the focal point and move the image according to the positioning of the fingers.

So when panning with one finger the pointer events are fired, and when using the gesture detector scale functions you also scale the image and pan at the same time.

Here you can use the details to also pan and scale at the same time. 
https://github.com/fluttercandies/extended_image/blob/19f3ca693ce38a5c580348a8051b218565ca142d/lib/src/editor/extended_image_editor.dart#L206

**Comment by zmtzawqlp** [comment]
don't want to make gesture ambiguous.

**Comment by naamapps** [comment]
@zmtzawqlp, Why not?
I think it solves the issue and makes the package better in terms of UX for the user.
If your concern is about code reliability or maintenance, than maybe add comments?

Please reconsider adding this feature.
Thanks
