### ISSUE TITLE
set [ExtendedImageProvider.cacheRawData] to true

### ISSUE THREAD

**Issue by aaesDev** [fluttercandies/extended_image#341]
i've been using the image editor package and when i try to crop with the same code used in your example app for the package image_editor, it gives me this error

Unhandled Exception: 'package:extended_image_library/src/extended_image_provider.dart': Failed assertion: line 34 pos 12: 'cacheRawData': you should set [ExtendedImageProvider.cacheRawData] to true, if you want to get rawImageData from provider.

**Comment by aaesDev** [comment]
Future<void> crop([bool test = false]) async {
    final ExtendedImageEditorState? state = editorKey.currentState;
    if (state == null) {
      return;
    }
    final Rect? rect = state.getCropRect();
    if (rect == null) {
      showToast('The crop rect is null.');
      return;
    }
    ui.Image? imageData = state.image;
    if (imageData == null) {
      return;
    }
    var data = await imageData.toByteData(format: ui.ImageByteFormat.png);
    if (data == null) {
      return;
    }
    // image.Image? src = decodePng();
    final EditActionDetails action = state.editAction!;

    final double radian = action.rotateAngle;

    final bool flipHorizontal = action.flipY;
    final bool flipVertical = action.flipX;

    final ImageEditorOption option = ImageEditorOption();

    option.addOption(ClipOption.fromRect(rect));
    option.addOption(
        FlipOption(horizontal: flipHorizontal, vertical: flipVertical));
    if (action.hasRotateAngle) {
      option.addOption(RotateOption(radian.toInt()));
    }
    option.outputFormat = const OutputFormat.png(88);
    print(const JsonEncoder.withIndent('  ').convert(option.toJson()));
    final DateTime start = DateTime.now();

    final Uint8List? result = await ImageEditor.editImage(
      image: data.buffer.asUint8List(),
      imageEditorOption: option,
    );

    print('result.length = ${result?.length}');

    final Duration diff = DateTime.now().difference(start);

    print('image_editor time : $diff');
    showToast('handle duration: $diff',
        duration: const Duration(seconds: 5), dismissOtherToast: true);

    if (result == null) return;

    showPreviewDialog(result);
  }

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/master/CHANGELOG.md
