### ISSUE TITLE
升级到4.0.0之后出现错误问题，请问如何解决

### ISSUE THREAD

**Issue by ltq2017** [fluttercandies/extended_image#342]
请问一下升级：extended_image 4.0.0之后，第一次打开图片正常，第二次打开图片出现错误问题
请问如何解决。
![5B52C61B1154EC2774D460944E2AB5EA](https://user-images.githubusercontent.com/33394752/115361371-19fbf680-a1f3-11eb-87d5-c7612f569f3f.jpg)

**Comment by ltq2017** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/33394752/115362369-0ac97880-a1f4-11eb-91f5-5f4a35afdbc6.png">

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/343 
the same
