### ISSUE TITLE
升级到4.0.0之后出现错误问题，请问如何解决 

### ISSUE THREAD

**Issue by ltq2017** [fluttercandies/extended_image#345]
Flutter 2.0.5

1、第一次打开图片显示正常，再次打开会出现如下错误，

════════ Exception caught by widgets library ═══════════════════════════════════
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
The relevant error-causing widget was

**Comment by zmtzawqlp** [comment]
the same https://github.com/fluttercandies/extended_image/issues/343
