### ISSUE TITLE
Crop images with circle shape UI

### ISSUE THREAD

**Issue by kiaxseventh** [fluttercandies/extended_image#346]
can you add support circle shape frame UI on crop image  ?
i need just circular UI but  export square image 1:1 size

**Comment by zmtzawqlp** [comment]
in fact， image is always  a rect, you can show it with circular

**Comment by zmtzawqlp** [comment]
here are the demo. https://github.com/fluttercandies/extended_image/blob/978092941fbe5e241221ba885f88263d3344c51b/example/lib/pages/complex/image_editor_demo.dart#L495
