### ISSUE TITLE
How to refresh ExtendedImage so it calls afterPaintImage again

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercandies/extended_image#347]
Hi
I am drawing some data from network on image, using afterPaintImage.
But setState does not refresh ExtendedImage, so afterPaintImage is not called, unless I zoom or unzoom.
How can I just refresh image so it recalls afterPaintImage ?
Thanks

**Comment by zmtzawqlp** [comment]
new function of afterPaintImage

**Comment by a-v-ebrahimi** [comment]
I just found adding a key to ExtendedImage is enough to setState
