### ISSUE TITLE
Bad state: Failed to load http://i.gtimg.cn/qqlive/images/newcolumn/v1/h/h1pyw6.jpg.

### ISSUE THREAD

**Issue by SinoMiles** [fluttercandies/extended_image#348]
![image](https://user-images.githubusercontent.com/9588025/115981018-68c6d900-a5c3-11eb-87ff-25bc82cc322e.png)
这个图是哪来的？我项目里都没这个东西。

**Comment by zmtzawqlp** [comment]
我也不知道也，你项目里面找找。

**Comment by yenyichau** [comment]
我也是有这个问题。请问是什么问题？
