### ISSUE TITLE
使用2.0.0版本，Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: () => Null

### ISSUE THREAD

**Issue by WangNingN** [fluttercandies/extended_image#349]
您好，请教一个问题，使用2.0.0版本，图片加载不出来，一直报Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: () => Null
如果使用Image.network点击事件还有缩放功能就只能自己实现了吗？还有其他办法吗

**Comment by zmtzawqlp** [comment]
升级到4.0.1
