### ISSUE TITLE
图片加载时 loading 样式 可否自定义

### ISSUE THREAD

**Issue by guduge** [fluttercandies/extended_image#35]
switch (_loadState) {
          case LoadState.loading:
            current = Row(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Center(
                   child: _getIndicator(context),
              ) ,
                  SizedBox(
                    width: 5.0,
                  ),
                  Text("loading...")
                ],
            );
            break;

你的源码是这样，假如我图片预览背景是黑色的，那么 “loading。。。”这几个字显示不出来，就只能看到CupertinoActivityIndicator 骗左，建议 loading样式可从外部传进去一个widget

**Comment by zmtzawqlp** [comment]
建议读完文档再提问题
