### ISSUE TITLE
添加数据 setState的时候 图片会闪一下 出现加载动画

### ISSUE THREAD

**Issue by xiao-cao-x** [fluttercandies/extended_image#351]
![code](https://user-images.githubusercontent.com/76673990/116262461-2233d300-a7ab-11eb-8e79-973a3e549138.png)

**Comment by zmtzawqlp** [comment]
as design

**Comment by xiao-cao-x** [comment]
今天试了下还是一模一样
只能嵌套CachedNetworkImageProvider来解决
