### ISSUE TITLE
when I copy the doubleTap zoom code from docs it shows error?

### ISSUE THREAD

**Issue by shabhi1997** [fluttercandies/extended_image#352]
the code to implement is not clear in docs . I have gone through examples but there are only examples for pan and zoom. Could you provide a link on the implementation of double tap to zoom.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/2d44d98eff67142af4e0cb8e4563381a4a0d74cf/example/lib/common/widget/pic_swiper.dart#L167
