### ISSUE TITLE
[Possible BUG] The crop adjustments will be lost & reset after the widget tree rebuilds. How to keep the state?

### ISSUE THREAD

**Issue by yasinarik** [fluttercandies/extended_image#357]
I put the `ExtendedImage` widget inside a scrollable, for example.

I can successfully adjust the crop area while it is stationary. However, if I start scrolling since the widgets are rebuilt, the crop area will be reset immediately.

The position of the crop box stays the same but the underlying image will be centered to its initial position.

There should be something to keep & save the current adjustments, in my opinion.

Thanks for creating lots of useful packages!

**Comment by zmtzawqlp** [comment]
may be you can add a key for this widget, or keep alive , something like keep text filed in listview

**Comment by yasinarik** [comment]
Yes, that came to my mind. So I gave it a constant key and refactored it into a separate stateful widget with `AutomaticKeepAliveMixin`.

Still no chances. It resets. I mean the package is very good and usable but if it moves inside something like a scrollable view, it rebuilds every frame. So the position of the image will be reset.

**Comment by zmtzawqlp** [comment]
please provide runnable simple demo

**Comment by zmtzawqlp** [comment]
save crop editinfo, and reset it when it rebuild in list

**Comment by lhb2435TW** [comment]
> save crop editinfo, and reset it when it rebuild in list

@zmtzawqlp Can you provide a simple code? There are several images. I am losing state of the previously cropped image.

**Comment by lhb2435TW** [comment]
> > save crop editinfo, and reset it when it rebuild in list
> 
> @zmtzawqlp Can you provide a simple code? There are several images. I am losing state of the previously cropped image.

I solved it
