### ISSUE TITLE
Cache does not working for Flutter web

### ISSUE THREAD

**Issue by liqiang1995** [fluttercandies/extended_image#359]
How are you?
Image cache does not support Flutter web.
Image is loaded from the server every time.
How can i do?
thank you

**Comment by AryashDubey** [comment]
https://pub.dev/packages/paulonia_cache_image Hey man check this package out. It supports caching on web but misses out on all other features your wonderful package provides!

**Comment by zmtzawqlp** [comment]
It's use hive to store data, you can override provider, do as the same
