### ISSUE TITLE
滑动退出时的几个建议

### ISSUE THREAD

**Issue by luckysmg** [fluttercandies/extended_image#36]
在滑动退出时，能否搞一个自定义的滑动边界参数（也就是滑动退出时如果offset的到达这个自定义的临界offset，那就判定为退出的参数），因为我感觉和手机qq的图片预览相比，您的这个滑动退出的判定貌似比较吃力，要把手指移到稍微下面一点的地方才能判定为退出，手机qq是手指往下一扫就退出了，比较轻松，所以看看能不能稍微优化一下捏😂，还有我遇到一个问题就是在滑动退出的最后一瞬间图片还留在屏幕上，然后突然闪没了，这个能设置么？

**Comment by zmtzawqlp** [comment]
不是有吗。。好好看demo
