### ISSUE TITLE
Null check operator used on a null value 

### ISSUE THREAD

**Issue by Mayb3Nots** [fluttercandies/extended_image#366]
This exception was thrown here on `layoutTopLeft`.
https://github.com/fluttercandies/extended_image/blob/3a05871ce95b9d2b0d9cd385b4136b73f4afd590/lib/src/editor/extended_image_editor_utils.dart#L77-L81

I have an Instagram-like editor, and when the user selects multiple images each image loads a Widget that contains an ImageEditor when the user select multiple images too quickly and doesn't load the Widget this error is thrown when calling `getCropRect()`.
What is going on here? Why can `layoutTopLeft `be null?

**Comment by zmtzawqlp** [comment]
can you provide an runnable demo to reproduce this issue?

**Comment by Mayb3Nots** [comment]
Hi @zmtzawqlp this can be reproduced if you build the ExtenedImage editor Widget and it hasn't load finish the state and you switch away. Basically, the state is not yet loaded. My solution was to wait till the `initEditorConfigHandler` is called then allow the next image to be picked.

**Comment by Mayb3Nots** [comment]
I do not think it is a bug on this package. But is there a way to set a callback ONLY when the image state is being generated? I tried `WidgetsBindings.instance.addPostFrameCallback` but it doesn't work.

**Comment by zmtzawqlp** [comment]
try use loadstate is completed
