### ISSUE TITLE
ExtendedImageGesturePageView 不同模式滑动问题

### ISSUE THREAD

**Issue by nx6313** [fluttercandies/extended_image#367]
ExtendedImageGesturePageView 里，如果第一页设置模式为：ExtendedImageMode.none、第二页设置模式为：ExtendedImageMode.gesture，

滑动页面到第二页，放大该页的图片，再滑动回第一页，这时候，，再想滑动到第二页，页面好像会卡住，无法滑动到第二页了

**Comment by nx6313** [comment]
我是想实现第一页图片不能放大，仅仅只能点击。用来播放一个视频，相当于是在你这个ExtendedImageGesturePageView里，实现视频与图片混合排布的效果

**Comment by zmtzawqlp** [comment]
看demo
