### ISSUE TITLE
No option to make always visible crop layer painter

### ISSUE THREAD

**Issue by nayanbabariya95** [fluttercandies/extended_image#370]
Unable to make always visible crop layer (The white thin line grid that is visible when cropping)

I used below code:
```
ExtendedImage(
    image: ExtendedFileImageProvider(
      widget.imageFile,
      cacheRawData: true,
      imageCacheName:
          DateTime.now().millisecondsSinceEpoch.toString(),
    ),
    extendedImageEditorKey: _editorKey,
    mode: ExtendedImageMode.editor,
    fit: BoxFit.contain,
    initEditorConfigHandler: (_) => EditorConfig(
      maxScale: 8.0,
      cropRectPadding: const EdgeInsets.all(20.0),
      hitTestSize: 20.0,
      cornerColor: Colors.white,
      editorMaskColorHandler: (_, __) => Colors.black,
      cornerSize: Size(24, 1.4),
    ),
  ),
)
```

**Comment by zmtzawqlp** [comment]
override following code: 
https://github.com/fluttercandies/extended_image/blob/3a05871ce95b9d2b0d9cd385b4136b73f4afd590/lib/src/editor/extended_image_editor_utils.dart#L661

**Comment by nayanbabariya95** [comment]
@zmtzawqlp Thanks for the suggestion

It's working. need to make custom class by extending `EditorCropLayerPainter`
And also remove the `if` at [extended_image/lib/src/editor/extended_image_editor_utils.dart](https://github.com/fluttercandies/extended_image/blob/3a05871ce95b9d2b0d9cd385b4136b73f4afd590/lib/src/editor/extended_image_editor_utils.dart#L661)
