### ISSUE TITLE
ExtendedImage load again and again on setState

### ISSUE THREAD

**Issue by nayanbabariya95** [fluttercandies/extended_image#372]
When calling `setState` method, image loads again. so i feel flickering in image.

i want to change aspect ratio of image. my code snippet is:

```
// in stateful widget
double _aspectRatio = CropAspectRatios.original;

ExtendedImage(
  image: ExtendedFileImageProvider(
    widget.imageFile,
    cacheRawData: true,
    imageCacheName:
        DateTime.now().millisecondsSinceEpoch.toString(),
  ),
  extendedImageEditorKey: _editorKey,
  mode: ExtendedImageMode.editor,
  fit: BoxFit.contain,
  initEditorConfigHandler: (_) => EditorConfig(
      maxScale: 8.0,
      cropAspectRatio: _aspectRatio,
      cropRectPadding: const EdgeInsets.all(20.0),
      hitTestSize: 20.0,
      cornerColor: Colors.white,
      editorMaskColorHandler: (_, __) => Colors.black,
      cornerSize: Size(24, 1.4),
      cropLayerPainter: CustomCropLayerPainter()),
)
```

I am changing `_aspectRatio` value in onTap of aspect ratio button
But even calling `setState` for other things also loads image again

**Comment by zmtzawqlp** [comment]
define ExtendedFileImageProvider as property, new one means this is new image.

**Comment by zmtzawqlp** [comment]
imageCacheName:
        DateTime.now().millisecondsSinceEpoch.toString(), 

and you are define imageCacheName as millisecondsSinceEpoch??

This is not good, please take a look at demo, and think how imageCacheName works.

**Comment by nayanbabariya95** [comment]
@zmtzawqlp Thanks for helping
I forgot to made `ExtendedFileImageProvider` object globally in `StatefulWidget`
I understand that with the previous code it was creating the new object of `ExtendedFileImageProvider` when called 'setState'
