### ISSUE TITLE
Using the maxBytes property on a random picked image file and trying to crop this image will result in an error

### ISSUE THREAD

**Issue by Letalus** [fluttercandies/extended_image#373]
Following is the case:
1. User picks image with the ImagePicker
2. User crops images by clicking on the crop button (shown within the example
3. User gets following error displayed during cropping:

`[default] [ERROR] Could not create a bookmark: NSError: Cocoa 257 "The file couldn’t be opened because you don’t have permission to view it." }
flutter: native library start cropping
flutter: save failed: 'package:extended_image_library/src/extended_image_provider.dart': Failed assertion: line 38 pos 7: 'rawImageDataMap.containsKey(this)': raw image data is not already now!
 #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      ExtendedImageProvider.rawImageData (package:extended_image_library/src/extended_image_provider.dart:38:7)
#3      ExtendedImageEditorState.rawImageData (package:extended_image/src/editor/extended_image_editor.dart:307:34)
#4      cropImageDataWithNativeLibrary (package:example/common/utils/crop_editor_helper.dart:174:31)
#5      _ImageEditorDemoState._cropImage (package:example/pages/complex/image_editor_demo.dart:430:26)
#6      _ImageEditorDemoState._showCropDialog.<anonymous closure>.<anonymous closure> (package:example/pages/complex/image_editor_demo.dart:399:33)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#25     _rootRunUnary (dart:async/zone.dart:1370:13)
#26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#28     _invoke1 (dart:ui/hooks.dart:182:10)
#29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#30     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
`

To reproduce this bug, I forked your package and created a new branch called reproduce_maxBytes_bug.
The edited file within the example folder is called image_editor_demo.dart. You can access this by downloading the forked repo on your device, click on the "2. Complex" list tile and then on the "2. ImageEditor" list tile.

Here is the link to the described branch:
https://github.com/Letalus/extended_image/tree/reproduce_maxBytes_bug

I believe the error is thrown because the image does not get a key assigned, once maxBytes, cacheWidth or cacheHeight is not null.

Kindly await your help here.

**Comment by Letalus** [comment]
@zmtzawqlp thanks again for the awesome package. Are there any updates on this issue?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/blob/f05275bb812102f960bbfbefb5a0b4d831795b8c/lib/src/extended_image_provider.dart#L18

set it to true
