### ISSUE TITLE
Question: is there a way to disable the drag and resizing on the crop area?

### ISSUE THREAD

**Issue by YAPMZHA** [fluttercandies/extended_image#376]
Hi, thanks for the great library. I would like to know if it's possible to disable the drag/resizing of the crop area? It's a bit confusing when the user accidentally drag/zoom-in/out the picture and instead the crop area resizes. If there is a workaround it would also be great. Thanks a lot!

**Comment by zmtzawqlp** [comment]
sorry, this is no workaround for this. we did as most photo app did.

**Comment by zmtzawqlp** [comment]
same https://github.com/fluttercandies/extended_image/issues/387
