### ISSUE TITLE
Inverted direction of zoom by mouse wheel

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercandies/extended_image#382]
Hi
In other Windows apps, when we scroll up using the mouse wheel, it will zoom, but in ExtendedImage, it's inverse and for zoom up we should scroll down.
Some users complain about this.
Thanks

**Comment by gcostaapps** [comment]
Is there any workaround to fix that while it's not on the main branch?

**Comment by zmtzawqlp** [comment]
add reverseMousePointerScrollDirection in config , you can set as you wish
