### ISSUE TITLE
Can slideoutpage dismiss amount be modified?

### ISSUE THREAD

**Issue by mark8044** [fluttercandies/extended_image#386]
Can the amount someone moves the image to initiate the close of the image be modified?  By default the image has to be moved up a lot to dismiss the image, I'd like it to be a less amount

Thanks!!

**Comment by zmtzawqlp** [comment]
please read readme first

**Comment by mark8044** [comment]
I did read it over and over but its not totally clear.  My assumption is that it has to do with `slideOffsetHandler` but the documentation does not describe how to use it, nor are there any examples of it

Thanks
