### ISSUE TITLE
can you add support so that we can have placeholder and imageprovider at the same time?

### ISSUE THREAD

**Issue by Asuraxxx** [fluttercandies/extended_image#393]
for example,

```
CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/200x150",
  imageBuilder: (context, imageProvider) => Container(
    decoration: BoxDecoration(
      image: DecorationImage(
          image: imageProvider,
          fit: BoxFit.cover,
          colorFilter:
              ColorFilter.mode(Colors.red, BlendMode.colorBurn)),
    ),
  ),
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),
```

**Comment by zmtzawqlp** [comment]
you can define when statue changed

**Comment by Asuraxxx** [comment]
> you can define when loadStateChanged

i know i can have placeholder with extendedImage.network by specifying the loadStateChanged function,  but here i'd like to use extendedImageProvider in decorationImage so that i can have the inkwell effect and don't want to rewrite reloadimage and placeholder.

**Comment by zmtzawqlp** [comment]
you can do it too, i can't get the point why you can't?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/1795ccdd937a3b291525055f97733297517997e7/lib/src/extended_image_utils.dart#L24

**Comment by Asuraxxx** [comment]
> https://github.com/fluttercandies/extended_image/blob/1795ccdd937a3b291525055f97733297517997e7/lib/src/extended_image_utils.dart#L24

Could you give me an example to incorporate placeholder with imageprovider in the following code? 

```
Ink(
      decoration: BoxDecoration(
        shape: BoxShape.rectangle,
        borderRadius: BorderRadius.circular(10),
        image: DecorationImage(
          fit: BoxFit.cover,
          image: ExtendedResizeImage.resizeIfNeeded(
            provider: ExtendedNetworkImageProvider(
              url,
            ),
          ),
        ),
      ),
    );
```

**Comment by zmtzawqlp** [comment]
use loadStateChanged callback
