### ISSUE TITLE
[Web] Saving cropped photo very slow (30+ seconds)

### ISSUE THREAD

**Issue by nwparker** [fluttercandies/extended_image#394]
# Reproduction Steps
1. Launch the example on the web
2. Run complex image editor demo (`2. Complex > 2. ImageEditor`) (http://localhost:53505/#fluttercandies://imageeditor)
3. Load an image with a large file size (I will attach my testing image below)
4. Try to crop and save the image

# Expected Results
I would expect cropping to take 1-2 seconds max.

![d](https://user-images.githubusercontent.com/4138956/131596872-2199ebfe-c11e-4ed4-9319-d739ffa4ed49.jpeg)

**Comment by zmtzawqlp** [comment]
you should release issue for flutter team or.  https://pub.dev/packages/image

**Comment by nwparker** [comment]
> you should release issue for flutter team or. https://pub.dev/packages/image

Thank you for the reply, @zmtzawqlp 

However, your provided details aren't quite clear here. I see you are implying the issue is in the Image library, but what specifically do you believe to be the issue?

I'm happy to report the issue, but I would need additional details which you appear to know (and I do not). So would you mind sharing those with me?

**Comment by zmtzawqlp** [comment]
use https://pub.dev/packages/image to crop image data on web

**Comment by nwparker** [comment]
Okay, I looked into this more.

Running the code in debug mode: ~30+ seconds
Running the code in release mode (`--release` flag): ~11 seconds
Optimizing your example (code below): ~4 seconds

---
Decoding/encoding images is very expensive.
You can skip a decode by instead reading bytes directly with this method:
```dart
    final ui.Image decodedUiImg = await decodeImageFromList(data);
    final ByteData? newBytesData = await decodedUiImg.toByteData();
    final Uint8List newBytes = newBytesData!.buffer.asUint8List();
    final Image decodedImg = Image.fromBytes(decodedUiImg.width, decodedUiImg.height, newBytes);
    src = Animation()..addFrame(decodedImg);
```

This code could be improved (and probably made to work with animations).

It seems likely encode time could also be improved by utilizing HTML canvas methods. But that's a not as easy as an optimization as above.

Anyhow, in conclusion:
  1. Running in release mode greatly improves performance
  2. The example code for this project can be further optimized to avoid unnecessary encode/decode calls

**Comment by nwparker** [comment]
Okay, here's the native encoding logic. This will get the code to run in 2-3 seconds:

```dart
final Image img = src.first;
final Uint8List imgBytes = img.getBytes();

final html.CanvasElement myCanvas = html.CanvasElement(width: img.width, height: img.height);
final html.ImageData htmlImgData = html.ImageData(Uint8ClampedList.fromList(imgBytes), img.width);
myCanvas.context2D.putImageData(htmlImgData, 0, 0);
final String b64ImgData = myCanvas.toDataUrl('image/png').substring('data:image/png;base64,'.length);
fileData = base64Decode(b64ImgData);
```

Further optimization would be difficult as PNG encoding itself takes time. But I think 2-3 seconds is acceptable behavior (for now).

On smaller images, less time is required.
