### ISSUE TITLE
翻转目前只有水平翻转，可以增加垂直翻转吗

### ISSUE THREAD

**Issue by jiezhiliu** [fluttercandies/extended_image#395]
前两天项目需要裁剪图片，然后找到了这个插件，产品经理又想要一个水平和垂直翻转的功能，发现插件里面只有一个水平翻转，经测试之后发现，flip方法传递一个bool的参数是可以实现水平和垂直翻转功能的，

**Comment by zmtzawqlp** [comment]
不明白你说啥，急就fork 自己改
