### ISSUE TITLE
我现在在做图片裁剪。 基本功能都实现了。  最后一步裁剪生成图片看不懂了。    按照例子 有红线 

### ISSUE THREAD

**Issue by 18518278831** [fluttercandies/extended_image#396]
``    final Rect cropRect = state.getCropRect();
                final img = state.rawImageData;
                final rotateAngle = action.rotateAngle.toInt();
                final flipHorizontal = action.flipY;
                final flipVertical = action.flipX;

**Comment by zmtzawqlp** [comment]
提供更多的信息
