### ISSUE TITLE
Possible to trigger auto-center without touch the rect ?

### ISSUE THREAD

**Issue by Nico3652** [fluttercandies/extended_image#399]
I'm editing an image and apply a ratio on the image created like this :

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-20 at 21 36 50](https://user-images.githubusercontent.com/50270977/134063619-f1efa3bd-5ee8-488d-b9d5-1f0c2c8af7ca.png)

When the user is validating the crop **on saved button clicked** without moving the rect I'm getting this : 

 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-20 at 21 33 17](https://user-images.githubusercontent.com/50270977/134064091-c6f63dda-b35b-44a6-b21e-6925469f55b4.png)

I would like to force the auto-center when the user is validating without moving the rect.  

Is it possible to do this ? 

Thanks is advance

**Comment by zmtzawqlp** [comment]
sorry, i didn't get it

**Comment by zmtzawqlp** [comment]
sorry for delay reply, there is no way to do this for now
