### ISSUE TITLE
beta branch issue: `delta` renamed `focalPointDelta`

### ISSUE THREAD

**Issue by cpboyd** [fluttercandies/extended_image#400]
After updating, I'm now getting this build errors:
```
Error output from Xcode build:
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the name 'delta'.
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional arguments: 2 required, 1 given.
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments: 2 required, 1 given.
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments: 2 required, 1 given.
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional arguments: 2 required, 1 given.
    ../../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.0.0/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional arguments: 2 required, 1 given.
```

This seems to be related to https://github.com/flutter/flutter/pull/85718 and the fact that the plugin now uses the `delta` parameter.

**Comment by zmtzawqlp** [comment]
we only force on stable branch, keep this issue open when we switch to next stable release

**Comment by mono0926** [comment]
Fixed at https://github.com/mono0926/extended_image/tree/dev

You can use it like this:

```yaml
  extended_image:
    git:
      url: https://github.com/mono0926/extended_image
      ref: dev
```

And, I can make a pull request to https://github.com/fluttercandies/extended_image/tree/dev if it is desirable 👌

**Comment by zmtzawqlp** [comment]
thanks, await for next stable and fix it , ScaleUpdateDetails has breaking change not only delta. and master/beta/dev  always have breaking change.

**Comment by zmtzawqlp** [comment]
Flutter v2.8 will release  tomorrow， i will do it after that

**Comment by chavesgu** [comment]
@zmtzawqlp   when do you plan to update plugin for `flutter 2.8`

**Comment by zmtzawqlp** [comment]
done

https://github.com/fluttercandies/extended_image/commit/02031d799bd7ea175138b5a593aabfc46055c5da
