### ISSUE TITLE
ScrollView在小范围内滚动时 ExtendedImage.network 会闪一下 出现loading

### ISSUE THREAD

**Issue by xiao-cao-x** [fluttercandies/extended_image#402]
有一些比较大的图片(`比屏幕要高`) 上下滚动(无论快慢)的时候 会出现`loading` 加载动画 跟刷新了一样
之前添加数据的时候也是会闪一下出现加载动画 我把 `gaplessPlayback设置成ture` 加载的时候是不会闪了 但是滚动较大的图片的时候 还是会出现`loading` 导致`Widget高度变化` 看起来 `弹下去又有弹上来` 影响使用

**Comment by xiao-cao-x** [comment]
值得一提的是 我把extended_image版本降低到3.0.0 以上问题都没有了 也不需要 gaplessPlayback: true

**Comment by zmtzawqlp** [comment]
能帮忙看看是哪个版本出现的问题吗，我这边重现不了

**Comment by xiao-cao-x** [comment]
> 能帮忙看看是哪个版本出现的问题吗，我这边重现不了

4.2.1
之前的版本也有这个问题
只有3.0.0没有

**Comment by zmtzawqlp** [comment]
我的意思是。试试从3.0.0到哪个具体的版本才有这个问题的。我好去排查

**Comment by xiao-cao-x** [comment]
我之前有提到过这个问题 你给我关闭了 #351
后来我又看到了个一样的问题 #355 解决方法: `gaplessPlayback设置成ture`

**Comment by xiao-cao-x** [comment]
@zmtzawqlp 4.0.0就有这个问题 可以在我的旧项目上重现

**Comment by xiao-cao-x** [comment]
在我的新项目上无法重现 可能是因为代码优化(之前没用`flutter_lints` 代码里一堆多余的Container 用了之后把大部分Container改成了SizedBox和Padding小部分删除)了

旧项目代码像这样代码像这样
```
Container(
      child: StaggeredGridView.countBuilder(
        shrinkWrap: true,
        physics: NeverScrollableScrollPhysics(),
        crossAxisCount: 2,
        itemCount: _illusts.length,
        staggeredTileBuilder: (index) => StaggeredTile.fit(1),
        itemBuilder: (BuildContext context, int index) {
            return Card(....);
        }
)
```

**Comment by xiao-cao-x** [comment]
> StaggeredGridView.countBuilder( shrinkWrap: true,
> 
> 看到这个就脑壳大

这个是以前刚开始用flutter的时候写的..

**Comment by zmtzawqlp** [comment]
你找到是哪个版本开始有问题的吗？ 最好是提供一个能重现的demo。。说不定，你写法就有问题。。

**Comment by xiao-cao-x** [comment]
> 你找到是哪个版本开始有问题的吗？ 最好是提供一个能重现的demo。。说不定，你写法就有问题。。

写的确实不对 但是3.0.0用那个错误的写法都没问题(4.0.0开始有问题)
后来重构了 用新版本也没那个问题
