### ISSUE TITLE
Image zoom (refresh) stops just after updating to ^5.1.1

### ISSUE THREAD

**Issue by a-v-ebrahimi** [fluttercandies/extended_image#404]
I am using extended_image for a while, the zoom functionality by double-tap or mouse wheel was working properly, but by just upgrading to 5.1.1 ( from 4.2.1 ) it stopped refreshing after double-tap or scrolling the mouse wheel.
Am I missing something? There is no migration guide ...

**Comment by zmtzawqlp** [comment]
you can't zoom image by double tap/ mouse wheel?

**Comment by a-v-ebrahimi** [comment]
No, I can't.

**Comment by zmtzawqlp** [comment]
check 5.1.2 later pls
