### ISSUE TITLE
Image editor flipX and flipY should be inverted

### ISSUE THREAD

**Issue by FRANIAZA** [fluttercandies/extended_image#406]
Hi,
In your image editor example in the cropImage function you have the following code:
```dart
if (editAction.needFlip) {
      late Flip mode;
      if (editAction.flipY && editAction.flipX) {
        mode = Flip.both;
      } else if (editAction.flipY) {
        mode = Flip.horizontal;
      } else if (editAction.flipX) {
        mode = Flip.vertical;
      }
      ...
}
```
But this is very counterintuitive and misleading.
editAction.flipX == true should correspond to Flip.horizontal and
editAction.fflipY == true should correspont to Flip.vertical.

As you can see in the cartesian plane the X axis is always the horizontal one, and the Y axis is the vertical one.

![cartesian-coordinate-system-plane-0-260nw-1149181886](https://user-images.githubusercontent.com/26068515/135462951-01e86456-c23b-4294-8dec-0a313fd97c3d.jpg)

It's just a detail but it took me hours to find out why my code wasn't working.

**Comment by zmtzawqlp** [comment]
flip is refer to raw image

**Comment by zmtzawqlp** [comment]
and Flip  mode is design by https://github.com/brendan-duncan/image
