### ISSUE TITLE
Compilation Failed 5.1.0

### ISSUE THREAD

**Issue by moseskarunia** [fluttercandies/extended_image#409]
<details>
  <summary>Error Log</summary>

  

> : Error: Type 'GestureLongPressDownCallback' not found.
>     final GestureLongPressDownCallback? onLongPressDown;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   
>   : Error: Type 'GestureLongPressCancelCallback' not found.
>     final GestureLongPressCancelCallback? onLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: Type 'GestureLongPressDownCallback' not found.
>     final GestureLongPressDownCallback? onSecondaryLongPressDown;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: Type 'GestureLongPressCancelCallback' not found.
>     final GestureLongPressCancelCallback? onSecondaryLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: Type 'GestureLongPressDownCallback' not found.
>     final GestureLongPressDownCallback? onTertiaryLongPressDown;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: Type 'GestureLongPressCancelCallback' not found.
>     final GestureLongPressCancelCallback? onTertiaryLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   
>   : Error: Superclass has no method named 'dispose'.
>       super.dispose();
>             ^^^^^^^
>   : Error: 'GestureLongPressDownCallback' isn't a type.
>     final GestureLongPressDownCallback? onLongPressDown;
>   
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: 'GestureLongPressCancelCallback' isn't a type.
>   
>     final GestureLongPressCancelCallback? onLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: 'GestureLongPressDownCallback' isn't a type.
>     final GestureLongPressDownCallback? onSecondaryLongPressDown;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: 'GestureLongPressCancelCallback' isn't a type.
>     final GestureLongPressCancelCallback? onSecondaryLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: 'GestureLongPressDownCallback' isn't a type.
>     final GestureLongPressDownCallback? onTertiaryLongPressDown;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: 'GestureLongPressCancelCallback' isn't a type.
>     final GestureLongPressCancelCallback? onTertiaryLongPressCancel;
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: The setter 'onLongPressDown' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onLongPressDown'.
>               ..onLongPressDown = onLongPressDown
>                 ^^^^^^^^^^^^^^^
>   : Error: The setter 'onLongPressCancel' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onLongPressCancel'.
>               ..onLongPressCancel = onLongPressCancel
>                 ^^^^^^^^^^^^^^^^^
>   : Error: The setter 'onSecondaryLongPressDown' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onSecondaryLongPressDown'.
>               ..onSecondaryLongPressDown = onSecondaryLongPressDown
>                 ^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: The setter 'onSecondaryLongPressCancel' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onSecondaryLongPressCancel'.
>               ..onSecondaryLongPressCancel = onSecondaryLongPressCancel
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: The setter 'onTertiaryLongPressDown' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onTertiaryLongPressDown'.
>               ..onTertiaryLongPressDown = onTertiaryLongPressDown
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: The setter 'onTertiaryLongPressCancel' isn't defined for the class 'LongPressGestureRecognizer'.
>   - 'LongPressGestureRecognizer' is from 'package:flutter/src/gestures/long_press.dart' ('../../../../fvm/versions/2.2.1/packages/flutter/lib/src/gestures/long_press.dart').
>   Try correcting the name to the name of an existing setter, or defining a setter or field named 'onTertiaryLongPressCancel'.
>               ..onTertiaryLongPressCancel = onTertiaryLongPressCancel
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^
>   : Error: No named parameter with the name 'delta'.
>             delta: delta,
>             ^^^^^
>   : Error: No named parameter with the name 'supportedDevices'.
>             supportedDevices: supportedDevices,
>             ^^^^^^^^^^^^^^^^
>   : Error: No named parameter with the name 'supportedDevices'.
>             supportedDevices: supportedDevices,
>             ^^^^^^^^^^^^^^^^
>   
>   FAILURE: Build failed with an exception.
>   
>   * Where:
>   Script '/Users/moseskarunia/fvm/versions/2.2.1/packages/flutter_tools/gradle/flutter.gradle' line: 1035
>   
>   * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
>   > Process 'command '/Users/moseskarunia/fvm/versions/2.2.1/bin/flutter'' finished with non-zero exit value 1
>   
>   * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>   
>   * Get more help at https://help.gradle.org
>   
>   BUILD FAILED in 31s
>   Exception: Gradle task assembleDebug failed with exit code 1
>   Exited (sigterm)

</details>

<details>
  <summary>Versions</summary>

  ```
  environment:
    sdk: '>=2.13.1 <3.0.0'
    flutter: 2.2.1
  
  dependencies:
    extended_image: 5.1.0
  ```
</details>

**Comment by zmtzawqlp** [comment]
5.0.0 only work for flutter sdk 2.5.0
