### ISSUE TITLE
When image is zoomed, is it possible to give the image padding between the edge of the screen, similar to twitter?

### ISSUE THREAD

**Issue by mark8044** [fluttercandies/extended_image#417]
When image is zoomed, is it possible to give the image padding between the edge of the screen, similar to twitter?

In the twitter app, when you have an image zoomed, there is some space between the edge of the image and the screen edge, which allows you to inspect the edge details of an image

Is this possible here?  Can we define how much 'padding' there would be between the image and the edge of the screen when zoomed

**Comment by zmtzawqlp** [comment]
Padding(child:Image) ? does it not work?

**Comment by mark8044** [comment]
> Padding(child:Image) ? does it not work?

Sort of yes Sort of no

```
itemBuilder: (context, pos) {
                  final nextMedia = _thisMediaList[pos];
                  return Padding(
                    padding: const EdgeInsets.all(20.0),
                    child: ExtendedImage.network(
                      nextMedia.url,
...
```

This creates padding around the image, which will maintain when the image is zoomed.  However when the image is first loaded it is now loaded with a large padding around it also

if we change it to 

```
padding: (_isZoomed) ? const EdgeInsets.all(20.0) : const EdgeInsets.all(0.0),
```

this is also bad because as you zoom, the image jumps as the padding is added into real time

**Comment by moffatman** [comment]
I agree. It would make it better to deal with iPhone notch as well. The additional padding would be at image painting step, rather than around the image widget.

**Comment by zmtzawqlp** [comment]
It looks good at my side, if i add following code, please check whether is it work for you
```dart
SafeArea(child: ClipRect(child: image),)  
```

**Comment by moffatman** [comment]
@zmtzawqlp When you have that approach, the border is outside of the zooming image widget, so you always have a border around all sides. See my approach in #509 to match expected behavior, the border will only be there if you have panned the image to that edge.
