### ISSUE TITLE
ExtendedImage.network headers don't work in web app (Chrome)

### ISSUE THREAD

**Issue by artempal** [fluttercandies/extended_image#419]
Hello!
I am using the following code:
```
ExtendedImage.network(
                    url,
                    headers: {"token":token },
                    cache: true
                  )
```
It's work in android app, but don't work in web app (headers are not applied).

In CachedNetworkImageProvider lib it can be fixed by adding `imageRenderMethodForWeb` parameter:
```
CachedNetworkImageProvider(
                   url,
                   headers: {"token":token},
                   imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet),
              )
```
How can I fix this in ExtendedImage lib?

Thanks.

**Comment by zmtzawqlp** [comment]
you can use CachedNetworkImageProvider .  ExtendedImage(CachedNetworkImageProvider())

**Comment by artempal** [comment]
@zmtzawqlp . it's works for me, thank you.

**Comment by ciccioska** [comment]
Thanks @zmtzawqlp for the answer, to complete the answer for newbie this is the final version:

> `ExtendedImage(
>         image: CachedNetworkImageProvider(url,
>             headers: {"token": "token"},
>             imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet));`
