### ISSUE TITLE
how to set badCertificateCallback 

### ISSUE THREAD

**Issue by wuwenbo5** [fluttercandies/extended_image#42]
加载不出来https的图片，证书不被信任，这改怎么解决？
有没有入口给client设置badCertificateCallback 参数

**Comment by zmtzawqlp** [comment]
？？  官方的能加载吗？？ 没听说过这个种？

**Comment by zmtzawqlp** [comment]
请引用最新的http_client_helper : 0.2.1
你可以这样设置badCertificateCallback
![image](https://user-images.githubusercontent.com/16477333/63141553-b7fbee80-c018-11e9-88a6-b26cca9e7235.png)

图片缓存使用的这个库，请求，所以你这样写就好了

**Comment by zmtzawqlp** [comment]
还有什么问题。可以加群问

**Comment by zmtzawqlp** [comment]
``` dart    
HttpClient http = HttpClient();
    http.badCertificateCallback =
        (X509Certificate cert, String host, int port) {
      return true;
    };
    HttpClientHelper().set(IOClient(http));
```

**Comment by zmtzawqlp** [comment]
in new version, you should do as following:   
``` dart
 HttpClient client = ExtendedNetworkImageProvider.httpClient as HttpClient;
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) {
      return true;
    };
```

**Comment by zmtzawqlp** [comment]
reopen,  peopele can find it quickly

**Comment by zbyJade** [comment]
请问您是如何解决的ExtendedImage.network加载https图片的问题
我配置了证书不起作用呢
![image](https://user-images.githubusercontent.com/16379906/91957004-0a00d680-ed38-11ea-97f1-dca918465905.png)

**Comment by zmtzawqlp** [comment]
你是什么版本。。后续版本才是这样写的，前面版本是按照前面的写法

**Comment by YaoShuwei** [comment]
小菜鸟前来挖坟，请问现在是怎么设置的，我这样设置无效
![image](https://user-images.githubusercontent.com/17966298/116099005-1f1ee100-a6de-11eb-9ead-421209590dd2.png)

**Comment by zmtzawqlp** [comment]
> 小菜鸟前来挖坟，请问现在是怎么设置的，我这样设置无效
> ![image](https://user-images.githubusercontent.com/17966298/116099005-1f1ee100-a6de-11eb-9ead-421209590dd2.png)

这是之前版本的设置方式，你看完整个issue哦

HttpClient client = ExtendedNetworkImageProvider.httpClient as HttpClient;
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) {
      return true;
    };

**Comment by YaoShuwei** [comment]
> > 小菜鸟前来挖坟，请问现在是怎么设置的，我这样设置无效
> > ![image](https://user-images.githubusercontent.com/17966298/116099005-1f1ee100-a6de-11eb-9ead-421209590dd2.png)
> 
> 这是之前版本的设置方式，你看完整个issue哦
> 
> HttpClient client = ExtendedNetworkImageProvider.httpClient as HttpClient;
> client.badCertificateCallback =
> (X509Certificate cert, String host, int port) {
> return true;
> };

我是沙雕，已经看到上面有此设置方式了，谢谢法佬
