### ISSUE TITLE
请问ExtendedResizeImage为什么无法按照指定尺寸解码图片呢？

### ISSUE THREAD

**Issue by ManInTheWind** [fluttercandies/extended_image#425]
感谢法老大大，感谢这个非常棒的插件！

问题描述：
原生的ResizeImage可以通过指定宽高进行解码，如图
![image](https://user-images.githubusercontent.com/32859126/144384316-b1b71b06-9950-4fd3-8ae1-65beb859b94c.png)

我看到ExtendedResizeImage用户与原生没什么差别，但是为什么ExtendedResizeImage为什么无法按照指定尺寸解码图片呢？如图
![image](https://user-images.githubusercontent.com/32859126/144383705-2d389c24-c1ca-429e-aca1-fdbdc4eaaea6.png)

而在load方法里确实也按照传递过去宽高进行解码，但实际上解码出来的还是原尺寸
![image](https://user-images.githubusercontent.com/32859126/144383945-8fd26b35-ed11-4c7d-b4b2-27e80c59e9f1.png)

不知道是我用法有问题还是ExtendedResizeImage没有按照指定尺寸解码

**Comment by ManInTheWind** [comment]
并且还有就是直接这样用provider的话，缓存能力似乎也不起作用了。可以看到控制台上imageCache 为 null

**Comment by zmtzawqlp** [comment]
根据条件有优先顺序。你可以更进一步查看代码

**Comment by ManInTheWind** [comment]
有留意到这个判判断
![image](https://user-images.githubusercontent.com/32859126/144395172-2caa5752-bf28-4961-8c81-66a1c263ceca.png)

但是我直接用ExtendedResizeImage也没有按照这个尺寸解码哦
![image](https://user-images.githubusercontent.com/32859126/144395320-0448b421-463b-48ac-bdf1-b84cbe167ecf.png)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image_library/blob/f05275bb812102f960bbfbefb5a0b4d831795b8c/lib/src/extended_resize_image_provider.dart#L193

**Comment by zmtzawqlp** [comment]
<img width="421" alt="截屏2021-12-02 下午5 39 42" src="https://user-images.githubusercontent.com/16477333/144396498-8211d707-7f68-459d-b6e3-60aacf6c5cab.png">
你设置了几个条件。肯定只会按照某个优先级来处理嘛。

**Comment by ManInTheWind** [comment]
好的，我明白了。感谢🙏
