### ISSUE TITLE
Render problem when resize web page

### ISSUE THREAD

**Issue by kiszewski** [fluttercandies/extended_image#427]
Sometimes when resize the page, some images get blurred or full black. This happens with asset or network images, i'm running flutter web on master channel with version 2.6.0-12.0.pre.931.

Examples:
![unknown](https://user-images.githubusercontent.com/53118132/145232098-166955dc-abfd-4650-a2d5-ce3ba0a1c6a2.png)
![image](https://user-images.githubusercontent.com/53118132/145232676-0c3da289-58e8-4fac-a9f7-fc011480566b.png)

**Comment by zmtzawqlp** [comment]
Image.network is work good? it's just issue for ExtendedImage.network?

**Comment by kiszewski** [comment]
No, image.network is not working too, this is a canvaskit issue, if I use web-renderer html works fine too, any suggestions to keep using canvaskit?

> Image.network is work good? it's just issue for ExtendedImage.network?

**Comment by zmtzawqlp** [comment]
sorry, i have no idea for now, may be you should open issue for flutter team
