### ISSUE TITLE
MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by OmgKevin** [fluttercandies/extended_image#43]
请问在我的flutter_module中包含有extended_image插件的使用，然后将flutter_module嵌套进iOS原生项目里，运行时控制台在运行到使用到缓存图片的地方时打印如下信息 ，flutter: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

**Comment by zmtzawqlp** [comment]
请自己手动加入插件，ios上面好像现在只能手动加入。。。具体请百度一下

**Comment by lihui2333** [comment]
你这个错误很正常 仔细按照谷歌的文档你这个pod install 没把插件搞进去仔细看招谷歌文档来 再者不推荐这种集成方式

**Comment by OmgKevin** [comment]
> 请自己手动加入插件，ios上面好像现在只能手动加入。。。具体请百度一下

我仔细排查了一下我的原生项目，发现当含有extended_image插件的flutter_module编入原生项目时。会自动的在Pods ->Development Pods->FlutterPluginRegistrant->GeneratedPluginRegistrant.m类里自动添加过了一行代码
  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
您说的手动加入插件指的是啥呀

**Comment by zmtzawqlp** [comment]
@lihui2333 你不是每次手动弄的吗?

**Comment by OmgKevin** [comment]
> 你这个错误很正常 仔细按照谷歌的文档你这个pod install 没把插件搞进去仔细看招谷歌文档来 再者不推荐这种集成方式
在执行pod install的时候，除了iOS原生的三方库，已经是将path_provider加进来了的啊

xingkunkun:SunLands admin$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `../flutter_module/.ios/Flutter/engine`
Fetching podspec for `FlutterPluginRegistrant` from `../flutter_module/.ios/Flutter/FlutterPluginRegistrant`
Fetching podspec for `flutter_module` from `../flutter_module/.ios/Flutter`
Fetching podspec for `path_provider` from `../flutter_module/.ios/Flutter/.symlinks/path_provider/ios`
Fetching podspec for `shared_preferences` from `../flutter_module/.ios/Flutter/.symlinks/shared_preferences/ios`
Downloading dependencies
Using AFNetworking (3.2.1)
Using BRPickerView (2.2.1)
Using FCUUID (1.3.1)
Using Flutter (1.0.0)
Using FlutterPluginRegistrant (0.0.1)
Using IQKeyboardManager (6.2.0)
Using MBProgressHUD (1.1.0)
Using MJExtension (3.0.15.1)
Using MJRefresh (3.1.15.7)
Using Masonry (1.1.0)
Using SDWebImage (4.4.5)
Using UICKeyChainStore (2.1.2)
Using UMCAnalytics (6.0.2)
Using UMCCommon (2.0.0)
Using UMCSecurityPlugins (1.0.6)
Using flutter_module (0.0.1)
Using path_provider (0.0.1)
Using pop (1.0.12)
Using shared_preferences (0.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 18 dependencies from the Podfile and 19 total pods installed.

**Comment by OmgKevin** [comment]
> 你这个错误很正常 仔细按照谷歌的文档你这个pod install 没把插件搞进去仔细看招谷歌文档来 再者不推荐这种集成方式

我现在就是严格按照谷歌的文档进行操作的，8月份文档更新，我本地也有更新了集成方式的
1.官方文档 ：https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
   1.1 官方文档更新 https://github.com/flutter/flutter/wiki/Upgrading-Flutter-added-to-existing-iOS-Xcode-project

**Comment by lihui2333** [comment]
注册插件了吗

**Comment by OmgKevin** [comment]
> 注册插件了吗

手动注册 这个extended_image插件 ？没有啊，不知道怎样去注册。。。

**Comment by zmtzawqlp** [comment]
注册path_provider

**Comment by lihui2333** [comment]
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

**Comment by OmgKevin** [comment]
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

这块写了的。项目里面的AppDelegate.m文件里的注册形式是 
  self.flutterEngine = [[FlutterEngine alloc] initWithName:@"io.flutter" project:nil];
  [self.flutterEngine runWithEntrypoint:nil];
  [GeneratedPluginRegistrant registerWithRegistry:self.flutterEngine];

**Comment by OmgKevin** [comment]
> https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps

点击进入registerWithRegistry方法里，代码如下
  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
  [FLTSharedPreferencesPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTSharedPreferencesPlugin"]];

**Comment by OmgKevin** [comment]
> 注册path_provider

原生项目里注册  [FLTSharedPreferencesPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTSharedPreferencesPlugin"]];了啊

**Comment by OmgKevin** [comment]
> 注册path_provider

原生项目里注册  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
了啊

**Comment by lihui2333** [comment]
你在delagate里面注册插件这个engine 是单例？你在flutterviewctrl 里面用的engine是appdelagate里面的engine？不是的话肯定报错啊 没必要在appdelagete 加任何代码删掉 你在哪个在你自己的flutetrctrl 里面把这些代码加上去就行 flutterctrl的engine 没不要自己创建flutterviewctrl 初始化的时候自带引擎

**Comment by lihui2333** [comment]
多多百度

**Comment by OmgKevin** [comment]
> 你在delagate里面注册插件这个engine 是单例？你在flutterviewctrl 里面用的engine是appdelagate里面的engine？不是的话肯定报错啊 没必要在appdelagete 加任何代码删掉 你在哪个在你自己的flutetrctrl 里面把这些代码加上去就行 flutterctrl的engine 没不要自己创建flutterviewctrl 初始化的时候自带引擎

谢谢大神，问题已解决
原因：appdelagete里面初始化的engine 并初始化的插件，跟具体flutterctrl里用到的engine不是同一个，所以会导致插件初始化失败
解决方式：在用到flutterctrl时再进行注册插件
 [GeneratedPluginRegistrant registerWithRegistry:self];
