### ISSUE TITLE
flutter 2.8.0  Temporary solution

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/extended_image#430]
fix some bugs
```dart
  extended_image:
    git:
      url: git://github.com/mdddj/extended_image.git
```

**Comment by 601367322** [comment]
dependency_overrides:
  extended_image:
    git:
      url: git://github.com/mdddj/extended_image.git

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/400
