### ISSUE TITLE
Compatibility with Flutter 2.8

### ISSUE THREAD

**Issue by Cavitedev** [fluttercandies/extended_image#434]
There are a lot of problems extending the classes this package has with the latest version of Flutter. You can test it by upgrading your own project.

**Comment by ryanaidilp** [comment]
Same here
![image](https://user-images.githubusercontent.com/43450710/145376411-6486309c-308a-49e1-bb8c-81c0bcec553d.png)

**Comment by mustafa-707** [comment]
same here
```
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional
    arguments: 2 required, 1 given.
        return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
                                                          ^
```

**Comment by phuhung273** [comment]
Same here

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/400
