### ISSUE TITLE
Getting error after update flutter 2.8.0

### ISSUE THREAD

**Issue by furkan1023** [fluttercandies/extended_image#439]
Hi! 
when i try to run my app after flutter update i get these errors

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart(32,11): error GBF4691A2: No named parameter with the name 'delta'. [C:\flutter_projects\healthassistant\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart(339,43): error G4117F63E: Too few positional arguments: 2 required, 1 given. [C:\flutter_projects\healthassistant\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart(46,66): error G4117F63E: Too few positional arguments: 2 required, 1 given. [C:\flutter_projects\healthassistant\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart(54,55): error G4117F63E: Too few positional arguments: 2 required, 1 given. [C:\flutter_projects\healthassistant\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart(101,66): error G4117F63E: Too few positional arguments: 2 required, 1 given. [C:\flutter_projects\healthassistant\build\windows\flutter\flutter_assemble.vcxproj]

![Ekran Alıntısı](https://user-images.githubusercontent.com/49057380/145552638-ed7723db-0a48-4583-9595-4bd7c41de134.PNG)

**Comment by furkan1023** [comment]
it has happened to me because i didnt update this package. I wanted to delete this issue but maybe someone also can forget update package and get these errors . Thanks for migrating to 2.8.0 fast ^^

**Comment by zmtzawqlp** [comment]
2.8 has breaking change, so please update package to 6.0.1
