### ISSUE TITLE
Custom Rotate Image

### ISSUE THREAD

**Issue by hasit-ai** [fluttercandies/extended_image#441]
I would like to rotate the image slightly, through a custom angle (not just 90 degrees clockwise or counterclockwise). This is similar to #204 but without the need to use gestures, as I would put in a slider to change the angle. 

How do I do this? I have tried `EditActionDetails.rotate(...)` but it does not give me the desired results as I don't have access to the private `_layoutRect` in that class. 

Any pointers would be appreciated!

**Comment by zmtzawqlp** [comment]
not support now

**Comment by zmtzawqlp** [comment]
please update to lastest version
