### ISSUE TITLE
Can not import lib after flutter pub get 6.0.1 version

### ISSUE THREAD

**Issue by z234009184** [fluttercandies/extended_image#444]
Can not import lib after flutter pub get 6.0.1 version

**Comment by z234009184** [comment]
flutter version is 2.8.1

**Comment by zmtzawqlp** [comment]
flutter clean, delete .package pubspec.lock

**Comment by z234009184** [comment]
> flutter clean, delete .package pubspec.lock

It doesn't work for me, can't find extended_image in .pub_cache/hosted/pub.dartlang.org/

**Comment by zmtzawqlp** [comment]
read flutter.cn first and use mirror cn

https://flutter.cn/docs/get-started/install

**Comment by z234009184** [comment]
> read flutter.cn first and use mirror cn
> 
> https://flutter.cn/docs/get-started/install

Thanks for your reply, It's work!!
