### ISSUE TITLE
Print error is false but i receive error in crashlytics

### ISSUE THREAD

**Issue by fahdboudakim** [fluttercandies/extended_image#445]
Hello, i have a problem with the packages, i have disabled print error but in debug and in crash report i receive the error bad state. anyone can help me please

code :

Center(
                    child: ExtendedImage.network(
                      url,
                      cache: false,
                      clearMemoryCacheIfFailed: true,
                      enableMemoryCache: false,
                      printError: false,
                      clearMemoryCacheWhenDispose: true,
                      loadStateChanged: (ExtendedImageState state) {
                        switch (state.extendedImageLoadState) {
                          case LoadState.loading:
                            return null;
                          case LoadState.completed:
                            return ExtendedImage.network(
                              url,
                              height: 150,
                              fit: BoxFit.fill,
                              cache: false,
                              clearMemoryCacheIfFailed: true,
                              enableMemoryCache: false,
                              clearMemoryCacheWhenDispose: true,
                            );
                          case LoadState.failed:
                            return Container(
                              height: 0,
                            );
                        }
                      },
                    ),
                  ),

error : 
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Failed to load https://www.xxx.com/images/infor/6192450503335.png  Error thrown Instance of 'ErrorDescription'.

**Comment by zmtzawqlp** [comment]
this is from http lib, we can't handle it

**Comment by GeylanKM** [comment]
@zmtzawqlp  how can't you handle it?? You are calling the http package to retrieve the image so if an error appears in that stage catch it and give us a way to handle it. We receive hundreds of errors in crashlytics cause of that.
