### ISSUE TITLE
I get this error when open ExtendedImage like editor

### ISSUE THREAD

**Issue by ziqq** [fluttercandies/extended_image#446]
![image](https://user-images.githubusercontent.com/20646071/149286487-4e464b5a-6e0d-40db-8e19-638ffa5a3e7c.png)
![image](https://user-images.githubusercontent.com/20646071/149286573-2e6b2559-cde3-41fb-ad70-5834ddb79582.png)

**Comment by zmtzawqlp** [comment]
file:///   use network provider?

**Comment by ziqq** [comment]
> file:/// use network provider?

I don't use network provider, i  use only ExtendedImage.network

**Comment by zmtzawqlp** [comment]
how can you. use ExtendedImage.network to load file:/// ????

**Comment by ziqq** [comment]
> how can you. use ExtendedImage.network to load file:/// ????
I dont use ExtendedImage.network for get image from file, i use ExtendedImage.file for get image from file
I use ExtendedImage.network for get image from internet

**Comment by zmtzawqlp** [comment]
check it by yourself , error log show you use ExtendedImage.network to load file

**Comment by ziqq** [comment]
> check it by yourself , error log show you use ExtendedImage.network to load file

NO. See condition and code bellow. I use **ExtendedImage.file**

<img width="654" alt="Снимок экрана 2022-01-17 в 11 41 50" src="https://user-images.githubusercontent.com/20646071/149727904-16ba2b5a-b2c7-4c45-87fe-2e1b72639f68.png">
