### ISSUE TITLE
Failing to build on web

### ISSUE THREAD

**Issue by AbderraoufKhodja** [fluttercandies/extended_image#447]
flutter build web
ERROR: ld.so: object '/lib/$LIB/liblsp.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

💪 Building with sound null safety 💪

Target dart2js failed: Exception:
lib/ui/pages/profile_screen/open_store_page.dart:107:25:
Error: The argument type 'File/*1*/' can't be assigned to the parameter type
'File/*2*/?'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:extended_image_library/src/_platform_web.dart'
 ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_ima
 ge_library-3.1.0/lib/src/_platform_web.dart').
                  file: File(_logoFile!.path),
                        ^
lib/ui/pages/check_upload_item_page.dart:305:35:
Error: The argument type 'File/*1*/' can't be assigned to the parameter type
'File/*2*/?'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:extended_image_library/src/_platform_web.dart'
 ('../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_ima
 ge_library-3.1.0/lib/src/_platform_web.dart').
                            file: File(
                                  ^
Error: Compilation failed.

Compiling lib/main.dart for the Web...                             21.3s
Exception: Failed to compile application for the Web.

**Comment by AbderraoufKhodja** [comment]
I am failing to build on flutter for the web. extended_image: ^6.0.1
Flutter (Channel stable, 2.8.0, on Ubuntu 18.04.6 LTS 5.4.0-92-generic, locale
    en_US.UTF-8)

**Comment by AbderraoufKhodja** [comment]
Problem solved after careful reading of the message error. I used File from dart.io where it was supposed to be from extended_image package.

**Comment by AbderraoufKhodja** [comment]
I need to open the issue again. Switching imports did not solve the problem.

**Comment by zmtzawqlp** [comment]
i can build ExtendedImage example in 2.8.0, please take care of dart:io

**Comment by zmtzawqlp** [comment]
i can build ExtendedImage example in 2.8.0, please take care of dart:io

**Comment by AbderraoufKhodja** [comment]
I need some guidance then. When I user FIle from dart:io, I get the error mentioned above. But when I use File from ExtendedImage, I am faced with File is an abstract and can't be initiated.

**Comment by zmtzawqlp** [comment]
File in ExtendedImage is mock class, it's just to use to pass dart analyse. you should change the way in web, something like read bytes into memory

**Comment by AbderraoufKhodja** [comment]
Alright understood. Thank you.
