### ISSUE TITLE
save it to my local drive once cropped

### ISSUE THREAD

**Issue by santinet28** [fluttercandies/extended_image#448]
Hello,

I am trying to crop an image from my gallery and once it is cropped, save it to my local drive. I have followed the examples but I am not able to do it.

This is how I capture the image and modify it

`
    return Center(
      child: ExtendedImage.file(
        File(_pathFoto),
        fit: BoxFit.contain,
        mode: ExtendedImageMode.editor,
        extendedImageEditorKey: _editorKey,
        enableMemoryCache: true,
        cacheRawData: true,
        initEditorConfigHandler: (state) {
          return EditorConfig(
            maxScale: 8.0,
            cropRectPadding: EdgeInsets.all(20.0),
            hitTestSize: 20.0,
            //  cropAspectRatio: 1,
          );
        },
      ),
    );
`

I understand that once the image is recorded in the raw, it must be recorded, but I am unable.

Thanks for the help

**Comment by dzero1** [comment]
Hope this will helps you: https://github.com/fluttercandies/extended_image/blob/master/example/lib/common/utils/crop_editor_helper.dart

**Comment by zmtzawqlp** [comment]
please check [crop_editor_helper.dart](https://github.com/fluttercandies/extended_image/blob/master/example/lib/common/utils/crop_editor_helper.dart)
