### ISSUE TITLE
将本地图片缓存到url

### ISSUE THREAD

**Issue by 1203556555** [fluttercandies/extended_image#449]
使用场景
本地选择一张图片，上传后获得url，我想将本地图片根据url缓存，后面加载图片就可以直接从缓存读取，不需要去下载。

希望能有和cache_network_image一样通过CacheManager().putFile(url, file);

**Comment by ManInTheWind** [comment]
cacheKey 写你的url不就行了吗

**Comment by zmtzawqlp** [comment]
你可以用 CacheManager 做一个 image provider

**Comment by xd-jeff** [comment]
求个例子
