### ISSUE TITLE
请问那个版本时没有ImageStreamListener的？

### ISSUE THREAD

**Issue by god-long** [fluttercandies/extended_image#45]
'ImageStreamListener' isn't defined for the class '_ExtendedImageState'.
     - '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart'

**Comment by zmtzawqlp** [comment]
flutter sdk 1.5.4  到1.7.8 有重大api变更，你是多少版本的

**Comment by god-long** [comment]
> flutter sdk 1.5.4 到1.7.8 有重大api变更，你是多少版本的

flutter 1.1.2版本

**Comment by zmtzawqlp** [comment]
![image](https://user-images.githubusercontent.com/16477333/63309199-82ad1480-c328-11e9-8530-280a142d19ec.png)
试试0.5.1 你的这个版本也太老了。。然后对应的extended image libary也要 改下。

**Comment by god-long** [comment]
谢谢，我试下，😁，主要是依赖的其它库，没有适配Flutter高版本
