### ISSUE TITLE
Issue with zoom

### ISSUE THREAD

**Issue by JSBmanD** [fluttercandies/extended_image#451]
When you set in the EditorConfig maxScale param - you can zoom image one time after another more than it's set.

Steps:
1. Set maxScale to some number
2. Start zoom in and out
3. After some time image will be zooming more than maxScale is set

https://www.upload.ee/files/13886636/video_2022-02-14_13-45-46.mp4.html

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/646c3f04701125598e0458babeb3a3e0634079d1/lib/src/gesture/utils.dart#L401
