### ISSUE TITLE
ExtendedImage out of container

### ISSUE THREAD

**Issue by Johann673** [fluttercandies/extended_image#465]
Hi, 
I use ExtendedImage with editor mode and i try to limit the height of the widget in a Container().
It work great, but when i make a zoom on the picture, the picture go out of the container.

For exemple, this is my widget with a maxHeight : 
![image](https://user-images.githubusercontent.com/6461852/160859143-2b9ab7d0-b3fa-4ee2-a274-8089668c1e0d.png)

When a make a small zoom, it's always ok : 
![image](https://user-images.githubusercontent.com/6461852/160859313-0119bae3-6d6e-4845-9104-c981eb0e0e89.png)

But for a big zoom, the picture go out the container : 
![image](https://user-images.githubusercontent.com/6461852/160859447-babe6441-07b3-4e3d-baea-96d223e9becd.png)

I use the last version of this library : 6.0.2+1

This is a small code to reproduce : 
```
class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<ExtendedImageEditorState> _editorKey =
      GlobalKey<ExtendedImageEditorState>();
  late ImageProvider _provider;

  @override
  void initState() {
    super.initState();
    _provider = ExtendedNetworkImageProvider('https://picsum.photos/300/600');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Container(
          constraints: const BoxConstraints(maxHeight: 400),
          child: ExtendedImage(
            image: _provider,
            extendedImageEditorKey: _editorKey,
            mode: ExtendedImageMode.editor,
            fit: BoxFit.contain,
            initEditorConfigHandler: (ExtendedImageState? state) {
              return EditorConfig(
                maxScale: 8.0,
                cropRectPadding: const EdgeInsets.all(15.0),
                hitTestSize: 20.0,
                cropAspectRatio: null,
              );
            },
          ),
        ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}
```

Any idea what is wrong ? 

Thank you.

**Comment by dzero1** [comment]
I have the same problem. As a quick fix I wraped this using ClipRect

```
ClipRect(
            clipBehavior: Clip.hardEdge,
            child: ExtendedImage(...)
)
```

**Comment by shiweibsw** [comment]
@dzero1 It works for me!
