### ISSUE TITLE
ExtendedImage.network 内存泄漏，导致OOM

### ISSUE THREAD

**Issue by eshopclound** [fluttercandies/extended_image#468]
`ExtendedImage.network(
      Utils.imageToWebp(url),
      width: width,
      height: height,
      fit: fit ?? BoxFit.contain,
      scale: scale,
      cacheHeight: height != null ? (height! * scale).toInt() : null,
      cacheWidth: width != null ? (width! * scale).toInt() : null,
      enableMemoryCache: false,
      compressionRatio: 0.5,
      maxBytes: 1,
    )`
compressionRatio：0.1 可以极大延缓此问题，但是图片失真严重。长列表加载较大图片，内存会一直上涨，图片下载时使用阿里oss进行了裁剪，图片为webp格式，加载几页后内存会一直上涨，随后导致OOM，请大佬帮忙看一下
extended_image版本为4.2.0 由于公司flutter sdk版本较老，最新版本 编译不过

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/9c49ae4259033d9c485ce32d3393df53bd8b9f5b/lib/src/extended_image.dart#L536
