### ISSUE TITLE
ExtendedImageSlidePage滑动生硬

### ISSUE THREAD

**Issue by QuantumSuperPositionCat** [fluttercandies/extended_image#469]
ExtendedImage.network被ExtendedImageSlidePage包住后，当 mode = ExtendedImageMode.gesture 时滑动非常难受，如果滑动速度慢根本slide out不了。但mode = ExtendedImageMode.none 时就非常顺滑。
flowing is the code :
[code.zip](https://github.com/fluttercandies/extended_image/files/8532904/code.zip)

**Comment by zmtzawqlp** [comment]
请运行官方demo
