### ISSUE TITLE
安卓集成flutter，遇到崩溃问题，

### ISSUE THREAD

**Issue by hua407035000** [fluttercandies/extended_image#47]
您好，情况是这样的我安卓项目通过aar形式集成flutter，
 我flutter项目，中加入您的库，集成之后项目就崩溃，跑不起来，去掉您的库就可以。 
单独跑flutter 项目，这个项目有您的库是没问题的。
可能我的表达能力不好，如果作者有兴趣的话，可以联系我，我吧当时的情况和项目演示一下。我的QQ是 407035000

**Comment by zmtzawqlp** [comment]
path_provider库 加进去了吗？ 我也是做混合开发的，打成aar，没遇到你说的问题

**Comment by hua407035000** [comment]
> path_provider
这个库要加？  我仅仅只是想加载一个网络图片，使用作者的extended_image的库，还得加上这个库吗

**Comment by hua407035000** [comment]
> path_provider库 加进去了吗？ 我也是做混合开发的，打成aar，没遇到你说的问题

我刚看了下项目 path_provider: ^1.2.0  是有加的

**Comment by zmtzawqlp** [comment]
不是项目。。是aar里面有没有，或者说你的maven库里面有没有
，你不做处理，，这个是不会自动添加到maven里面去的，你不是在群里的吗。。干嘛跑这里来聊天。。

**Comment by zmtzawqlp** [comment]
path_provider 是用来做本地缓存的，我只是猜测你的原因

**Comment by hua407035000** [comment]
加了很多群，不太清楚您在哪个群，这个path这个库，我像extend image这个库一样的操作方式，依赖在flutter项目里，然后打成arr文件，然后就报错了，报错确实是找不到path这个插件，但是这个插件我按照稳定依赖的，不清楚是否依赖错了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zmtzawqlp <notifications@github.com>
发送时间: 2019年8月23日 21:56
收件人: fluttercandies/extended_image <extended_image@noreply.github.com>
抄送: hua407035000 <407035000@qq.com>, Author <author@noreply.github.com>
主题: 回复：[fluttercandies/extended_image] 安卓集成flutter，遇到崩溃问题， (#47)




path_provider 是用来做本地缓存的，我只是猜测你的原因

**Comment by hua407035000** [comment]
不好意思加了很多群不知道哪个你在。。。我是按照你的文档集成的，



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zmtzawqlp <notifications@github.com>
发送时间: 2019年8月23日 17:51
收件人: fluttercandies/extended_image <extended_image@noreply.github.com>
抄送: hua407035000 <407035000@qq.com>, Author <author@noreply.github.com>
主题: 回复：[fluttercandies/extended_image] 安卓集成flutter，遇到崩溃问题， (#47)




不是项目。。是aar里面有没有，或者说你的maven库里面有没有
 ，你不做处理，，这个是不会自动添加到maven里面去的，你不是在群里的吗。。干嘛跑这里来聊天。。

**Comment by zmtzawqlp** [comment]
https://juejin.im/post/5cd51f61f265da039c056e39

**Comment by zmtzawqlp** [comment]
https://juejin.im/post/5d668d0e6fb9a06add4e3f35
