### ISSUE TITLE
Only fade image in when loading from network (not on rebuild)

### ISSUE THREAD

**Issue by mark8044** [fluttercandies/extended_image#471]
Using the example provided https://github.com/fluttercandies/extended_image/blob/978092941fbe5e241221ba885f88263d3344c51b/README.md an image can be faded in using `FadeTransition` in the `LoadState.completed`:

```
case LoadState.completed:
        _controller.forward();
        return FadeTransition(
          opacity: _controller,
          child: ExtendedRawImage(
            image: state.extendedImageInfo?.image,
            width: ScreenUtil.instance.setWidth(600),
            height: ScreenUtil.instance.setWidth(400),
          ),
        );
        break;
```

However, the problem is that the image will always fade in even if the image is being retrieved from cache or when the page is being rebuilt.  This creates a fade effect every time the page is rebuilt adding unnecessary flickers.

Is it possible to only have the `FadeTransition` run when the image is retrieved from the network only and not when its coming from cache or being rebuilt?

In the documents it says 
```
loadStateChanged is not only for network, if your image need long time to load, you can set enableLoadState(default value is true for network and others are false) to true
```
The way Im reading this is that loadState is happening on network but not for local image, but in practice the `LoadState.completed` is always running

**Comment by gamcho3** [comment]
I have same problem. How can i solve it?

**Comment by zmtzawqlp** [comment]
return AnimatedOpacity(
      child: child,
      opacity: frameNumber == null ? 0 : 1,
      duration: const Duration(seconds: 1),
      curve: Curves.easeOut,
    );

try this

**Comment by zmtzawqlp** [comment]
if state.wasSynchronouslyLoaded is true, you don't need FadeTransition 
``` dart 
if (state.wasSynchronouslyLoaded) {
       return state.completedWidget;
 }
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/commit/d24600b5fbd4e68a4cd34eaf8ac9ce67319874c7

**Comment by gamcho3** [comment]
> [d24600b](https://github.com/fluttercandies/extended_image/commit/d24600b5fbd4e68a4cd34eaf8ac9ce67319874c7)

How can I show images in girdView without loading?

**Comment by zmtzawqlp** [comment]
> > [d24600b](https://github.com/fluttercandies/extended_image/commit/d24600b5fbd4e68a4cd34eaf8ac9ce67319874c7)
> 
> How can I show images in girdView without loading?

read readme
