### ISSUE TITLE
Image get centered while page scroll and image flooded over the boundary

### ISSUE THREAD

**Issue by dzero1** [fluttercandies/extended_image#472]
First thing first. Thanks for the amazing plugin. I really like this. While I using this, I got 2 major problems as I mentioned in the title.

1. Image get always centered while scrolling the page after zoom/marked the corp aread
2. Image flooded over the widget area. As a quick fix I wrap this using ClipRect. So this can be a late fix.

From here you can see the problem: https://youtube.com/shorts/oOlPxPAHBrU
Here is the flutlab sandbox to try it out : https://flutlab.io/sandbox/ae79da37-d20c-4327-8921-309106553975

**Comment by zmtzawqlp** [comment]
1. as design 2.please use ClipRect if it's not fullscreen
