### ISSUE TITLE
Show error widget only when all retries are done

### ISSUE THREAD

**Issue by yadaniyil** [fluttercandies/extended_image#473]
Is there a way to not show the error widget until all the retries are done?
I have something like this:

```
return ExtendedImage.network(
      imageUrl,
      retries: 50,
      timeLimit: Duration(seconds: 10),
      timeRetry: Duration(milliseconds: 100),
      loadStateChanged: (ExtendedImageState state) {
        switch (state.extendedImageLoadState) {
          case LoadState.loading:
            return CupertinoActivityIndicator();
          case LoadState.failed:
            state.reLoadImage();
            return errorWidgetFinal;
        }
        return null;
      },

```
and I want loading indicator to spin 50 * 100ms = 5 seconds when the retries are in progress. If the image is loaded successfully after e.g. 2 seconds, show the image but not loading.

**Comment by zmtzawqlp** [comment]
switch (state.extendedImageLoadState) {
          case LoadState.loading:
            return CupertinoActivityIndicator();
          case LoadState.failed:
          SchedulerBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                   state.reLoadImage();
          });
    
           return CupertinoActivityIndicator();
        }

**Comment by zmtzawqlp** [comment]
or      ExtendedImage.network(,retries: 3,timeRetry: ,)

**Comment by yadaniyil** [comment]
Thanks, my helicopter solution was to increment the index each reload until the index equals the retries time. And it worked :)
