### ISSUE TITLE
同时设置ExtendedImageSlidePage和mode: ExtendedImageMode.gesture，滑动会出现卡顿

### ISSUE THREAD

**Issue by supercq123** [fluttercandies/extended_image#475]
我运行了demo,在demo上slide_page_demo.dart文件中加上mode: ExtendedImageMode.gesture后，
demo上也会出现这个问题。我看了一下在5.1.3版本上是可以流畅滑动的，是不是升级flutter2.8后去掉了gesture_detector.dart和scale.dart这两个文件导致的。

**Comment by zmtzawqlp** [comment]
不能重现

**Comment by shenjingfs** [comment]
Flutter: 3.3.8 
当前版本的demo中的photoView点开大图后滑动退出时可复现

看起来也是一样的问题：#518 #529
