### ISSUE TITLE
* thread #17, name = 'io.worker.6', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=3072 MB, unused=0x0)

### ISSUE THREAD

**Issue by wds1181977** [fluttercandies/extended_image#480]
ios  listView loadmore 超500张图片 crash，android过长也有oom,请问有优化方案吗 使用6.0.3版本，

`* thread #17, name = 'io.worker.6', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=3072 MB, unused=0x0)
    frame #0: 0x0000000107940d50 Flutter`neon::store_8888(unsigned long, void**, unsigned long, unsigned long, float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4], float vector[4]) + 132
Flutter`neon::store_8888:
->  0x107940d50 <+132>: str    q16, [x8]
    0x107940d54 <+136>: add    x8, x1, #0x10
    0x107940d58 <+140>: ldr    x4, [x1, #0x8]
    0x107940d5c <+144>: mov    x1, x8
Target 0: (Runner) stopped.`

`[✓] Flutter (Channel unknown, 2.5.3, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/wds/Library/flutter
    • Upstream repository unknown
    • Framework revision 18116933e7 (7 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wds/Library/Android/sdk
    • Platform android-272, build-tools 31.0.0
    • ANDROID_HOME = /Users/wds/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart`

           `ExtendedImage(
                      height: height,
                      width: width,
                      fit: fit ?? BoxFit.cover,
                      image: ExtendedResizeImage(
                        ExtendedNetworkImageProvider(
                          icon,
                        ),
                        compressionRatio: 0.9,
                        maxBytes: null,
                      ),
                      loadStateChanged: (ExtendedImageState state) {
                        Widget loader = const SizedBox.shrink();
                        switch (state.extendedImageLoadState) {
                          case LoadState.loading:
                            loader = placeholderWidget ??
                                (isMarket
                                    ? SkeletonItems(
                                        width: width, height: height)
                                    : loadAssetsImage(
                                        placeholder,
                                        fit: fit == null ? BoxFit.cover : fit,
                                        width: width,
                                        height: height,
                                      ));
                            break;
                          case LoadState.failed:
                            loader = errorWidget ??
                                (!showDefault && isMarket
                                    ? Container(
                                        width: width,
                                        height: height,
                                        decoration: new BoxDecoration(
                                          color: Global.kTheme.bg1,
                                          borderRadius: BorderRadius.all(
                                              Radius.circular(radius ?? 4)),
                                        ),
                                      )
                                    : loadAssetsImage(
                                        placeholder ?? 'default_error_image',
                                        fit: fit == null ? BoxFit.cover : fit,
                                        width: width,
                                        height: height,
                                      ));
                            break;

                          case LoadState.completed:
                            loader =
                                RepaintBoundary(child: state.completedWidget);
                            break;
                        }
                        return loader;
                      },
                      clearMemoryCacheIfFailed: true,
                      clearMemoryCacheWhenDispose: true,
                      enableMemoryCache: false,
                      enableLoadState: false,
                    )`

**Comment by zmtzawqlp** [comment]
看 readme

**Comment by wds1181977** [comment]
readme里并没有解决方案

**Comment by zmtzawqlp** [comment]
<img width="694" alt="截屏2022-05-12 下午4 15 59" src="https://user-images.githubusercontent.com/16477333/168024565-17c3cad5-7528-4290-891f-5101fc74a0b2.png">
<img width="1111" alt="截屏2022-05-12 下午4 16 20" src="https://user-images.githubusercontent.com/16477333/168024618-7aadaa36-c7ca-4c21-8821-e673d44ef438.png">

**Comment by wds1181977** [comment]
不是 ExtendedImage 问题
