### ISSUE TITLE
Allow hitTestSize to be 0

### ISSUE THREAD

**Issue by ivansemkin** [fluttercandies/extended_image#485]
Hello! I am using an `ExtendedImageMode.editor` version of this widget to crop a profile picture in my app. I am using a custom round (circle) `cropLayerPainter`, hence I need to disable the ability to resize cropLayer by dragging corners.

However, when I set `hitTestSize` to 0, an assert throws an error. Please, make `hitTestSize >= 0` so that it's possible to disable hit test altogether. 
https://github.com/fluttercandies/extended_image/blob/d24600b5fbd4e68a4cd34eaf8ac9ce67319874c7/lib/src/editor/editor_utils.dart#L388

**Comment by zmtzawqlp** [comment]
I will changed it if it has not any breaking change

**Comment by ivansemkin** [comment]
@zmtzawqlp I tested it, it has no breaking changes. It can be zero, but it should not go below zero. So >= is ok
