### ISSUE TITLE
Is it possible to do a irregular polygon crop?

### ISSUE THREAD

**Issue by gfb-47** [fluttercandies/extended_image#487]
I would like to crop non-rectangle images for scanning like this:

(it is not easy to see, but the user can do a irregular polygon there)

![Screen Shot 2022-06-10 at 13 46 36](https://user-images.githubusercontent.com/46033500/173113574-813134bb-2771-4dce-8816-915e6b76a882.png)

Is it possible?

**Comment by zmtzawqlp** [comment]
it should not be refer to this package
