### ISSUE TITLE
设备旋转后图片位置错误（未居中）

### ISSUE THREAD

**Issue by tgcasce** [fluttercandies/extended_image#489]
具体步骤：
1. 先进行缩放，缩小，等待动画自动恢复scale：1.0
2. 设备旋转，此时图片不居中

import 'package:flutter/material.dart';
import 'package:extended_image/extended_image.dart';

import '../../utils/resources_util.dart';

class HeroImagePreviewWidget extends StatefulWidget {
  const HeroImagePreviewWidget({
    Key? key,
    required this.tag,
    required this.provider,
  }) : super(key: key);

  final String tag;
  final ImageProvider<Object> provider;

  @override
  State<HeroImagePreviewWidget> createState() => _HeroImagePreviewWidgetState();
}

class _HeroImagePreviewWidgetState extends State<HeroImagePreviewWidget>
    with TickerProviderStateMixin {
  /// 双击缩放的动画控制器
  late final AnimationController doubleTapAnimationController;

  /// 双击缩放的动画曲线
  late final Animation<double> doubleTapCurveAnimation;

  /// 双击缩放的动画
  Animation<double>? doubleTapAnimation;

  /// 双击缩放的回调
  late VoidCallback doubleTapListener;

  @override
  void initState() {
    super.initState();
    doubleTapAnimationController = AnimationController(
      duration: const Duration(milliseconds: 200),
      vsync: this,
    );
    doubleTapCurveAnimation = CurvedAnimation(
      parent: doubleTapAnimationController,
      curve: Curves.easeInOut,
    );
  }

  @override
  void dispose() {
    super.dispose();
    doubleTapAnimationController
      ..stop()
      ..reset()
      ..dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox.expand(
      child: GestureDetector(
        onTap: _dismissPreview,
        behavior: HitTestBehavior.opaque,
        child: ExtendedImage(
          image: widget.provider,
          fit: BoxFit.contain,
          mode: ExtendedImageMode.gesture,
          onDoubleTap: _updateDoubleTapAnimation,
          initGestureConfigHandler: (ExtendedImageState state) {
            return GestureConfig(
              initialScale: 1.0,
              minScale: 1.0,
              maxScale: 4.0,
              animationMinScale: 0.6,
              animationMaxScale: 5.0,
              cacheGesture: false,
              inPageView: true,
            );
          },
          loadStateChanged: (ExtendedImageState state) {
            Widget loader;
            switch (state.extendedImageLoadState) {
              case LoadState.completed:
                loader = state.completedWidget;
                break;
              default:
                loader = Image.asset(
                  assetImagePath('im_default_picture_loading.png'),
                  fit: BoxFit.contain,
                );
                break;
            }
            return loader;
          },
        ),
      ),
    );
  }

  void _updateDoubleTapAnimation(ExtendedImageGestureState state) {
    final double begin = state.gestureDetails!.totalScale!;
    final double end = state.gestureDetails!.totalScale! == 1.0 ? 4.0 : 1.0;
    final Offset pointerDownPosition = state.pointerDownPosition!;

    doubleTapAnimation?.removeListener(doubleTapListener);
    doubleTapAnimationController
      ..stop()
      ..reset();
    doubleTapListener = () {
      state.handleDoubleTap(
        scale: doubleTapAnimation!.value,
        doubleTapPosition: pointerDownPosition,
      );
    };
    doubleTapAnimation = Tween<double>(
      begin: begin,
      end: end,
    ).animate(doubleTapCurveAnimation)
      ..addListener(doubleTapListener);
    doubleTapAnimationController.forward();
  }

  void _dismissPreview() {
    Navigator.of(context).maybePop();
  }
}

视频：
https://user-images.githubusercontent.com/9710553/174578733-59829e45-79b2-4f9c-82e9-6a65a7b3dda7.MP4

**Comment by tgcasce** [comment]
> 不支持横屏

奇怪的是刚开始进去横屏位置是对的，只不过缩小一下还原后，旋转横屏位置就错位了

**Comment by zmtzawqlp** [comment]
就没有考虑横屏的计算
