### ISSUE TITLE
怎样下载加密图片并解密

### ISSUE THREAD

**Issue by xiaopigpig** [fluttercandies/extended_image#492]

**Comment by xiaopigpig** [comment]
https://github.com/fluttercandies/extended_image/issues/116 这个issue 不可以，新版的ExtendedNetworkImageProvider is abstract

**Comment by zmtzawqlp** [comment]
你要继承 。io 下面的。而且不是 abstract 的

**Comment by TrueloveSomeGIRl** [comment]
> 你要继承 。io 下面的。而且不是 abstract 的

继承不了呀 最新版
