### ISSUE TITLE
【Proposal提议】【Nested PageView】 支持嵌套多个ExtendedImageGesturePageView

### ISSUE THREAD

**Issue by huntrist** [fluttercandies/extended_image#493]
不知是否能支持做到嵌套多个ExtendedImageGesturePageView

使用场景如下：
有多组图片
上下滑动切换组
左右滑动在当前组内切换图片

但是希望上下左右的滑动翻页都能和ExtendedImage本身的缩放联动
即在图片放大的情况下优先以动图片本身，只有到边界了再做对应的翻页。

现在的ExtendedImageGesturePageView只支持一层，嵌套后的外层并不能和最内部的ExtendedImage联动。

如果短期内没有支持的计划，不知道大佬们有没有什么实现的思路可以提供或参考？

**Comment by zmtzawqlp** [comment]
没有计划，这涉及到手势冲突，你上下滚动 和上下手势冲突。你得想办法 让上下左右手势不冲突
