### ISSUE TITLE
Error: The class 'File' is abstract and can't be instantiated.

### ISSUE THREAD

**Issue by AreejNour** [fluttercandies/extended_image#499]
I tired to use ExtendedImage.file widget and it doesn't behave the same on web and mobile, as the application run in right way on mobile and failed to compile on web

this is my code example

`ExtendedImage.file(
                  File(widget.pickedImage!.path),
                  width: 140.r,
                  height: 140.r,
                  matchTextDirection: true,
                  filterQuality: FilterQuality.high,
                  loadStateChanged: onStateChanged,
                )`
                
version:
  extended_image: ^6.0.1
  
 run command:
 flutter run -d chrome --web-renderer html  --no-sound-null-safety

**Comment by zmtzawqlp** [comment]
File is not support on Web
