### ISSUE TITLE
闪烁问题

### ISSUE THREAD

**Issue by IT-crackpot** [fluttercandies/extended_image#502]
使用ExtendedImage.asset时，键盘的弹出会导致图像闪烁

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/985ce26abfb72b1d9c0a0e0adb3630479ff83583/lib/src/extended_image.dart#L773

**Comment by q2564063** [comment]
> https://github.com/fluttercandies/extended_image/blob/985ce26abfb72b1d9c0a0e0adb3630479ff83583/lib/src/extended_image.dart#L773

为什么系统组件Image.asset，gaplessPlayback设置true或false都不会闪烁
