### ISSUE TITLE
当上滑显示更多信息，在更多信息中有textfield，当聚焦键盘弹出时图片会移动然后复位。

### ISSUE THREAD

**Issue by xikeqian** [fluttercandies/extended_image#503]
尝试设置过Scaffold 的 resizeToAvoidBottomInset为false无效，版本6.2.1

**Comment by zmtzawqlp** [comment]
你应该让布局顶上去，请参考 https://github.com/fluttercandies/extended_text_field/blob/master/example/lib/pages/complex/text_demo.dart

**Comment by xikeqian** [comment]
布局顶上去一样的会出现那种情况

**Comment by xikeqian** [comment]
![Simulator Screen Recording - iPhone 13 - 2022-09-15 at 13 57 35](https://user-images.githubusercontent.com/39973278/190325892-60b54f1d-4efa-479a-9075-efae764d0e8c.gif)
