### ISSUE TITLE
Too few positional arguments: 4 required, 3 given.

### ISSUE THREAD

**Issue by lijianqiang12** [fluttercandies/extended_image#508]
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/extended_image-6.2.1/lib/src/gesture/page_view/widgets/scroll_activity.dart:56:12: Error: Too few positional arguments: 4 required, 3 given.
  ) : super(
           ^

FAILURE: Build failed with an exception.

Flutter 3.1.0-0.0.pre.2343 • channel master • https://github.com/flutter/flutter.git
Framework • revision 97b574b09b (35 minutes ago) • 2022-08-17 21:11:27 -0400
Engine • revision 32d8c521da
Tools • Dart 2.19.0 (build 2.19.0-108.0.dev) • DevTools 2.16.0

**Comment by zmtzawqlp** [comment]
update it after stable

**Comment by Story5** [comment]
遇到同样的问题了,怎么处理?

**Comment by zmtzawqlp** [comment]
3.3.0 is released, but nothing change for this

**Comment by lijianqiang12** [comment]
Thanks
