### ISSUE TITLE
-[MTLDebugDevice newBufferWithLength:options:]:633: failed assertion `Buffer Validation newBufferWith*:length 0x18000000 must not exceed 256 MB.

### ISSUE THREAD

**Issue by Bisond** [fluttercandies/extended_image#514]
iOS 使用很多图的时候直接crash了。有什么方法解决这个问题吗？

**Comment by zmtzawqlp** [comment]
列表记得回收

**Comment by Bisond** [comment]
怎么回收这个，有相关代码没？

**Comment by zmtzawqlp** [comment]
1.  版本信息  2.看readme 3. 看demo

**Comment by alexandranb1** [comment]
Did someone find a solution for this? Let me know. Thank you

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/995556ba98169b04696ea839a0a9731cc305d720/lib/src/extended_image.dart#L541

**Comment by zhangfeixiang** [comment]
clearMemoryCacheWhenDispose: true,
enableMemoryCache: false,

滑动过快的情况下，依然会崩溃，有办法限制或优化这个过程造成的内存问题吗?

**Comment by zmtzawqlp** [comment]
没有遇到过，请提供可以重现的环境和demo

**Comment by zhangfeixiang** [comment]
设备：iPad mini 2  
系统：iOS12.5.5 
场景：因为我们的图片比较大，我们项目的图片是读取的离线资源载入速度挺快的，滑动如果过快大概5下就崩溃了（高性能设备可能会久一些）
复现：ipad mini 2快速滑动几下就崩溃
---------------------------------
extended_image: ^6.1.0
---------------------------------
main.dart
---------------------------------
`import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int current = 0;

  @override
  Widget build(BuildContext context) {
    List list = [
      "https://static.imolacn.com/imola_wxa/gallery/29b4c115c80932731abe2c415a9ec217a1a404b7sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/814c89670cd0d75e27cab16ca755887dde636dfbsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/96446ac4452fc0498f639d867ff935a1d9e5a8ebimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b2d7f34562577b4e656bf21c6a243a9f3779579csipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/565796c9695a6f772d2349b5e7421411f78a1fb2sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d9c0c3f768bc6ffb081dad287450f29686f2e5a5sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1d41550221d5b1e01c86c0a0cac18871a8b5447dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/caeda6a3eaa6eb7825b1d2cfc4ba375e9275476fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/87ef3cc1d879b2408d19806e95e1e6bb6ceccd7fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d4a5ad81abf6a1bfc3ec7fef0dab17841d959123sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/571d9063af1d241988a7b6467820ca0a98195fedsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/6d0fd2ae8b9e91176f72250c26fe59ea9ed23cecsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c23f590de098e408567ec728d456c741750ce4f9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0f5d63d350352d6763922af79235d825536a6629sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/15203fa6885906f1b91359256299aee9ab50a695sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0b80723e255a2e68c4688c45648b58e99edbe9f8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3613eddac424740373f9420130e64570c64ecb65sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c6a37a2b0592c7466c40c43fb78eb0196f51dbd1sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ffc023fa18402c51da80948374971555d30f4207sipsimageoptim",
"https://static.imolacn.com/imola_wxa/gallery/2c56d4754b49b09e06bc3432515db7f660b4e4d3sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3c0d537ad0b9bbc37bcb3ada53ed52a4abcf9edfsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/552a45af348145bc4abbac89945d138d8045b6fasipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e2a725b719ac5aaf12c62e7f23aa0ffcbe0f448bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3cbc9e0a2af63c0825b4728043124ab5594dadb2sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/7bc51a803b3946cfebae7cf2d80a354361ed715dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ab5afcf133542ec06554d24565521e8a559ea7d8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/606abd2a7a8f53561fe153fae7ca3464b5279139sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0bac74985959d046bbc3bfc17262dc29fa356619sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/15533a3f8d2a1b1227d6583dab597eac7bd5d6f0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8591dfc3bd2d5059227ac0a916fb89c664fba504sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9368b91114304a35dc1dc8da17c8e5b5544d6d5bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/062367f9a38d58c489240940d45260b6fb8a378fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/654d456798aaefbbf06e5cf9a13b1f6c314870d5sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e986d9aff81783665172ea706500675dabbd609bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/77b5176d6e6ced2426dc396666b2e7f7d264c219sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/16d39f4609ae8c5a670ac3633ee3b35cb38490desipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0c14009d579eaf232b904ddc161af6c35873c733sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/da771342db14d91d160e451187f62234bcf2076bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e45430e116a12935cb4958d91f247e15e57a3ba1sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/75174394038e9ba20da6d8e0b87ba47c2d4e0035sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/19cdc303e65be3c51ae36728ff7b761d7480eacdsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9d30863210c3de41e0443b5ae4134fdd4adfb724sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c62bc00749c3e6ec94d92c099a8087eafbed0476sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9e5a5ccaa767c70befb0c01dacd11c8c8ed25b0asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/954a65637cb101b4bb1fdaf44f7a14179ba055e8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/fee739a4eb2ab67c28fd3b40a69d1aa82d096494sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b02049cc17ef239876cd2039f2b103e218b5382bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c8764b5b9bac201baf214cad2c656c63c98c0cd0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/aad20d257862d456f52555d46e4fdac7443d9ea5sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9ce9b32f2629fcf85d9f8f44bea5daf92adf660csipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9f32f48d49c329d15475b5d03ea75ff668593fbesipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0552c52a27c900a3e9bd0ff4544b4552b184432asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8047852a1b615f0a27a09ee04e600f54920835e6sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ea2a65d55eb6eff5cbacac9c91e66cb289a46cc1sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1e477e6f436397c1b118b6966bca0e1a30962ed2sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/18f54a25df5cc92ae2d6e2f26331b551c3387aedsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0184f629ad568f9ba64fab84c4ff2f7869b3bf05sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a3b1823bdb6ba0552c0ea329ab7d7e778b198ad4sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ca81d174e1f3edcfac488daa8e40398a4e98e469sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ba465d7d7d5f393bac6ed6d87fed9740d453744dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a1e74fa539d946b9d34666d33f76266b0e56e58bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9d175dd315be03e937c3a4d45d7a5e03d65228acsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9995340ec85bf7e502937777373db64ea313e109sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ba9021e9aa29a0eeac62e8f232da17f472bc7692sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a5cfa8d681b5f9ac29ddf2937e4e2474733c56adsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e6f7b7bc24b460a3ebe3dbcde8f371a387c1fe38sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/7152b5643c6f9f06fb3d082726133e70cee12b2esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8e7aa501a6b62bd1ba0100e4e5c98326daf27526sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a4e035bde7096aad4d390cfce21a307a89d71997sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/51c878c3d90a8797d9d11ec626f115ca95557e5esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/bd741e3c9a8cd7fcb39c431baeddd4d262acaa5esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/31c859d5c30deaf79937fe0817605585154a4004sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/360d42aa47e6e1d0c79c7a664dc9ff62f1f242a0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c77e35387d90d1e05480676af9b73a5d3718e66fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/164fa9191771d88845548d646abcb6b579b48ca3sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b5ea5f924efe6ca576570499b21ac4a4bc34b86dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c1ca96ea346007053d1b673665d0687ac423b021sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/94eb9711ffe14a561bbd62b7a28a6ba5330dbaa2sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/5ac0f9aa7c23b984e76d08b78d491ac8178921dasipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/10ccda097fd70990e904f51c21ae66e2e21cdf49sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1a67c126e48b1ff031a93480a1f5dd891c0a5576sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/10257ea46373ea9dfcc297e19e5b2aff0c7b9484sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d776820e93a803b9119fc4d291ec127acc401838sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/7af7b2b8d71867a25e0c4e20185207a961148b94sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/975f776a89156d72067b21382e4b538794216700sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/6f674ca2dede0a7936678479b5c72678cb9354ecsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d9ec7cdaa8dc4e9331c4f2cfea3ac2fb8c520d5dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1460b86a2c8bd61890fdb28b6a925a757cfedbc3sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a117795b3d6ddfd410f8f73c3d331f9676669b55sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/365ee2f67dd6c26d2230a3fa3bcb1a72746d63a9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b3c1488e68a9b25b94f62616caffc99406c65553sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/55cbdbc6c4a6ed400912fe1b3ed340046821a1f6sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e73fd4427026db796f61c93b464c370ac60d1b30sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/dd3899adf0560f30bfe14da584a039a201993d7csipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d097e41d602efe2b8244a937279153c230f68770sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/40e59e8f27d55a52a8080c47af33fb9950bec9a3sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/51e8f1f9f00c9d9fed13a85aabf07ee0cb51b53fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b4ff7b91fcd20fb9a32adea23f6d4bb96134ac53sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/38826454c208f538d9965bf74137b95fed7aff91sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/cf4568d41dd465bc0bd6370891a5f63d08c08797sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/dcd883b1e00d09aaa3826e6669d6112efd004861sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/85c3bfcadf5eccc7852277781415516029341fc0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d84a2ef06cc73393f81d24889a1f0d58b015d080sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3c1ef90a3c7c8d3db10ab257b10d2f264882e6casipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/30a4c205fa0999c1d8ededd8219a148af455640esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/415b272550eee50146442175fba22aaf59985b52sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e9ac1588a4ac3dad1a62efb03d4d2642f85e7c6eimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1adddcb1ca8f09651ec908fc3adaf7f642ba0aadsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0f9f7ae8619fe3315d6d70cb60e5ab3f6801c9a9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/b08f4f4918a0543e29b8242c7ee53dc09414a424sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8c35c4a89d3e69e4a21919e6d7c35d0bf715255esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/4de4db29c0e2e84937817d6204e432bba000e737sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/742853f1f57c3f5953bf5a2275060d3683fec9f5sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/352372620bb32e3665af3a9fc67e1a7a9db141dbsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d3dfb17265d3a9e9fb90afc6bfa21c0e29730de2sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8b34e094b7d423b80e8af7a69b1e23bc94ee4d4esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a5676ac00cccec92eb1218cd4ceba5eef3690804sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/2e59154e7e831264b7f95fbede2aa949165bad7bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/fc02a7b1ac98cd8d72788a0ed9fe23b5c5b3371asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/5228f7e201c679cc4ab68a174cf479f7043b4895sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/061dc43c2d64cb328998dce348fe2183084bc7fdsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d7584e984140873822fdde5d63aa3d52eb010fa1sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e02d22b8923e54181d8d85dde093b2ad8f3091f0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8e92cf5b3b597b3d8e9e8e83a0a69bfc81152048sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1f7a29ab194bd61a98e92b41930ade3bafe49c7dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/894d11653c1701e40723419b82de0e8dd6f4b13asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/4aebbd4cce80eb3d84131a860e5fe1abd714e551sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0e57e02c93c8c705706caeb13ac2b133d5c94c0esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/eb3db7010d2edfbee03fe9f596e8c661b5f5853csipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d2c774e4e04a7dfcc33bd87f7575ea2037df6cffsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3e5a4853bdb2acb7daa0326197df2dc7c96feaeasipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8c7b5ebf41655b86d8ca2c7069e3c54b6c3bf169imageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/258c8390fd878f1bf888d5ba8f3d676b44a81616imageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/5df038fffee4cb879a21f1960d6df9b06e4d0f4csipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/31af5577094100320a17045eb555326bd69884ccsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/faffc4ccf3635dfd8c1adab4284b101f13afabb8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/7776faaa69ea58d2b55f9471709827afb83e5d92sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0841b9f7db7b268e59651905ed4deab98364588esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d03f10fdc64b613daf5ccf14231afffaf38ddce1sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/41e291955c5e21dec1d70098b5c5683e47b6810fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/2048ffd2a3125703cda87050e96e6582655ea586sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c546e20df834f6cb02c9f5ebc0e4393a2e81cbe8imageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/718936887cb4c54f9cf047087d4cefa977b69089sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ad9775065aa82c9ae9e2b950bb10fa6761846008sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e19c8cf556aa93d6db778ef455d17df4adfa017fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/512787cd3d53929d2bc1c7039f4a618966391a7fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8ab0332103618ca72a362882f6b8712dd7b0eb7asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/f2ae1745e9a21140742f276a986a971bb64dbc50sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/60b68fa20c6066b839190c7e3a767375aece43ecsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/6b13ab3d9967e2f6fc60dab9ae27d210f2244335imageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9da5babcdc024722f94831ec8fcdab830b57cb84sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/f68a6988da028f4b50f79de1df124f7721c8bf89sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8022a148e6b98fec1fa1c95fec0c1bb3f028026cimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/19a899f7e3de4532a9641d75f53b8f3855e69f1eimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/72f35a93b607f74bd607ba326023c6e45879459fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/abad42d58b947c5d78c86f5bf54911f8a6fb1632sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/27dc0fa0251a94df1c5f09f96ea4339b2c209284sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/1bd91f0f1501ca7be0f8ad618168e1df755310d8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/5d610e50fbc0f16a7ada78b905fb6f80230beacesipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/90d67cd1b84534a64fe59ca829514cfe4e164444sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8e83cd4e5436ddb1b2f9bb2065d6e9a1fb9698d0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/c176bc3137572dd171f7b9522b765ccaf0bb79efsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a3b491c6dda3da88f5e152fde1ff582bbb193f61sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/0695d5c9ba431fa906568c63068f54426e471e96sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/249425f019c78ce4decaab9915ee33ca5940c222sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/81789448611fe532f2fd19e67394823339129c01sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/175d13d9491045964f77507f4af4e4d31956aff4sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ebd1209fc1b9b1a16bf75173b891506de3f2c817sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e46dffe5217712b78551f4a5345af66144831ba3sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/894f09604fb3a53acb7ffa5a0766c435b4d092b9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/5cf2270befd0f45b6fb68fd4924cf409518063b9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/229870a921553170340541d38b75ab1e4e44831fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d454a6d5970e75c773e5d1907c6777d9f2979d03sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/f92f6fdc9f0672646754e8fbd0c6b54692b89f4esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/9e6e38dda518c4f18468a6d031f749a0f6219458sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d45d60161106deb6c48157d1cd7941322cad609dsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/19fb8b55c470d39e2301171360a45cb7678e8669sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a59be865c0689d9231c060f5f5e37213391809b0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/ecf8e5766793c88fe95903cd1f33c43bfe784194sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/d78b524743aa7e249d6b7f12d812b0c18f1ac8e4sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/a36a0f0e6f3e3ca6da1d9d5550512ae75bd9dd6fimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/06c4146a11bdb31b0be2f526dfc70f7b3aff8c18sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/8cc8bff1fc1952c04576225f0d06e67da3f4807bsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/38c2b8b77b52ff1638bf9823df08e3914745de8fsipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/3a4e90401dc921a8cf908aadc2da6b217a2c8cf8sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/89ee1d22e478821a224d26a8d857e6f53cbd1765sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/30504bb6c4601c1ff690ceba3d4c7bcd2764f165sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/903279e7f431aedfbfbb62fa0c10adf25190226asipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/34db6e761f6c8ebd5efeadb7ec10955f4a36e5e0sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/e7ee0ff8819509b95b217a1d663660a2a479787esipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/253f82c6c8e459735e7d01d92b70fde9846927a9sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/7645540e1373ca1ce75de48ed10f5bc1fab53e78sipsimageoptim",
      "https://static.imolacn.com/imola_wxa/gallery/026fc09246a543cdabe4cd8fa092128826237823sipsimageoptim"
    ];
    ExtendedPageController pageController = ExtendedPageController();
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text('${current + 1}/${list.length}'),
      ),
      body: ExtendedImageGesturePageView.builder(
        itemCount: list.length,
        controller: pageController,
        scrollDirection: Axis.horizontal,
        onPageChanged: (int index) {
          setState(() {
            current = index;
          });
        },
        itemBuilder: (BuildContext context, int index) {
          var cover = list[index];
          // initialScale|minScale<=1时会出现无法切换的情况
          GestureConfig gestureConfig = GestureConfig(
            minScale: 1.0001,
            maxScale: 3.5,
            animationMinScale: 1,
            animationMaxScale: 3.6,
            speed: 1.0,
            inertialSpeed: 100.0,
            initialScale: 1.0001,
            inPageView: true,
            initialAlignment: InitialAlignment.center,
          );
          return ExtendedImage(
              image: ExtendedNetworkImageProvider(
                // 如本地不存在，案例默认加载大图，产品加载缩略图
                cover,
              ),
              mode: ExtendedImageMode.gesture,
              clearMemoryCacheWhenDispose: true,
              initGestureConfigHandler: (state) {
                return gestureConfig;
              });
        },
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


`

**Comment by zhangfeixiang** [comment]
flutter: flutter-2.11-candidate.10

**Comment by zmtzawqlp** [comment]
列表的图片。请压缩，没有哪家公司会这样做
