### ISSUE TITLE
ExtendedImageGesturePageView 在键盘事件触发时会左右滑动

### ISSUE THREAD

**Issue by tangbl93** [fluttercandies/extended_image#516]
问题描述：
SDK版本：extended_image: ^6.3.0
描述：在 ExtendedImageGesturePageView 中 itemCount 大于0 时，同时在 showModalBottomSheet 弹出有输入框时。当键盘呼出与隐藏时，会自动左右滑动。

演示视频：
![2022-09-16 11 53 23](https://user-images.githubusercontent.com/13956214/190553195-334b68d1-7a22-4a7e-98e0-5ec5ebe2907e.gif)

演示工程源码
[test_extended_image_app.zip](https://github.com/fluttercandies/extended_image/files/9580546/test_extended_image_app.zip)

**Comment by zmtzawqlp** [comment]
check whether is fixed at your size with https://github.com/fluttercandies/extended_image/commit/995556ba98169b04696ea839a0a9731cc305d720

**Comment by tangbl93** [comment]
Thanks, it has been fixed.

**Comment by zmtzawqlp** [comment]
release it later.
