### ISSUE TITLE
Problem with ExtendedImageSlidePage when gesture mode is enabled on ExtendedImage

### ISSUE THREAD

**Issue by Alwein** [fluttercandies/extended_image#518]
Trying the example's photoView, I've got a problem when opening any image : slide out animation is kind of jerky

I've experienced this issue on Web and IOS.

Steps to reproduce : simply run the example provided with this package and go to > complex > photoView and try to open and slide out any image.

Note : online example is working well on my side

**Comment by Alwein** [comment]
Any update ?

**Comment by zmtzawqlp** [comment]
demo set    ` slideAxis: SlideAxis.vertical,` , so maybe you want to slide at horizontal. and demo has add slide bottom to show bottom widget
``` dart 
enum SlideAxis {
  both,
  horizontal,
  vertical,
}
```

**Comment by zmtzawqlp** [comment]
see https://github.com/fluttercandies/extended_image/commit/1332576def5b31164ee2d64532b8b3d28d954451 whether fix your problem

**Comment by Alwein** [comment]
works as expected, thanks 👍
