### ISSUE TITLE
demo Drag and drop the picture（拖拽图片困顿）

### ISSUE THREAD

**Issue by tiangaopan** [fluttercandies/extended_image#529]
https://user-images.githubusercontent.com/33128981/201526350-f1dff8d4-cafb-400f-a262-d3d0c55ce31b.mp4

**Comment by tiangaopan** [comment]
运行demo后，在这里拖动会有明显的卡顿

**Comment by QuantumStudioOfficial** [comment]
same #469

**Comment by zmtzawqlp** [comment]
close https://github.com/fluttercandies/extended_image/issues/518
