### ISSUE TITLE
希望提供获取本地缓存图片路径的方法

### ISSUE THREAD

**Issue by caoyunxiao** [fluttercandies/extended_image#53]
有一个这样的使用场景，混合开发需要互相传递image video 时，直接传本地路径就好了，传网络路径的话，还要重新下载缓存，如果能共用路径，实际上就相当于共用缓存了。

**Comment by zmtzawqlp** [comment]
欢迎 pr https://github.com/fluttercandies/extended_text_library

**Comment by caoyunxiao** [comment]
![image](https://user-images.githubusercontent.com/15682437/64222034-64870d00-cf01-11e9-90a1-4bf2ad5c2b7b.png)
自己动手丰衣足食
