### ISSUE TITLE
Getting this error while compiling to web Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.

### ISSUE THREAD

**Issue by tanveer1302** [fluttercandies/extended_image#531]
While compiling for web, I am getting this error. This code was working previously and I recently updated extended image version to the latest from 4.1.0 after which this issue cropped if. If I comment out the kIsWeb check and removed ExtendedImage.file code, it works fine for web, but with this check, it fails. Appreciate if anyone can help me out

Error: The argument type 'File/*1*/' can't be assigned to the parameter type
'File/*2*/'.
 - 'File/*1*/' is from 'dart:io'.
 - 'File/*2*/' is from 'package:extended_image_library/src/_platform_web.dart'
 ('../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.4.1/lib/src/_platform_web.dart').

Even though I am checking if it is for web, I am still getting this error. The code is as follow

      `Column(
          children: <Widget>[
            Expanded(
              child: kIsWeb
                  ? ExtendedImage.network(
                      _resetToOriginalImage
                          ? widget.orgImgFile as String
                          : widget.imgFile as String,
                      fit: BoxFit.contain,
                      mode: ExtendedImageMode.editor,
                      extendedImageEditorKey: editorKey,
                      initEditorConfigHandler: (ExtendedImageState? state) {
                        return EditorConfig(
                            maxScale: 8.0,
                            cropLayerPainter: _cropLayerPainter!,
                            cropAspectRatio: _aspectRatio!.value);
                      },
                      cacheRawData: true,
                    )

                  // TODO: this doesn't allow to compile to web. Check if this is resolved in new version of extended image package
                  : ExtendedImage.file(
                      _resetToOriginalImage
                          ? widget.orgImgFile as File
                          : widget.imgFile as File,
                      fit: BoxFit.contain,
                      mode: ExtendedImageMode.editor,
                      enableLoadState: true,
                      extendedImageEditorKey: editorKey,
                      initEditorConfigHandler: (ExtendedImageState? state) {
                        return EditorConfig(
                            maxScale: 8.0,
                            cropLayerPainter: _cropLayerPainter!,
                            cropAspectRatio: _aspectRatio!.value);
                      },
                      cacheRawData: true,
                    ),
            ),
          ],
        ),`

Found another reference for this issue logged in recently https://github.com/dint-dev/universal_io/issues/17#issuecomment-1327377845

Let me know if any more information is needed.

Thanks

**Comment by zmtzawqlp** [comment]
image.dart

``` dart 
export '_image_io.dart'
  if (dart.library.html) '_image_web.dart' ;
```

_image_io.dart

``` dart 
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ExtendedImage.file(
      _resetToOriginalImage
          ? widget.orgImgFile as File
          : widget.imgFile as File,
      fit: BoxFit.contain,
      mode: ExtendedImageMode.editor,
      enableLoadState: true,
      extendedImageEditorKey: editorKey,
      initEditorConfigHandler: (ExtendedImageState? state) {
        return EditorConfig(
            maxScale: 8.0,
            cropLayerPainter: _cropLayerPainter!,
            cropAspectRatio: _aspectRatio!.value);
      },
      cacheRawData: true,
    );
  }
}

```

_image_web.dart

``` dart 
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ExtendedImage.network(
      _resetToOriginalImage
          ? widget.orgImgFile as String
          : widget.imgFile as String,
      fit: BoxFit.contain,
      mode: ExtendedImageMode.editor,
      extendedImageEditorKey: editorKey,
      initEditorConfigHandler: (ExtendedImageState? state) {
        return EditorConfig(
            maxScale: 8.0,
            cropLayerPainter: _cropLayerPainter!,
            cropAspectRatio: _aspectRatio!.value);
      },
      cacheRawData: true,
    );
  }
}

```

import 'image.dart' and use MyWidget.

**Comment by tanveer1302** [comment]
Thanks, it works like a charm.

However, now I am facing another issue with html renderer and created this ticket

https://github.com/fluttercandies/extended_image/issues/546#issue-1571393515
