### ISSUE TITLE
Flutter Web does not support the blend mode: BlendMode.clear

### ISSUE THREAD

**Issue by Cyb0org** [fluttercandies/extended_image#534]
Hi.

Version 6.3.3 introduces drawing editor with BlendMode.clear which is not supported for the flutter web.

Trying to use editor in the latest version produces error:

"Flutter Web does not support the blend mode: BlendMode.clear"

and Editor is unusable.

Version 6.3.2 is of course working fine.

**Comment by zmtzawqlp** [comment]
i  test it on  3.3.9 ,it works nice.

**Comment by zmtzawqlp** [comment]
if you are under this version, please use 6.3.2 instead if

**Comment by gigi** [comment]
Same issue on Flutter 3.7.3

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/545
