### ISSUE TITLE
ExtendedImage.asset唤起、隐藏键盘时，会闪烁

### ISSUE THREAD

**Issue by Marshal-S** [fluttercandies/extended_image#539]
ExtendedImage.asset唤起、隐藏键盘时，会闪烁

**Comment by Marshal-S** [comment]
一个120 x 120 小图片，唤起、隐藏键盘就是闪烁，
flutter 3.3.9，ExtendedImage 6.3.2

**Comment by Marshal-S** [comment]
注意不是主动调用聚焦和取消方法触发的，而是系统键盘弹起和收回自动出现的问题
代码如下所示
ExtendedImage.asset(
          'images/oval_logo.png',
          width: 60,
          height: 60,
        ),

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L783

**Comment by wangzhipeng-vicky** [comment]
> https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L783

这个也不起效   会闪烁

**Comment by wangzhipeng-vicky** [comment]
> https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L783

这个也不起效   会闪烁

**Comment by wangzhipeng-vicky** [comment]
> https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L783

这个也不起效   会闪烁
