### ISSUE TITLE
Cannot compile on latest master

### ISSUE THREAD

**Issue by delfme** [fluttercandies/extended_image#540]
On latest master I get this error. Can you help with this?

Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/extended_image-6.3.4/lib/src/gesture/page_view/widgets/scroll_position.dart:184:15: Error: The method
'ExtendedPagePosition.copyWith' doesn't have the named parameter 'devicePixelRatio' of overridden method 'ViewportOffset with ScrollMetrics.copyWith'.

**Comment by delfme** [comment]
Exact same issue occurs with extended_image-7.0.0-dev.1

**Comment by Alijaaan** [comment]
same error here  , any solution?

**Comment by zmtzawqlp** [comment]
https://pub.dev/packages/extended_image/    7.0.0 is already

**Comment by Alijaaan** [comment]
This problem is exists in 7.0.0 too.
[√] Flutter (Channel master, 3.8.0-4.0.pre.21, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    • Flutter version 3.8.0-4.0.pre.21 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 61f6a0bcd4 (3 hours ago), 2023-02-04 03:08:35 -0500
    • Engine revision c7a4bbab0e
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
    • Pub download mirror https://pub.dev/

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Alijaan\AppData\Local\Android\Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.
