### ISSUE TITLE
Conflicts with Widget Testing

### ISSUE THREAD

**Issue by darwin-morocho** [fluttercandies/extended_image#541]
Hi, great work with this package.

I'm using the next code to show images from network
```dart
ExtendedImage.network(
   'https://somedomain.com/someimage.png,
)
```
But when I run my widget test it fails due to a `pumpAndSettle timeOut`.

Here a minimal reproducible code
```dart
import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets(
    'ExtendedImage',
    (tester) async {
      await tester.pumpWidget(
        const MaterialApp(
          home: DemoPage(),
        ),
      );
      expect(
        find.byType(CircularProgressIndicator),
        findsOneWidget,
      );
      await tester.pumpAndSettle();
      expect(
        find.byType(CircularProgressIndicator),
        findsNothing,
      );
    },
  );
}

class DemoPage extends StatefulWidget {
  const DemoPage({super.key});

  @override
  State<DemoPage> createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  bool _loaded = false;
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback(
      (_) => _load(),
    );
  }

  void _load() async {
    await Future.delayed(
      const Duration(milliseconds: 300),
    );
    if (mounted) {
      setState(() {
        _loaded = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _loaded
          ? ExtendedImage.network(
              'https://www.themoviedb.org/t/p/w440_and_h660_face/q6j9Dn3iiXoCjpVitDppNNZXwVq.jpg',
            )
          : const Center(
              child: CircularProgressIndicator(),
            ),
    );
  }
}

```

How we can use this package with widget testing?

**Comment by zmtzawqlp** [comment]
you can find CircularProgressIndicator by define as;

import 'package:extended_image/extended_image.dart' as extended_image; 

expect(
        find.byType(extended_image.CircularProgressIndicator),
        findsOneWidget,
 );

**Comment by darwin-morocho** [comment]
> you can find CircularProgressIndicator by define as;
> 
> import 'package:extended_image/extended_image.dart' as extended_image;
> 
> expect( find.byType(extended_image.CircularProgressIndicator), findsOneWidget, );

It doesn't have sence we will still the pumpAndsettle time out error because we have an infinite animation with Extended Image by default when we are running a widget testing

**Comment by zmtzawqlp** [comment]
you can use this callback  to override loading widget : https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L628

**Comment by darwin-morocho** [comment]
> you can use this callback to override loading widget :
> 
> https://github.com/fluttercandies/extended_image/blob/d748a866ae7f16a69024b35a3fdfea48ef85400f/lib/src/extended_image.dart#L628

Override the loading animation in every use of ExtendedImage.network is not a good solution because we lost the posibilite to use a custom loader while the image is fetching.  For example if  someone want to use a custom loading animation like a shimmer effect. I posible solution could be have a CacheManager class that we can override in testing. For example in CachedNetworkImage we can use HttpOverrides.runZone to simulate every http request

**Comment by zmtzawqlp** [comment]
in fact, no one will use ExtendedImage directly.  The better way is that  a custom image widget which contains business logic and use ExtendedImage.

**Comment by darwin-morocho** [comment]
> in fact, no one will use ExtendedImage directly. The better way is that a custom image widget which contains business logic and use ExtendedImage.

Create a custom image widget is a bad practice due to is not maintainable if you are working in a team. If a new developer is joined to the team he could omit the use of the custom image widget and then our code will not friendly with testing.

I found a solution to make ExtendendImage.network(...) friendly with testing forcing an error when the cache folder is readed.


```dart
import 'package:path_provider_platform_interface/path_provider_platform_interface.dart';

Future<void> mockNetworkImages(Future<void> Function() test) {
  PathProviderPlatform.instance = MockPathProviderPlatform();
  return test();
}

class MockPathProviderPlatform extends PathProviderPlatform {
  @override
  Future<String?> getTemporaryPath() {
    throw FakeError();
  }
}

class FakeError {
  @override
  String toString() => '';
}
```

the next test will pass
```dart
  testWidgets(
    'Network Image',
    (tester) => mockNetworkImages(
      () async {
            await tester.pumpWidget(
        const MaterialApp(
          home: DemoPage(),
        ),
      );
      expect(
        find.byType(CircularProgressIndicator),
        findsOneWidget,
      );
      await tester.pumpAndSettle();
      expect(
        find.byType(CircularProgressIndicator),
        findsNothing,
      );
      },
    ),
  );
```

**Comment by zmtzawqlp** [comment]
i don't think your test case in right for this case, CircularProgressIndicator is default ExtendedImage loading widget, i don't think it has any problem. A team should be has their own rule to following, you can take a look about custom lint, https://github.com/fluttercandies/candies_analyzer_plugin.

**Comment by darwin-morocho** [comment]
> i don't think your test case in right for this case, CircularProgressIndicator is default ExtendedImage loading widget, i don't think it has any problem. A team should be has their own rule to follow, you can take a look about custom lint,

Currently the only way to make Extended image by default  friendly with testing is using a widget without an infinite animation while the image is fetching. But that is a big limitation of UI and design
