### ISSUE TITLE
ExtendedImage.asset(..) throws a black image on a smartphone

### ISSUE THREAD

**Issue by Lukascoding1** [fluttercandies/extended_image#549]
### Content

When I want to crop an image, I get to the page, but instead of an image, I only see a black area

**Comment by zmtzawqlp** [comment]
i don't know what are you talking about

**Comment by Lukascoding1** [comment]
![image](https://user-images.githubusercontent.com/71288546/219352733-7a9707d3-7887-431e-a8a7-a7a4b25b38c5.png)

**Comment by Lukascoding1** [comment]
On this page I always get a black area instead of a image

**Comment by Lukascoding1** [comment]
However, this error only occurs when I test it on a smartphone

**Comment by zmtzawqlp** [comment]
can you follow the issue template?

**Comment by Lukascoding1** [comment]
What do you mean?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/546    find at the end
