### ISSUE TITLE
ImageStreamListener

### ISSUE THREAD

**Issue by zxszxszxszxs** [fluttercandies/extended_image#55]
报错
- '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart' ('file:///Users/zhengxiaoshan/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.6/lib/src/extended_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
        ImageStreamListener(_handleImageChanged, onError: _loadFailed));

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/45
