### ISSUE TITLE
[Feature request] Provide controller for the ExtendedImageEditorState or state setters to implement Undo/Redo

### ISSUE THREAD

**Issue by ramtinq** [fluttercandies/extended_image#553]
### Platforms

Android, iOS

### Description

I need to add undo redo buttons to my editor.

Tried copying 'editorKey.currentState' in a `_previousState` variable to be able to set the state back to the `_previousState` later. But, there's no state manipulation methods for `currentState` and we can just `get` the `currentState`.

In addition, we can capture `currentState` before flipping and rotating, but **cropping** also needs an `onCropEnd` callback to be able to update the `_previousState` with the newly cropped version.

### Why

To provide history / undo / redo functionality for my editor.

**Comment by zmtzawqlp** [comment]
please update to lastest version
