### ISSUE TITLE
7.0.2 Required named parameter 'devicePixelRatio' must be provided.

### ISSUE THREAD

**Issue by wolf-leo** [fluttercandies/extended_image#557]
### Version

7.0.2

### Platforms

iOS

### Device Model

iPhone14PM

### flutter info

```sh
lastversion
```

### How to reproduce?

这个问题在7.0.2还是没解决吗？

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/37436228/225949982-cf8210b4-415a-4658-be46-afebac32c10a.png">

<img width="809" alt="image" src="https://user-images.githubusercontent.com/37436228/225949762-e96c6b3f-21c9-473e-9b23-50c1fda053df.png">

**Comment by zmtzawqlp** [comment]
只支持 stable

**Comment by gslender** [comment]
Flutter 3.9.0-0.2.pre • channel beta which is about to become 3.10 stable very soon continues to have this change that hasn't yet been resolved. Is it possible that a change can be made to accomdoate for this so that testing on the beta channel can begin for apps that use extended_image

**Comment by zmtzawqlp** [comment]
The versions to fit beyond flutter 3.10.0 are updated, please reload your local version.
