### ISSUE TITLE
能否支持双指缩放过程中不调整图片位置居中，缩放完了才居中，感觉这样体验好些，类似于抖音选择本地图片

### ISSUE THREAD

**Issue by liuguicen** [fluttercandies/extended_image#558]
### Platforms

dart

### Description

然后还需要一个处理，就是缩放过程中图片跟随两指中心移动。
另外，也可以参考美图秀秀等P图APP，它们是这样的。

这样图片会显得很跟手，用户相放大观察的点不会因为对齐而跳走。

**Comment by zmtzawqlp** [comment]
暂时没有计划
