### ISSUE TITLE
Precache the next network image

### ISSUE THREAD

**Issue by csacchetti** [fluttercandies/extended_image#560]
I cannot find a way to precache next network image when I am looking at the images individually using gestures to switch between them. This would avoid waiting times, especially when the images are high definition.
Thank you for this extraordinary package

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/6ca24b7386d221ecfcb0092bbe19ae22195b1f4a/lib/src/gesture/page_view/gesture_page_view.dart#L50
