### ISSUE TITLE
[How to use] 下载的代码运行不起来是什么原因呢？好多代码都提示报错。

### ISSUE THREAD

**Issue by taozhixiang** [fluttercandies/extended_image#561]
### Platforms

dart, Android

### Description

../../../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_text-9.1.2/lib/src/selection/extended_text_selection.dart:151:7: Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:
 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../../SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1163:8: Context: 'TextInputClient.didChangeInputControl' is defined here.
  void didChangeInputControl(TextInputControl? oldControl, TextInputControl? newControl) {}
       ^^^^^^^^^^^^^^^^^^^^^
../../../../../SDK/flutter/packages/flutter/lib/src/services/text_input.dart:1184:8: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by zmtzawqlp** [comment]
请根据 changelog 找到自己适配的 版本
