### ISSUE TITLE
[Bug report] This package will stop working on the upcoming stable 3.10 release 

### ISSUE THREAD

**Issue by gslender** [fluttercandies/extended_image#563]
### Version

7.0.1

### Platforms

dart, Android, iOS, macOS, Web, Windows, Linux

### Device Model

any

### flutter info

```sh
Flutter 3.9.0-0.2.pre • channel beta
```

### How to reproduce?

Flutter 3.9.0-0.2.pre • channel beta which is about to become 3.10 stable is removing API that was marked deprecated in the earlier Flutter versions. Very soon this package will stop working on the stable release because no effort is being made to remove deprecated API.

Is it possible that changes can be made to accomdoate for this so that testing on the beta channel can begin for apps that use extended_image - my initial checks would suggest nothing is breaking by fixing the API used to ensure they match the change method signatures.

**Comment by ps6067966** [comment]
Yes, I can confirm. 
This package is causing issue in master channel.

**Comment by gslender** [comment]
Stable 3.10 release candidate has been released and yep, this package is breaking. All other packages I used (over 30 of them) have made changes BEFORE and removed deprecated API, but unsure why this package's author is reluctant to do something proactive and fix things before it breaks. My only solution is to fork and make the changes myself. Took only 15 mins and surprising that the author isn't willing to help in that way - is there any reason why you're not looking into this?

**Comment by gslender** [comment]
This is the set of minor changes needed

https://github.com/lhengl/extended_image/commit/08c613002d70bb06f18d2722907909674bf24daa

**Comment by eerive** [comment]
Flutter 3.10 stable just went live, please consider approving #572

**Comment by AliSattar95** [comment]
Flutter 3.10 stable is live, please approve https://github.com/fluttercandies/extended_image/pull/572

**Comment by qflbai** [comment]
作者能发个版本吗，等米下锅呀。

**Comment by zmtzawqlp** [comment]
8.0.0 is ready on pub.
