### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by Eriickson** [fluttercandies/extended_image#570]
### Version

7.0.2

### Platforms

Android

### Device Model

Samsung Galaxy s22 ultra 

### flutter info

```sh
at the time of starting the project, the following errors are displayed and the project does not start

I tried to downgrade to a lower version, I read some issues related to this, but I couldn't find a solution

I'm not even using the package, with the simple fact of adding the import line, the bug is already detected
```

### How to reproduce?

![image](https://user-images.githubusercontent.com/38663299/236576899-615e881c-b170-40cf-b99f-c0f72efb1c20.png)

**Comment by zmtzawqlp** [comment]
flutter --version.  and check changelog

**Comment by Eriickson** [comment]
This is a response: 
![image](https://user-images.githubusercontent.com/38663299/236624134-946e6840-57ac-4bb2-b35f-e4adde0989e0.png)

**Comment by zmtzawqlp** [comment]
only support stable

**Comment by Eriickson** [comment]
I should download this versión? 

[SmartSelect_20230507_212406_Chrome.jpg](https://user-images.githubusercontent.com/38663299/236714292-69df5d2c-c98d-437e-9c5d-31f819c42849.jpg)

**Comment by eerive** [comment]
@Eriickson you can use this package with any flutter 3.7.
flutter 3.10 has just been deployed to stable and there is already a PR #572 in the pipeline which will hopefully get approved soon - then you can upgrade flutter to 3.10

**Comment by zmtzawqlp** [comment]
8.0.0 is ready on pub.
