### ISSUE TITLE
loadStateChanged 方法如何正确使用

### ISSUE THREAD

**Issue by zjyhll** [fluttercandies/extended_image#571]
### Platforms

Android

### Description

当前页面有大量图片时（比如100张），跳转到第二个页面时（即离开当前页面）loadStateChanged方法会执行100次，再返回图片页面时，又会执行100次，我看到一些问题解决方案中使用   if (state.wasSynchronouslyLoaded) {return state.completedWidget;}来避免在completed中加载动画，但我此时并不想让程序再进入loadStateChanged中，也就是根本不需要刷新已经加载出来的图片，不然这200次回调会消耗大量内存

### My code

ExtendedImage.network(
            url,
            width: width.r,
            height: height.r,
            fit: BoxFit.cover,
            cache: true,
            // border: Border.all(color: themeColor.withAlpha(10), width: 2.0),
            shape: BoxShape.rectangle,
            borderRadius: BorderRadius.all(Radius.circular(borderRadius.r)),
            clearMemoryCacheWhenDispose: true,
            loadStateChanged: (ExtendedImageState state) {
          print('loadStateChanged:${state.extendedImageLoadState}');
          switch (state.extendedImageLoadState) {
            case LoadState.completed:
              if (state.wasSynchronouslyLoaded) {
                return state.completedWidget;
              }
              // _controller.forward();

              ///if you don't want override completed widget
              ///please return null or state.completedWidget
              //return null;
              return state.completedWidget;
            // return FadeTransition(
            //   opacity: _controller,
            //   child: state.completedWidget,
            // );
            case LoadState.failed:
              return UnconstrainedBox(
                child: SizedBox(
                  // width: 100.r,
                  // height: 80.r,
                  width: widget.placeWidth!.r,
                  height: widget.placeHeight!.r,
                  child: Image.asset(
                    defImagePath,
                    fit: BoxFit.fill,
                  ),
                ),
              );
          }
        }
            )

### Try do it

我按照文档或demo来使用的，不知道问题出在哪里

**Comment by zmtzawqlp** [comment]
200次回调会消耗大量内存 从哪里得出来的？一个页面上面为啥有 100张图片？
