### ISSUE TITLE
How using zoom with extendedImageEditorKey

### ISSUE THREAD

**Issue by Eriickson** [fluttercandies/extended_image#575]
### Platforms

dart, Android, iOS

### Description

How could I use the extendedImageEditorKey to be able to zoom, is there a method such as reset, flip or rotate?

ex: editorKey.currentState!.zoom(1.5);

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/2f0042598f932feaba869a3f6a6b6bd93ff9f76b/example/lib/pages/complex/image_editor_demo.dart#L186
