### ISSUE TITLE
Add BlendMode.clear on HTML web renderer

### ISSUE THREAD

**Issue by ElhamM7518** [fluttercandies/extended_image#578]
### Platforms

Web

### Description

Please add **BlendMode.clear on HTML web renderer** to your package. 

### Why

I want to upgrade the extended_image package on my project, but actually, it can't be possible! Because the higher versions don't support **BlendMode.clear on HTML web renderer** and unfortunately, I currently have to use version 6.3.2!

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/545

you can do as this

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/546#issue-1571393515
