### ISSUE TITLE
[How to use]  ExtendedImage.network error status code

### ISSUE THREAD

**Issue by EmirBashiri** [fluttercandies/extended_image#584]
### Platforms

Android

### Description

Hi 

First off all thank you for this amazing package.
I need access to status code of error any time an error detected in ExtendedImage.network to implement some custom logic.
I've checked code so many time but I can't find anything about access to error status code , so what should I do?

### My code
`ExtendedImage.network(
      url,
      cacheMaxAge: cahceMaxAge,
      fit: fit,
      width: width,
      height: height,
      borderRadius: borderRadius,
      loadStateChanged: (state) {
        return Container(
          color: Colors.amber,
          child: Text(state.lastException.toString()),
        );
      },
    );`

**Comment by zmtzawqlp** [comment]
```
  @override
  Object? get lastException => _lastException;

  @override
  StackTrace? get lastStack => _lastStack;
```

**Comment by zmtzawqlp** [comment]
lastException is the same as error which it give from errorBuilder

**Comment by EmirBashiri** [comment]
> lastException is the same as error which it give from errorBuilder

As I told you earlier I tested the lastException but it's just giving error message and it's not giving the error status code whereas I need the error status code to implement custom logic.

**Comment by zmtzawqlp** [comment]
ExtendedImage and Image are not throw the raw HttpClientResponse code. you can custom your network provider base on your case.

**Comment by EmirBashiri** [comment]
> ExtendedImage and Image are not throw the raw HttpClientResponse code. you can custom your network provider base on your case.

Whenever an httpClient error is detected, Flutter's built-in image widget will throw a Networkloadexception.
Do you have any other solution for this issue?

**Comment by zmtzawqlp** [comment]
> > ExtendedImage and Image are not throw the raw HttpClientResponse code. you can custom your network provider base on your case.
> 
> Whenever an httpClient error is detected, Flutter's built-in image widget will throw a Networkloadexception. Do you have any other solution for this issue?

you can custom your network provider base on your case.

**Comment by EmirBashiri** [comment]
Ok , can you explain in more detail please?
I mean what should I do?

**Comment by EmirBashiri** [comment]
> > > ExtendedImage and Image are not throw the raw HttpClientResponse code. you can custom your network provider base on your case.
> > 
> > 
> > Whenever an httpClient error is detected, Flutter's built-in image widget will throw a Networkloadexception. Do you have any other solution for this issue?
> 
> you can custom your network provider base on your case.


Ok , can you explain in more detail please?
I mean what should I do?

**Comment by zmtzawqlp** [comment]
> > > > ExtendedImage and Image are not throw the raw HttpClientResponse code. you can custom your network provider base on your case.
> > > 
> > > 
> > > Whenever an httpClient error is detected, Flutter's built-in image widget will throw a Networkloadexception. Do you have any other solution for this issue?
> > 
> > 
> > you can custom your network provider base on your case.
> 
> Ok , can you explain in more detail please? I mean what should I do?

Write a Custom ImageProvider .(Copy ExtendedNetworkImageProvider code)
