### ISSUE TITLE
[Bug report] App flickering due to a conflict with flutter master

### ISSUE THREAD

**Issue by delfme** [fluttercandies/extended_image#585]
### Version

8.0.2

### Platforms

iOS

### Device Model

iPhone 13 pro ios 16.1

### flutter info

```sh
[✓] Flutter (Channel master, 3.11.0-18.0.pre.76, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
Run path/to/sdkmanager --install "cmdline-tools;latest"
See https://developer.android.com/studio/command-line for more details.
✗ Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources
```

### How to reproduce?

Found out a conflict between latest master and ExtendedImage that triggers the infamous screen flickering issue on iOS.
Basically flickering is triggered by precaching image with `ExtendedNetworkImageProvider`
A video reproducing the issue is available here: https://github.com/flutter/flutter/issues/128221
I
```
precacheImage(
                  ExtendedNetworkImageProvider(
                    image_url,
                    cache: true,
                    cacheMaxAge: const Duration(days: 2),
                  ),
                  context,
                );
```

### Logs

```sh
No errors thrown by console
```

**Comment by zmtzawqlp** [comment]
Impeller is not good enough, suggest to disable it for now

**Comment by zmtzawqlp** [comment]
@delfme  did this issue fixed?

**Comment by delfme** [comment]
@zmtzawqlp I got to workaround it somehow using `CachedNetworkImage`.
Initially I had issues with both plugins.

Unfortunately, code is closed and I was not able to reproduce the issue by isolating it inside a sample.
Still using ExtendedImage elsewhere where that issue doesn't occur.

**Comment by zmtzawqlp** [comment]
reopen if it still has this problem
