### ISSUE TITLE
[Discussions/Request] Zoom image without double-tap first

### ISSUE THREAD

**Issue by burekas7** [fluttercandies/extended_image#586]
### Content

Hi,

Currently in order to activate the zooming you need to double tap first, 
Is there any way of doing it without the tapping action, so directly by pinching it?

Thanks

**Comment by zmtzawqlp** [comment]
I couldn't get it, it's not necessary

**Comment by burekas7** [comment]
@zmtzawqlp 
What do you mean by "not necessary"?
For me it does. I don't want to need of double-tap in order to enable the zoom option.

**Comment by burekas7** [comment]
You right, I don't know why it didn't work before.
