### ISSUE TITLE
[Discussions] 作者您好，能否在该库中使用类似Android中LruCache的内存管理策略。

### ISSUE THREAD

**Issue by qflbai** [fluttercandies/extended_image#590]

**Comment by zmtzawqlp** [comment]
Cache 可以自己管理

**Comment by zmtzawqlp** [comment]
比如我的需求是清除7天之前的，你自己也可以写自己的策略，文件你都能访问到

**Comment by qflbai** [comment]
谢谢作者的回答。那如果我想对内存进行管理，比如当图片占用内存到达500M时，是否能把最近最少使用的对象从内存中移除。类似Android里的lrucache。

**Comment by zmtzawqlp** [comment]
自定自己的 provider， 重载 https://github.com/fluttercandies/extended_image_library/blob/a67b5596beaf0369b704edd5802be8e085f73985/lib/src/extended_image_provider.dart#L92

**Comment by qflbai** [comment]
好的，谢谢您。
