### ISSUE TITLE
[Bug report] Bug in hero animation

### ISSUE THREAD

**Issue by B0yma** [fluttercandies/extended_image#591]
### Version

7.0.2

### Platforms

Android

### Device Model

Android Emulator api 33

### flutter info

```sh
[!] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2251])
    • Flutter version 3.7.12 on channel stable at C:\flutter
    ! The flutter binary is not on your path. Consider adding C:\flutter\bin to your path.        
    ! The dart binary is not on your path. Consider adding C:\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (10 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use
```

### How to reproduce?

Bug in demo example - simple demos - simple photo view
Bug in hero animation 
[untitled.webm](https://github.com/fluttercandies/extended_image/assets/14963010/9beda632-e4c7-4319-9019-46c7dec46a33)

expected behavior - tap on one image - hero animation with this image.
after swipe left to image number 3 - tap on back - one hero animation to same image in list

**Comment by zmtzawqlp** [comment]
i can't reproduce at my side
