### ISSUE TITLE
[Discussions] Cache image in Android

### ISSUE THREAD

**Issue by duymanhit** [fluttercandies/extended_image#593]
### Content

I cannot enable the cache of network images in Android. When the cache is set to True, the image will be an error because it did not find the local cache file

**Comment by zmtzawqlp** [comment]
any error log or a runnable simple demo?

**Comment by duymanhit** [comment]
Hello @zmtzawqlp, 
This is my code:
`    return ExtendedImage.network(
      Network().getFile(
        url,
        thumbnail: thumbnail,
        isProfile: isProfile,
      ),
      cache: true,
      cacheMaxAge: const Duration(minutes: 5),
      cacheKey: url,
      loadStateChanged: loadStateChanged ?? defaultLoadStateChanged,
      constraints: constraints,
      fit: boxFit,
      shape: shape,
      borderRadius: borderRadius,
      clipBehavior: Clip.antiAliasWithSaveLayer,
      border: border,
      // cache: false,
    );`
And error logs:

> __I/flutter ( 9866): PathNotFoundException: Cannot open file, path = '/data/user/0/com.example.vifa_client/cache/cacheimage/u/89/9734efaa-8595-56ff-b26b-10765d79fa24.jpg' (OS Error: No such file or directory, errno = 2)
I/flutter ( 9866): Bad state: Cannot add event after closing

**Comment by zmtzawqlp** [comment]
please provide more info about this issue, i can't reproduce it at my side
