### ISSUE TITLE
[Feature request] Avoid inverting aspect ration when image is rotated

### ISSUE THREAD

**Issue by maRci002** [fluttercandies/extended_image#598]
### Platforms

dart, Android, iOS, macOS, Web, Windows, Linux

### Description

Let's say my `cropAspectRatio` is `16/9`. Whenever I rotate the image, the aspect ratio is inverted, which means that when I export the image, it becomes a `9/16` aspect ratio.

I propose that a new flag should be added to disable inversion.

Example video ( _current behaviour_ ):

https://github.com/fluttercandies/extended_image/assets/8436039/0373d7b7-bc13-4e50-a20e-5c538ca533f1

**Comment by zmtzawqlp** [comment]
The same as https://github.com/fluttercandies/extended_image/issues/277
