### ISSUE TITLE
Exception thrown in Flutter v1.5.9-pre.106/1.5.9-pre.107

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [fluttercandies/extended_image#6]
Error:

> Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
>  - 'StringBuffer' is from 'dart:core'.
>  - 'Iterable' is from 'dart:core'.
>  - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/thinkdigital/development/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
> Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
>         informationCollector: (StringBuffer information) {
>                               ^

this points to the file in "package:extended_image/src/network/extended_network_image_provider.dart" 
line: 68

**Comment by DatStorm** [comment]
Same error here:

`Compiler message:
file:///home/USER/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///home/USER/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /home/USER/Downloads/Instagram-Clone-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by ThinkDigitalRepair** [comment]
You have to downgrade your flutter version if you want to keep using this package

**Comment by DatStorm** [comment]
@ThinkDigitalRepair  Thanks for the answer :bowing_man:

**Comment by ThinkDigitalRepair** [comment]
You're welcome. If you want to keep your version, you can cast the
functions to the type is suggests manually in the package's code. I
submitted a PR for it, but again, he's waiting

**Comment by zmtzawqlp** [comment]
@ThinkDigitalRepair @DatStorm 

## [0.3.3]
* disabled informationCollector to keep backwards compatibility for now (ExtendedNetworkImageProvider)

**Comment by ThinkDigitalRepair** [comment]
> @ThinkDigitalRepair @DatStorm
> 
> ## [0.3.3]
> * disabled informationCollector to keep backwards compatibility for now (ExtendedNetworkImageProvider)

Thank you!

**Comment by ThinkDigitalSoftware** [comment]
@zmtzawqlp the fact that this keeps me from upgrading my Flutter version to 1.6+ is very frustrating. I have to code with lots of flutter bugs because they haven't pushed the changes to stable yet. And it's too late to remove this package from my project. 😓

**Comment by zmtzawqlp** [comment]
see https://github.com/fluttercandies/extended_image/issues/16

dev is ready for flutter master branch， you can link it as github url

**Comment by zmtzawqlp** [comment]
@ThinkDigitalSoftware link dev branch as github url at the moment

**Comment by ThinkDigitalSoftware** [comment]
OK, great!

**Comment by zmtzawqlp** [comment]
use  following code to link to dev at the moment，
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 549af1104e55b9494f014d8e7f8e55cb5882d729

i will update codes to stable 1.7.8 as soon as possible，

**Comment by zmtzawqlp** [comment]
use  following code to link to dev at the moment，

``` dart
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 549af1104e55b9494f014d8e7f8e55cb5882d729
```

i will update codes to stable 1.7.8 as soon as possible，

**Comment by ManojMM026** [comment]
tried this as well same error. in Flutter 1.7

extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: 549af1104e55b9494f014d8e7f8e55cb5882d729
Did not work for me.

**Comment by zmtzawqlp** [comment]
try it
``` dart
  extended_image:
    git:
      url: https://github.com/fluttercandies/extended_image.git
      ref: dev
```

**Comment by ManojMM026** [comment]
> try it
> 
> ```dart
>   extended_image:
>     git:
>       url: https://github.com/fluttercandies/extended_image.git
>       ref: dev
> ```

did not work. I think I will have to wait till you push update or change library

**Comment by zmtzawqlp** [comment]
extended image base on v1.7.8 is ready in pub, please update it.
