### ISSUE TITLE
swipe back image preview page made background to black

### ISSUE THREAD

**Issue by jinfagang** [fluttercandies/extended_image#60]
Hi, the default swipe back image preview page is white and not good at previewing images. Also the swip gesture senstive seems not as good as wechat (need fully drag to the bottom of the page can trigger the back function).

**Comment by zmtzawqlp** [comment]
take a look at demo, make sure use transparent route. and define your condition to pop page

**Comment by zmtzawqlp** [comment]
canMovePage | whether we should move page | true
-- | -- | --

**Comment by zmtzawqlp** [comment]
slideEndHandler

**Comment by zmtzawqlp** [comment]
slideEndHandler
