### ISSUE TITLE
[Feature request] ExtendedImageGesturePageView can add scroll loop?

### ISSUE THREAD

**Issue by ehangwork** [fluttercandies/extended_image#606]
### Platforms

dart, Android, iOS

### Description

 I need ExtendedImageGesturePageView add scroll loop, like swiper banner，infinite loop。

**Comment by zmtzawqlp** [comment]
no plan, it's not the same thing.

**Comment by zmtzawqlp** [comment]
index=index% total, and don't set pageCount
