### ISSUE TITLE
[How to use] Documents on `timeLimit`, `timeRetry` and retry mechanism

### ISSUE THREAD

**Issue by kientux** [fluttercandies/extended_image#607]
### Platforms

Android, iOS

### Description

Can you explain the usage of `timeLimit` and `timeRetry` properties? I can't find the usage of those anywhere.

Also is there any mechanism to retry the failed image, like which HTTP status codes, or any error will be retried?

**Comment by zmtzawqlp** [comment]
It's from https://github.com/fluttercandies/http_client_helper
