### ISSUE TITLE
[Discussions]   在列表中, 有大量的图片, 如何正确的设置参数,保证不被crash

### ISSUE THREAD

**Issue by huafsud** [fluttercandies/extended_image#609]
### Content

用extended_image 当cache 来用的.

在列表中,有大量的高清图, 当快速滑动, IOS 会crash, 如何正确设置参数,才能保证不闪退呢? 

研究了半天, 发现还是闪退,

求大佬指点指点,  贴个参数代码, 让我抄抄 

谢谢大佬们~

**Comment by zmtzawqlp** [comment]
压缩图片，并且把图片的释放设置成true

**Comment by huafsud** [comment]
@zmtzawqlp 感谢, 我在研究研究,
