### ISSUE TITLE
[How to use] How to get the image after using the EditorConfig?

### ISSUE THREAD

**Issue by ember11498** [fluttercandies/extended_image#610]
### Platforms

dart

### Description

I want to get the image after the user finishes cropping it but i dont know how

### My code

my code looks like this:

                            return ExtendedImage.file(
                              snapshot.data!,
                              fit: BoxFit.contain,
                              mode: ExtendedImageMode.editor,
                              extendedImageEditorKey: editorKey,
                              clearMemoryCacheWhenDispose: true,
                              enableLoadState: true,
                              cacheRawData: true,
                              initEditorConfigHandler: (state) {
                                return EditorConfig(
                                  //maxScale: 8.0,
                                  cropRectPadding: const EdgeInsets.all(40.0),
                                  hitTestSize: 20.0,
                                  cropAspectRatio: 1,
                                  tickerDuration:
                                      const Duration(milliseconds: 150),
                                );
                              },
                            );

the editorKey is GlobalKey < ExtendedImageEditorState > ();

### Try do it

should i try this?

    Future<void> _cropImage(bool useNative) async {
      if (_cropping) {
        return;
      }
      String msg = '';
      try {
        _cropping = true;
  
        //await showBusyingDialog();
  
        late EditImageInfo imageInfo;
  
        /// native library
        if (useNative) {
          imageInfo = await cropImageDataWithNativeLibrary(
              state: editorKey.currentState!);
        } else {
          ///delay due to cropImageDataWithDartLibrary is time consuming on main thread
          ///it will block showBusyingDialog
          ///if you don't want to block ui, use compute/isolate,but it costs more time.
          //await Future.delayed(Duration(milliseconds: 200));
  
          ///if you don't want to block ui, use compute/isolate,but it costs more time.
          imageInfo =
              await cropImageDataWithDartLibrary(state: editorKey.currentState!);
        }
        final String? filePath = await ImageSaver.save(
            'extended_image_cropped_image.${imageInfo.imageType == ImageType.jpg ? 'jpg' : 'gif'}',
            imageInfo.data!);
        // var filePath = await ImagePickerSaver.saveFile(fileData: fileData);
  
        msg = 'save image : $filePath';
      } catch (e, stack) {
        msg = 'save failed: $e\n $stack';
        print(msg);
      }

**Comment by zmtzawqlp** [comment]
download demo, and run edit demo, see what to get croped image
