### ISSUE TITLE
[Bug report] Error on Chrome

### ISSUE THREAD

**Issue by zhaoxianxin** [fluttercandies/extended_image#612]
### Version

8.1.0

### Platforms

Web

### Device Model

Chrome

### flutter info

```sh
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.14.0-9.0.pre.48, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
! Flutter version 3.14.0-9.0.pre.48 on channel [user-branch] at /Users/tyzl/flutter
Currently on an unknown channel. Run flutter channel to switch to an official channel.
If that doesn't fix the issue, reinstall Flutter by following instructions at
https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (4 available)
[✓] Network resources
```

### How to reproduce?

Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:14:8: Error: Error when reading '../../../../flutter/packages/flutter/lib/src/services/dom.dart': No such file or directory
import 'package:flutter/src/services/dom.dart';
^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:20:30: Error: Type 'DomXMLHttpRequest' not found.
typedef HttpRequestFactory = DomXMLHttpRequest Function();
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:23:1: Error: Type 'DomXMLHttpRequest' not found.
DomXMLHttpRequest _httpClient() {
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:24:10: Error: Method not found: 'DomXMLHttpRequest'.
return DomXMLHttpRequest();
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:153:23: Error: 'DomXMLHttpRequest' isn't a type.
final Completer completer =
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:154:21: Error: 'DomXMLHttpRequest' isn't a type.
Completer();
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:155:13: Error: 'DomXMLHttpRequest' isn't a type.
final DomXMLHttpRequest request = httpRequestFactory();
^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:165:64: Error: 'DomEvent' isn't a type.
request.addEventListener('load', createDomEventListener((DomEvent e) {
^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:165:40: Error: The method 'createDomEventListener' isn't defined for the class 'ExtendedNetworkImageProvider'.

'ExtendedNetworkImageProvider' is from 'package:extended_image_library/src/network/network_image_web.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createDomEventListener'.
request.addEventListener('load', createDomEventListener((DomEvent e) {
^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart:184:20: Error: The method 'createDomEventListener' isn't defined for the class 'ExtendedNetworkImageProvider'.
'ExtendedNetworkImageProvider' is from 'package:extended_image_library/src/network/network_image_web.dart' ('../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.6.0/lib/src/network/network_image_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createDomEventListener'.
'error', createDomEventListener(completer.completeError));
^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by AlexRich16** [comment]
Hello 
I've the same issue

```
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.3.1 22E772610a darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources
```

**Comment by zmtzawqlp** [comment]
> Hello I've the same issue
> 
> ```
> [✓] Flutter (Channel stable, 3.13.0, on macOS 13.3.1 22E772610a darwin-arm64, locale fr-FR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.3)
> [✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
> [✓] VS Code (version 1.81.1)
> [✓] Connected device (2 available)
> [✓] Network resources
> ```

i can't reproduce it at 3.13.0

**Comment by zmtzawqlp** [comment]
3.16.0 is already

**Comment by zhanglijie5997** [comment]
i have a sample problem
`
extended_image: ^8.1.0

[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1 23B74 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.3 on channel stable at /Users/a1/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (7 天前), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

⢿
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/a1/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone13 (mobile) • 00008110-000470CA2E2A801E • ios            • iOS 17.1 21B74
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 14.1 23B74
      darwin-arm64
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome
      116.0.5845.96
`

**Comment by 25thammar** [comment]
any update?

**Comment by zmtzawqlp** [comment]
could you please check the changelog? pick the version which fit your flutter sdk
