### ISSUE TITLE
Reports to crashlytics though they are handled

### ISSUE THREAD

**Issue by xOldeVx** [fluttercandies/extended_image#617]
### Version

8.1.0

### Platforms

dart

### Device Model

Galaxy 10

### flutter info

```sh
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta),
    locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

### How to reproduce?

I'm using `ExtendedImage` and `firebase crashlytics` in my project, when the image is failed from the network (return 404) I handle the error in `state.extendedImageLoadState == LoadState.failed` part (see the code below), but this error is report to my crashlytics, and i get a lot of this reports, how can i prevent this reports?

I tried to find a solution in the crashlytics side, but didn't find.

```
ExtendedImage.network(
          'https://...',
          fit: BoxFit.cover,
          loadStateChanged: (state) {
            if (state.extendedImageLoadState == LoadState.loading) return const ImagePlaceHolder();
            if (state.extendedImageLoadState == LoadState.failed) {
              return ErrorImageWidget();
            }
            return null;
          },
        ),
```

The error
```
ImageStreamCompleter.reportError (image_stream.dart:734)
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Bad state: Failed to load https://.... Error thrown resolving an image codec.
```

**Comment by zmtzawqlp** [comment]
This is not an exception form extended_image. https://github.com/flutter/flutter/blob/ef9befc9da9f358f301d052e900b36ea3e797565/packages/flutter/lib/src/painting/image_stream.dart#L934

you can ignore this error

**Comment by thedotedge** [comment]
@zmtzawqlp could you please elaborate why it tries to decode and report the error even though there is no image to decode (since network request was not successful)?

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp could you please elaborate why it tries to decode and report the error even though there is no image to decode (since network request was not successful)?

https://github.com/flutter/flutter/blob/55e692229eaee5e37a5e35c05607853125b5f49b/packages/flutter/lib/src/painting/_network_image_io.dart#L115

it throws exception if http request has error. you can custom your image provider base on your case
