### ISSUE TITLE
不能用

### ISSUE THREAD

**Issue by markerharry** [fluttercandies/extended_image#62]
photo view 报错
Compiler message:
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-0.1.5/lib/src/extended_network_image_provider.dart:68:29: Error: The argument type 'List<DiagnosticsNode> Function()' can't be assigned to the parameter type 'void Function(StringBuffer)'.
 - 'List' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///D:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
 - 'StringBuffer' is from 'dart:core'.
Try changing the type of the parameter, or casting the argument to 'void Function(StringBuffer)'.
      informationCollector: () {
                            ^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/editor/extended_image_editor_utils.dart:223:25: Error: Method not found: 'Rect.fromCenter'.
            rect = Rect.fromCenter(
                        ^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/editor/extended_image_editor_utils.dart:230:25: Error: Method not found: 'Rect.fromCenter'.
            rect = Rect.fromCenter(
                        ^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:765:11: Error: Method not found: 'ImageStreamListener'.
          ImageStreamListener(_handleImageChanged, onError: _loadFailed));
          ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:777:11: Error: Method not found: 'ImageStreamListener'.
          ImageStreamListener(_handleImageChanged, onError: _loadFailed));
          ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:765:11: Error: The method 'ImageStreamListener' isn't defined for the class '_ExtendedImageState'.
 - '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
          ImageStreamListener(_handleImageChanged, onError: _loadFailed));
          ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:777:11: Error: The method 'ImageStreamListener' isn't defined for the class '_ExtendedImageState'.
 - '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
          ImageStreamListener(_handleImageChanged, onError: _loadFailed));
          ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:783:9: Error: Method not found: 'ImageStreamListener'.
        ImageStreamListener(_handleImageChanged, onError: _loadFailed));
        ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:783:9: Error: The method 'ImageStreamListener' isn't defined for the class '_ExtendedImageState'.
 - '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
        ImageStreamListener(_handleImageChanged, onError: _loadFailed));
        ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:790:9: Error: Method not found: 'ImageStreamListener'.
        ImageStreamListener(_handleImageChanged, onError: _loadFailed));
        ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart:790:9: Error: The method 'ImageStreamListener' isn't defined for the class '_ExtendedImageState'.
 - '_ExtendedImageState' is from 'package:extended_image/src/extended_image.dart' ('file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/extended_image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ImageStreamListener'.
        ImageStreamListener(_handleImageChanged, onError: _loadFailed));
        ^^^^^^^^^^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/editor/extended_image_editor.dart:145:37: Error: Method not found: 'Rect.fromCenter'.
                    cropRect = Rect.fromCenter(
                                    ^^^^^^^^^^
file:///D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-0.5.7/lib/src/editor/extended_image_crop_layer.dart:503:45: Error: Method not found: 'Rect.fromCenter'.
        var newScreenDestinationRect = Rect.fromCenter(

**Comment by zmtzawqlp** [comment]
这个api是1.7.8之后才有的。如果你一定要用。自己加一下Rect.fromCenter 方法。。或者提高你的flutter sdk
