### ISSUE TITLE
How to set max width, height for cropped image ?

### ISSUE THREAD

**Issue by jostney** [fluttercandies/extended_image#621]
### Platforms

iOS

### Description

I want to achieve a width and height of 400x400 pixels for the cropped image. How can I do this?

Another issue I'm encountering is that the original image is 900KB in size, but the cropped image is approximately 2MB. Logically, the cropped image should be smaller in size than the original image, shouldn't it?

```
        Expanded(
          child: ExtendedImage.file(
            File(path),
            fit: BoxFit.contain,
            mode: ExtendedImageMode.editor,
            cacheRawData: true,
            extendedImageEditorKey: editorKey,
            initEditorConfigHandler: (state) {
              return EditorConfig(
                maxScale: 8.0,
                cropRectPadding: const EdgeInsets.all(20.0),
                hitTestSize: 20.0,
                cornerColor: anzac,
                cropAspectRatio: CropAspectRatios.ratio1_1,
                lineColor: anzac,
              );
            },
          ),
        ),
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/b335bb2ef758bdb92f621300a521bd6ad6d28726/example/lib/common/utils/crop_editor_helper.dart#L200  

take a look at ImageEditor API
