### ISSUE TITLE
[Feature request] ExtendedNetworkImageProvider add clearMemoryCacheWhenDispose

### ISSUE THREAD

**Issue by huafsud** [fluttercandies/extended_image#624]
### Platforms

dart

### Description

ExtendedNetworkImageProvider need clearMemoryCacheWhenDispose = true ,

能否加上?

### Why

因为, 加上会很方便.

**Comment by huafsud** [comment]
ExtendedNetworkImageProvider 如果加上这个属性, 很多时候, 能减少代码, 求大佬加上

**Comment by zmtzawqlp** [comment]
这个不是 provider的职责

**Comment by huafsud** [comment]
@zmtzawqlp 是的大佬,最后反应过来了,感觉不对劲这需求, 所以关了,, 感谢大佬回复
