### ISSUE TITLE
[Feature request] 如何实现任意的角度旋转

### ISSUE THREAD

**Issue by JosonJiang** [fluttercandies/extended_image#627]
### Platforms

Android, iOS

### Description

能不能实现任意的角度旋转？现在有个需对图片实现自定义任意角度 进行旋转

**Comment by zmtzawqlp** [comment]
暂时不支持。算法没有想好

**Comment by JosonJiang** [comment]
> 暂时不支持。算法没有想好

https://github.com/JosonGrp/buffer_image
不知是否 有参考价值，这里有实现

**Comment by zmtzawqlp** [comment]
裁剪有库可以做，ui 上面。比如裁剪框跟图片的关系

**Comment by zmtzawqlp** [comment]
please update to lastest version
