### ISSUE TITLE
[Discussions] Why remove preloadPagesCount?

### ISSUE THREAD

**Issue by jae-om** [fluttercandies/extended_image#628]
### Content

It makes a lot to improve the quality of the gallery.

Can you tell me why it was removed?

**Comment by zmtzawqlp** [comment]
It has an unable fixing issue, and it has anothoer workaround for it

**Comment by jae-om** [comment]
> It has an unable fixing issue, and it has anothoer workaround for it

Can you tell me what the solution is?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/7b444abd813b4a5d256f4196045327dd48840754/example/lib/pages/simple/simple_photo_view_demo.dart#L109
