### ISSUE TITLE
[How to use] 

### ISSUE THREAD

**Issue by pen110** [fluttercandies/extended_image#630]
### Platforms

dart

### Description

extended_image: ^7.0.2 想实现 微信朋友圈显示九宫格 点击图片预览的功能

### My code

<img width="1013" alt="image" src="https://github.com/fluttercandies/extended_image/assets/7963859/6dbdb930-111d-4ab1-9aff-2a1487e1d475">
显示图片后，点击预览，类似微信那样

### Try do it

return GestureDetector(
                                        onTap: () {
                                          MultiImageProvider multiImageProvider = MultiImageProvider(List.generate(controller.imgs.length, (i) {
                                            return Image.network(controller.imgs[i]).image;
                                          }));
                                          showImageViewerPager(context, multiImageProvider, onPageChanged: (page) {
                                            print("page changed to $page");
                                          }, onViewerDismissed: (page) {
                                            print("dismissed while on page $page");
                                          });

**Comment by zmtzawqlp** [comment]
example 里面有。请自行查看
