### ISSUE TITLE
怎么让裁剪框范围离开图片限定宽高，让其自定义截取全屏范围；并让图片四个角添加手势进行缩放

### ISSUE THREAD

**Issue by Gluuuuuu** [fluttercandies/extended_image#632]
### Platforms

dart, Web

### Description

怎么让裁剪框范围离开图片限定宽高，让其自定义截取全屏范围；并让图片四个角添加手势进行缩放

How to make the scope of the crop frame leave the picture limit width and height, so that it can customize the full screen range of interception; Add gestures to the four corners of the picture to zoom

**Comment by zmtzawqlp** [comment]
不能，你可以fork 仓库自己试试改改

**Comment by Gluuuuuu** [comment]
> 不能，你可以fork 仓库自己试试改改

可否告诉我关键代码在哪里呢，找了蛮久的

**Comment by Gluuuuuu** [comment]
> 不能，你可以fork 仓库自己试试改改

关键就是让裁剪框范围离开图片限定宽高
