### ISSUE TITLE
[How to use] How to make the crop Circle? there are only square or rectangule options

### ISSUE THREAD

**Issue by ember11498** [fluttercandies/extended_image#633]
### Platforms

dart

### Description

i want to crop a circular avatar, not a square or rectangule. how can i do that? (regarding the image editor)

### My code

  return ExtendedImage.memory(
    imageData,
    fit: BoxFit.contain,
    mode: ExtendedImageMode.editor,
    extendedImageEditorKey: UniqueKey(),
    initEditorConfigHandler: (state) {
      return EditorConfig(
        maxScale: 8.0,
        cropRectPadding: const EdgeInsets.all(20.0),
        hitTestSize: 20.0,
        cornerColor: Theme.of(context).colorScheme.secondary,
      );
    },
  );

### Try do it

irrelevant

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/7b444abd813b4a5d256f4196045327dd48840754/example/lib/pages/complex/image_editor_demo.dart#L490
