### ISSUE TITLE
[Feature request] catch errors

### ISSUE THREAD

**Issue by AntoniPochopien** [fluttercandies/extended_image#635]
### Platforms

Android, iOS, macOS, Web, Windows, Linux

### Description

Hello, I believe it would be highly beneficial to handle errors associated with 'failed to load <URL>'.
When a user goes offline every request results in this type of error when offline. Your package is awesome, offering extensive customization options, and it also includes a state listener that enables us to update widgets based on the state, including 'LoadState.failed.' Given this, does it make sense to provide guidance on how to handle failures and still triggering an error?

### Why

The image provider should not raise an error when the URL is not found. For example, consider the use case where a user goes offline but continues to make requests.

![image](https://github.com/fluttercandies/extended_image/assets/81657640/47d025bf-12bd-4b04-9180-7fbb38310889)

**Comment by zmtzawqlp** [comment]
you can it from https://github.com/fluttercandies/extended_image/blob/7b444abd813b4a5d256f4196045327dd48840754/lib/src/extended_image.dart#L925

**Comment by AntoniPochopien** [comment]
Thank you, @zmtzawqlp for your response! Could you please provide more code samples for the solution? I'm having trouble understanding how this getter helps. It seems like it only allows me to retrieve the last exception object, but printing it doesn't assist me in catching the error. If my case is unclear, let me know. Your further guidance would be greatly appreciated.

**Comment by zmtzawqlp** [comment]
extended_image is base on offical Image.  it will throw exception if it has
 https://github.com/flutter/flutter/blob/55e692229eaee5e37a5e35c05607853125b5f49b/packages/flutter/lib/src/painting/_network_image_io.dart#L115

you can define a custom image provider base on your case
