### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by xOldeVx** [fluttercandies/extended_image#636]
### Platforms

Android

### Description

How can I set **eTag** _(e.g If-None-Match)_ support to the image provider?

@zmtzawqlp I see you refer to this link https://github.com/fluttercandies/extended_image_library/issues/20 but there's no any information about this.

These the parameters I get:
![image](https://github.com/fluttercandies/extended_image/assets/24361103/e9e3096b-c0b4-48a1-988f-8593a94e20ec)

**Comment by zmtzawqlp** [comment]
not support
