### ISSUE TITLE
[How to use] I managed to make the crop layer a circle but now I want to actually crop the image. Do I need an external package? from what I can see I can only cropRect

### ISSUE THREAD

**Issue by ember11498** [fluttercandies/extended_image#642]
### Platforms

dart

### Description

title self-explanatory

### My code

I use this in my editor in order to make the croplayer a circle

    class CircleEditorCropLayerPainter extends EditorCropLayerPainter {
      const CircleEditorCropLayerPainter();

      @override
      void paintCorners(
          Canvas canvas, Size size, ExtendedImageCropLayerPainter painter) {
        // do nothing
      }

      @override
      void paintMask(
          Canvas canvas, Size size, ExtendedImageCropLayerPainter painter) {
        final Rect rect = Offset.zero & size;
        final Rect cropRect = painter.cropRect;
        final Color maskColor = painter.maskColor;
        canvas.saveLayer(rect, Paint());
        canvas.drawRect(
            rect,
            Paint()
              ..style = PaintingStyle.fill
              ..color = maskColor);
        canvas.drawCircle(cropRect.center, cropRect.width / 2.0,
            Paint()..blendMode = BlendMode.clear);
        canvas.restore();
      }

      @override
      void paintLines(
          Canvas canvas, Size size, ExtendedImageCropLayerPainter painter) {
        final Rect cropRect = painter.cropRect;
        if (painter.pointerDown) {
          canvas.save();
          canvas.clipPath(Path()..addOval(cropRect));
          super.paintLines(canvas, size, painter);
          canvas.restore();
        }
      }
    }

### Try do it

I want to crop the image as a circle

**Comment by zmtzawqlp** [comment]
take a look 

https://github.com/fluttercandies/extended_image/blob/618a0f06f145db3cf2b6db8712cee5e472936843/example/lib/pages/complex/image_editor_demo.dart#L473
