### ISSUE TITLE
> please take a look at changelog, and pick the version match your flutter sdk version

### ISSUE THREAD

**Issue by thirstyde** [fluttercandies/extended_image#645]
> please take a look at changelog, and pick the version match your flutter sdk version

Version 8.0.2 is not flutter & dart version it's extended_image package version

_Originally posted by @thirstyde in https://github.com/fluttercandies/extended_image/issues/644#issuecomment-1874831582_

**Comment by zmtzawqlp** [comment]
your :  extended_image: ^8.0.2
your flutter : flutter sdk: Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.19045.3803], locale en-IN)

changelog: 
<img width="364" alt="截屏2024-01-03 19 27 19" src="https://github.com/fluttercandies/extended_image/assets/16477333/6815da98-61f7-49d6-997c-b8c6bc527d90">
