### ISSUE TITLE
macos环境不能加载图片

### ISSUE THREAD

**Issue by stoneLee81** [fluttercandies/extended_image#647]
### Version

extended_image 8.2

### Platforms

macOS

### Device Model

macOS

### flutter info

```sh
Channel stable, 3.16.5, on macOS 13.4.1 
CocoaPods version 1.14.3
```

### How to reproduce?

在macOS下编译运行，图片都不能加载
![Xnip2024-01-10_10-55-33](https://github.com/fluttercandies/extended_image/assets/18001708/78a8839c-d1cd-4789-8bf8-f5e4e73632b8)

### Logs

```sh
null
```

### Example code (optional)

```Dart
null
```

**Comment by zmtzawqlp** [comment]
自己加网络权限
