### ISSUE TITLE
在IM类型的App中，我想将不同群的图片放在不同的文件夹中，extended_image中能实现将不同的图片缓存在不同的文件夹中吗？

### ISSUE THREAD

**Issue by yhcflyy** [fluttercandies/extended_image#650]
### Platforms

Android, iOS, macOS, Windows

### Description

问题如上面的标题

**Comment by zmtzawqlp** [comment]
cacheKey

https://github.com/fluttercandies/extended_image_library/blob/d2e0a2299601248c55f58486dd90b4384f35f671/lib/src/network/network_image_io.dart#L190

**Comment by zmtzawqlp** [comment]
更自由的方式就是自定义 imagprovider
