### ISSUE TITLE
[Discussions] 

### ISSUE THREAD

**Issue by SauravSCC** [fluttercandies/extended_image#652]
### Content

../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:202:13: Error: 'ImageTilingInfo' isn't a type.
      final ImageTilingInfo info =
            ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/extended_image-8.0.2/lib/src/image/painting.dart:203:11: Error: Method not found: 'createTilingInfo'.
          createTilingInfo(repeat, rect, destinationRect, sourceRect);
          ^^^^^^^^^^^^^^^^

**Comment by zmtzawqlp** [comment]
check the changelog, pick the right version to fix your flutter version
