### ISSUE TITLE
[How to use] 请问，能禁用裁剪框的拖拽吗？

### ISSUE THREAD

**Issue by sleagon** [fluttercandies/extended_image#659]
### Platforms

dart

### Description

裁剪框拖拽后，裁剪区域的图片会自动移动到中间，视图会产生变化，所以目前有方法或者参数能禁止裁剪框移拖拽吗？

**Comment by zmtzawqlp** [comment]
不能

**Comment by loscoy** [comment]
自己extends一个EditorCropLayerPainter然后固定住cropRect就可以

**Comment by zmtzawqlp** [comment]
> 自己extends一个EditorCropLayerPainter然后固定住cropRect就可以

但是注意计算问题
