### ISSUE TITLE
Update dependency web: ^0.5.0

### ISSUE THREAD

**Issue by VersaDesenvolvimento** [fluttercandies/extended_image#661]
### Content

Hi, could you update "web package: dependency to 0.5.0?

I can't install extended_image 8.2.0.
extended_image >=8.2.0 depends on extended_image_library ^4.0.1, extended_image >=8.2.0 requires web ^0.3.0 or ^0.4.0.
because OURSYSTEM depends on both extended_image ^8.2.0 and web ^0.5.0, version solving failed.

So, i downgrade extended_image to 8.1.1

**Comment by zmtzawqlp** [comment]
The same as  https://github.com/fluttercandies/extended_image_library/issues/62
