### ISSUE TITLE
[Feature request] iOS 加载图片中 退出到后台再进入， 就会呈现紫色这种。

### ISSUE THREAD

**Issue by zhaoweiguo5505** [fluttercandies/extended_image#663]
### Platforms

iOS

### Description

![f525052f15776333f462a76b61503612](https://github.com/fluttercandies/extended_image/assets/34048223/8058bafa-69c8-497f-b912-0157e92faa1e)

**Comment by zmtzawqlp** [comment]
这是官方的api 的问题，官方的 Image 也能重现，建议升级 sdk

**Comment by DriverFrameWork** [comment]
升级到flutter 哪个版本可以解决
