### ISSUE TITLE
如何让展示的图片旋转？

### ISSUE THREAD

**Issue by EchoPuda** [fluttercandies/extended_image#665]
### Platforms

dart

### Description

你好，图片的加载，如何使其旋转（90度，270度之类的）而不影响其手势效果或其他效果？

我尝试过直接套个RotatedBox进行旋转，最终会变形，不过旋转90度这种的的把宽高交换之后倒是能够旋转展示，但是手势的效果会变的很奇怪，ExtendedImageSlidePage的Hero动画也会有点问题。

是否有更加推荐的方法？

**Comment by zmtzawqlp** [comment]
展示一般不支持旋转，只有编辑模式会

**Comment by zmtzawqlp** [comment]
可以用 Image_editor 旋转了之后。再给 extended_image 展示
