### ISSUE TITLE
 incompatible with http

### ISSUE THREAD

**Issue by migdev-br** [fluttercandies/extended_image#666]
### Content

Hi team,

Please have a look.

extended_image ^8.2.0 requires web ^0.3.0 or ^0.4.0.
And because http >=1.2.1 depends on web ^0.5.0, extended_image ^8.2.0 is incompatible with http >=1.2.1.

**Comment by wsk321** [comment]
Just force dependency

**Comment by zmtzawqlp** [comment]
please dependency_overrides for the web version
