### ISSUE TITLE
png图片裁剪后，背景变成了黑色，要怎么改呢？

### ISSUE THREAD

**Issue by ShuangZiMoYin** [fluttercandies/extended_image#669]
### Version

8.2.0

### Platforms

dart

### Device Model

iphone

### flutter info

```sh
0
```

### How to reproduce?

0

**Comment by ShuangZiMoYin** [comment]
After cropping the png image, the background becomes black. How to change it?

**Comment by zmtzawqlp** [comment]
you should change output format to png
