### ISSUE TITLE
[Feature request] pluggable data loading http2/http3

### ISSUE THREAD

**Issue by SbiCA** [fluttercandies/extended_image#678]
### Platforms

dart, Android, iOS, Web, Linux

### Description

I'd like to make use of http2/http3 for image loading using dio or my own http.client.

Atm. it seems that the package is using a static instance of http.client and doesn't allow to provide my own instance.

``` dart

abstract class ImageDataLoader {
      ///get network image data from cached
  Future<Uint8List?> getNetworkImageData({   String url, {
    double scale,
    Map<String, String>? headers});
}

```

### code

I'd like to use Dio to load the bytes since it supports h2 instead of the static http.client instance

``` dart

  final dio = Dio()
    ..options.baseUrl = 'https://pub.dev'
    ..interceptors.add(LogInterceptor())
    ..httpClientAdapter = Http2Adapter(
      ConnectionManager(idleTimeout: Duration(seconds: 10)),
    );

  Response<String> response;
  response = await dio.get('/?xx=6');
  for (final e in response.redirects) {
    print('redirect: ${e.statusCode} ${e.location}');
  }

```
see https://github.com/cfug/dio/tree/main/plugins/http2_adapter  for more details on how the adapter works.

### Why

- [perf] improved performance of image loading by using faster transports 
- [extensibility] Allow using different data source without touching the lib e.g. local / different protocols e.g. UDP

**Comment by zmtzawqlp** [comment]
Maybe you can create your own provider and implements it base on ExtendedNetworkImageProvider

**Comment by SbiCA** [comment]
@zmtzawqlp I could give a try, if this is worth a PR? and you think it's for the benefit of everyone. 
just a word of warning I'm not a dart expert 😅

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp I could give a try, if this is worth a PR? and you think it's for the benefit of everyone. just a word of warning I'm not a dart expert 😅

i think we should keep the library simple, and only use flutter official API.
