### ISSUE TITLE
[Bug report] I can not finish building my app

### ISSUE THREAD

**Issue by micodev** [fluttercandies/extended_image#680]
### Version

8.2.0

### Platforms

iOS

### Device Model

iPhone 15 Pro Max

### flutter info

```sh
Failed to build iOS app
[        ] Error (Xcode): [+3379 ms] /Users/ibrahim/.pub-cache/hosted/pub.dev/extended_image-8.2.0/lib/src/gesture_detector/official.dart:615:7: Error: The
           non-abstract class '_VerticalDragGestureRecognizer' is missing implementations for these members:
```

### How to reproduce?

I am just using the library by providing data to extended image

**Comment by zmtzawqlp** [comment]
please check the changelog, find the version to fit your local flutter sdk

**Comment by k3v1n-uncle** [comment]
同样的问题，flutter 3.22.1

**Comment by zmtzawqlp** [comment]
> please check the changelog, find the version to fit your local flutter sdk

https://github.com/fluttercandies/extended_image/issues/680#issuecomment-2141281472

**Comment by zmtzawqlp** [comment]
> 同样的问题，flutter 3.22.1

please check the changelog, find the version to fit your local flutter sdk
