### ISSUE TITLE
how to auto zoom to the crop area when initiated (fit: BoxFit.contain)

### ISSUE THREAD

**Issue by dvlj** [fluttercandies/extended_image#69]
Is there any way to auto zoom to the square crop area when the widget is initiated.  My image is 16:9, and i can only use BoxFit.contain to allow full image editing instead of BoxFit.cover (which only have square part), currently i use a work around (after build and rotate back and forth) to achieve this, but ugly...:

```
return ExtendedImage.memory(
      cachedOriFilters[filter?.name ?? "_"],
      fit: BoxFit.contain,
      mode: ExtendedImageMode.editor,
      extendedImageEditorKey: editorKey,
      initEditorConfigHandler: (state) {
        return EditorConfig(
          cornerSize: Size(0.0, 0.0),
          cropRectPadding: EdgeInsets.all(0.0),
          // maxScale: 2.0,
          cropAspectRatio: CropAspectRatios.ratio1_1,
          animationDuration: Duration(milliseconds: 0),
          tickerDuration: Duration(milliseconds: 0),
        );
      },
      loadStateChanged: (ExtendedImageState state) {
        switch (state.extendedImageLoadState) {
          case LoadState.loading:
            break;
          case LoadState.completed:
            SchedulerBinding.instance
                .addPostFrameCallback((_) => _onAfterBuild(context));
            break;
          case LoadState.failed:
            break;
        }
      },
    );
```

```
void _onAfterBuild(BuildContext context) {
    editorKey.currentState.rotate(right: true);
    editorKey.currentState.rotate(right: false);
  }
```

**Comment by zmtzawqlp** [comment]
please provide runable demo, i didn't get your point

**Comment by dvlj** [comment]
picture is more than a word:

this is normal setting, i put ExtendedImage in a square container with cropAspectRatio 1:1 and fit=BoxFit.contain :
![image](https://user-images.githubusercontent.com/17700047/66282343-9b31b800-e8f1-11e9-95d8-8415144c5cd5.png)

this is after when i size the crop, picture fills entire square (which is what i want in the initial):
![image](https://user-images.githubusercontent.com/17700047/66282494-33c83800-e8f2-11e9-815a-4747e0503a3e.png)

Is there any way i can fill the to the entire square at initial (not doing fit:BoxFit.cover)?

what i come out a workaround is to rotate back and forth to achieve it, which is ugly (shown in 
 above code)

**Comment by zmtzawqlp** [comment]
reopen it, if it still has problem.
