### ISSUE TITLE
[How to use] editorKey.currentState.rotate() 能否让裁剪框不跟着旋转？

### ISSUE THREAD

**Issue by cn-ljb** [fluttercandies/extended_image#691]
### Platforms

Android, iOS

### Description

 editorKey.currentState.rotate() 图像旋转同时裁剪框跟着旋转

### My code

step1: 
ClipRect(
        child: ExtendedImage(
          image:
              ExtendedFileImageProvider(_getImage().file, cacheRawData: true),
          height: widget.width,
          width: widget.height,
          extendedImageEditorKey: editorKey,
          mode: ExtendedImageMode.editor,
          fit: BoxFit.contain,
          initEditorConfigHandler: (_) => EditorConfig(
            maxScale: 8.0,
            cropRectPadding: const EdgeInsets.all(20.0),
            hitTestSize: 20,
            cropAspectRatio: widget.width / widget.height,
          ),
        ),
      )
      
      
step2:
editorKey.currentState?.rotate(right: true),

**Comment by zmtzawqlp** [comment]
是这样设计的，你可以看看小米的系统相册

**Comment by binzeefox** [comment]
挺重要的。。能否提供个开关啥的？

**Comment by zmtzawqlp** [comment]
关键是算法，临界值处理，不是一个开关就解决
