### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/extended_image-8.2.1/lib/src/gesture_detector/official.dart:34:38: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.

### ISSUE THREAD

**Issue by mark8044** [fluttercandies/extended_image#693]
### Version

8.2.1

### Platforms

dart, Android, iOS

### Device Model

iPhone 15

### flutter info

```sh
Flutter 3.24.0-1.0.pre.525 • channel master • https://github.com/flutter/flutter.git
Framework • revision 76107bdf50 (12 hours ago) • 2024-08-08 16:50:40 -0700
Engine • revision 0520889683
Tools • Dart 3.6.0 (build 3.6.0-130.0.dev) • DevTools 2.38.0
```

### How to reproduce?

Just try to run the app

### Logs

```sh
Not needed
```

**Comment by kevin007** [comment]
Issue is present on Android as well once the flutter is updated to 3.24.  I

**Comment by zmtzawqlp** [comment]
it will be fixed in next stable version

**Comment by mark8044** [comment]
@zmtzawqlp it looks like version 3.24.1 is out today, any chance for update?

**Comment by zmtzawqlp** [comment]
it will not merge the hotfix branch code

**Comment by bismarabia** [comment]
> it will be fixed in next stable version

3.24.1 is out already, 5 days ago...
when are you planning to fix this? this is a blocking issue

@zmtzawqlp

**Comment by zmtzawqlp** [comment]
> > it will be fixed in next stable version
> 
> 3.24.1 is out already, 5 days ago... when are you planning to fix this? this is a blocking issue
> 
> @zmtzawqlp

it will not merge the hotfix branch code

**Comment by bismarabia** [comment]
> > > it will be fixed in next stable version
> > 
> > 
> > 3.24.1 is out already, 5 days ago... when are you planning to fix this? this is a blocking issue
> > @zmtzawqlp
> 
> it will not merge the hotfix branch code

what do you mean? @zmtzawqlp

**Comment by luomo-pro** [comment]
I have also encountered the same problem, is there a solution now?

**Comment by AlexV525** [comment]
Could you run `flutter clean` once to see if the issue was fixed?

**Comment by zmtzawqlp** [comment]
I have no problem on stable 3.24.1 ,  make sure you are right flutter branch.

**Comment by zmtzawqlp** [comment]
The DragGestureRecognizer change to sealed in  master branch https://github.com/flutter/flutter/blob/f7804404b8151895be872b0e6deda9dded4ee22d/packages/flutter/lib/src/gestures/monodrag.dart#L78

**Comment by luomo-pro** [comment]
I am using the latest master version.
Flutter (Channel master, 3.25.0-1.0.pre.172

I tried Flutter Clean, but the problem remains the same.

../../.pub-cache/hosted/pub.flutter-io.cn/extended_image-8.2.0/lib/src/gesture_d
etector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be
extended, implemented, or mixed in outside of its library because it's a sealed
class.

**Comment by AlexV525** [comment]
The library does not target branches other than the stable. If anyone is still running into the same issue, check if your Flutter is on the stable branch.

**Comment by zmtzawqlp** [comment]
please update to 8.2.3

**Comment by 312236232** [comment]
extended_image: ^8.3.1

升级后解决了
