### ISSUE TITLE
[Feature request] 有没有纯粹的图片加载库? 就像glide/pricasso之类的一样

### ISSUE THREAD

**Issue by Liloupar** [fluttercandies/extended_image#694]
### Platforms

dart

### Description

rt

### Why

flutter上这块生态有点缺失, cached_network_image 缺少很多功能, 比如滚动时暂停加载之类的, 以及引入了外部依赖

**Comment by zmtzawqlp** [comment]
你又要简单，又说其他库缺少功能。。what do you want?

**Comment by Liloupar** [comment]
> 你又要简单，又说其他库缺少功能。。what do you want?

抱歉 标题编辑后忘了提交了
我指的是就像 coil 这样的, 专注于图片加载, 不会有什么图片预览啊 放大缩小手势啊 等等的

**Comment by zmtzawqlp** [comment]
> > 你又要简单，又说其他库缺少功能。。what do you want?
> 
> 抱歉 标题编辑后忘了提交了 我指的是就像 coil 这样的, 专注于图片加载, 不会有什么图片预览啊 放大缩小手势啊 等等的 @zmtzawqlp

你不使用，也不影响你使用。。这是一些图片相关的功能

**Comment by Liloupar** [comment]
> > > 你又要简单，又说其他库缺少功能。。what do you want?
> > 
> > 
> > 抱歉 标题编辑后忘了提交了 我指的是就像 coil 这样的, 专注于图片加载, 不会有什么图片预览啊 放大缩小手势啊 等等的 @zmtzawqlp
> 
> 你不使用，也不影响你使用。。这是一些图片相关的功能

话是这么说的没错, 但是不是很多库都标榜轻量, 或者是功能可以按需加依赖.
说明是有这种需求或者说是算优势点的..

**Comment by zmtzawqlp** [comment]
功能是按需加载的，不可能有一个组件，完全满足你自身的需求的。要不然fork ，自己改改？

**Comment by Liloupar** [comment]
> 功能是按需加载的，不可能有一个组件，完全满足你自身的需求的。要不然fork ，自己改改？

只是提个建议, 并不是说要把这个库剥离掉什么什么之类的, 只是找库的时候发现没有Android上类似的那些, 所以问了下

感谢解答

**Comment by zmtzawqlp** [comment]
没事，希望帮助到了你
