### ISSUE TITLE
[Feature request] Update dependency web ^1.0.0.

### ISSUE THREAD

**Issue by tannker** [fluttercandies/extended_image#695]
### Platforms

Android, iOS

### Description

web package dependency needs to be upgraded. Latest web package version is now 1.0.0. We see several other packages upgrading their dependencies and as a result we are not able to make any upgrades as extended_image blocks it

### Why

We have some other packages that have introduced dependences on web ^1.0.0. As extended_image needs to have web 0.6.0, it blocks us various important upgrades. Hence is it possible to upgrade web dependency to web ^1.0.0

**Comment by zmtzawqlp** [comment]
the same as https://github.com/fluttercandies/extended_image_library/issues/62

**Comment by zmtzawqlp** [comment]
done https://github.com/fluttercandies/extended_image_library/commit/77073a70aa6797c33dd2df6bf1ccef42496881cd
