### ISSUE TITLE
缓存失败[Discussions] 

### ISSUE THREAD

**Issue by yangyiyyds** [fluttercandies/extended_image#698]
### Content

我设置了 cache: true, 为什么我有时候进入app的时候还需要重新加载网络图片 并且某些页面去其他页面返回这个页面的时候 还会重新加载网络图片

**Comment by zmtzawqlp** [comment]
你的图片太大了。缓存的是原始数据，flutter解析还需要时间

**Comment by yangyiyyds** [comment]
我通过查看网络请求发现 第一次加载后 第二次进入页面 没有重新发送网络请求获取图片 所以图片是缓存的 但是为什么 他有有时候从当前页面使用.pushNamed调整其他页面 然后放回当前页面 有时候图片显示效果还是在重新加载的效果（但是这个时候图片已经缓存了）
 ExtendedImage.network(
                                                        homeData["bannerCards"]
                                                                [index]["image"]
                                                            ["src"],
                                                        fit: BoxFit.cover,
                                                        cache: true,
                                                      )

这是使用的代码

**Comment by yangyiyyds** [comment]
有没有什么办法优化下

**Comment by zmtzawqlp** [comment]
> 你的图片太大了。缓存的是原始数据，flutter解析还需要时间

压缩你的图片

**Comment by yangyiyyds** [comment]
你是说 缓存的时候设置压缩图片 还是获取的接口数据里面的图片 叫他们压缩一下再上传？

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/blob/93d54c615f8ec7eb81b5609036855a904deff17f/lib/src/extended_image.dart#L503 

设置看看？或者让接口压缩
