### ISSUE TITLE
androidx support？

### ISSUE THREAD

**Issue by jinfagang** [fluttercandies/extended_image#7]
projects with Android X support will not built with it. seems imagepickersave has Android X
  support issue.

**Comment by zmtzawqlp** [comment]
@jinfagang  image picker save  is other plugin。 it's just in demo, you can update the lastest version of image picker save to slove Android X

**Comment by jinfagang** [comment]
Ok, unfortunately, for anyone else got same issue, image_picker_saver newest does not support android x yet
