### ISSUE TITLE
[Discussions] 针对一个场景，页面无限套娃式的，比如商品详情里有商品推荐，从商品推荐点击某个商品又进入商品详情，然后详情里又有推荐的商品，这么无限套娃

### ISSUE THREAD

**Issue by anypwx** [fluttercandies/extended_image#718]
### Content

如题。无限套娃式的页面，图片内存释放不了，看了源码，是会等dispose才去释放内存，但套娃页面比较特殊，它不会销毁页面，而是新增页面。当然，返回上一页是会释放，但假设用户不返回，而是在里面点播放一个4k的广告视频，那么就崩了
我如何去针对这个场景去释放内存呢，可否提供一个外部可调用的方法，开发者手动去释放一波内存？

**Comment by anypwx** [comment]
> 可以自己释放。ImageProvider.evict()

我调用了这个，但是没有启作用，我用一个list 存起来provider
![image](https://github.com/user-attachments/assets/db0a7bc7-f47d-4872-a775-1910571218b8)

而且还使用了这两句代码，内存没有释放
PaintingBinding.instance.imageCache.clear();
PaintingBinding.instance.imageCache.clearLiveImages();

![image](https://github.com/user-attachments/assets/fe919b3d-28c8-4a8a-9e0b-32814fca7909)

**Comment by anypwx** [comment]
内存一直随着页面的套娃打开，而增长

**Comment by zmtzawqlp** [comment]
那这应该属于 flutter imagg cache 的问题了，可以去官方issue里面搜索下看看

**Comment by zmtzawqlp** [comment]
另外。详情跳详情。建议只保留一个。可以参考下其他app

**Comment by anypwx** [comment]
![image](https://github.com/user-attachments/assets/96d86543-f065-4a6f-b258-02dc5ae2410c)
![image](https://github.com/user-attachments/assets/da53c62b-50e6-45e0-a180-21eba65f3a53)
我在ExtendedImage.network 定义了一个imageCacheName，然后用上述图片的方式清理，发现也无效

**Comment by anypwx** [comment]
> 另外。详情跳详情。建议只保留一个。可以参考下其他app

需求是这样的，用户希望能返回上一页的推荐， 是可以用同一个页面来做，但是也需要维护多个页面的数据，方便返回上一页后拿出来渲染

**Comment by zmtzawqlp** [comment]
pushreplace ，无限，不管什么手机都不行。还有你的图片不压缩一下吗

**Comment by anypwx** [comment]
> pushreplace ，无限，不管什么手机都不行。还有你的图片不压缩一下吗

已经是压缩后的，没压缩更大，也不能压缩过头了，会模糊。 之前用cachenetworkimage 这个框架它不自动释放内存。坑的很。但是很奇怪的是，调用下面这两个是有效的，会立即降低内存压力。
PaintingBinding.instance.imageCache.clear();
PaintingBinding.instance.imageCache.clearLiveImages();

**Comment by zmtzawqlp** [comment]
建议你用 flutter 的跑下profile 模式
