### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by zhancheng** [fluttercandies/extended_image#76]
1. loading样式能不能自定义

2. 图片loading的时候出现了样式溢出

![image](https://user-images.githubusercontent.com/2122947/66821952-e729d000-ef75-11e9-9a37-2b0d7eaee8a5.png)

**Comment by zmtzawqlp** [comment]
请仔细查看readme
![image](https://user-images.githubusercontent.com/16477333/66823714-6076f200-ef79-11e9-9975-8f818e44d97e.png)

**Comment by zhancheng** [comment]
@zmtzawqlp 非常感谢 是我漏掉了
