### ISSUE TITLE
图片尺寸过大时不显示，和容量无关

### ISSUE THREAD

**Issue by crazecoder** [fluttercandies/extended_image#77]
目前测试6000x3803 2.3M的网络图片，无论开不开启缩放和手势都不显示，配置高一点的机型，在开手势的情况下默认不显示，手势操作时会闪屏

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/30

最下面有解决方案。是跟图片的分辨率有关系

**Comment by crazecoder** [comment]
```dart
WidgetsFlutterBinding.ensureInitialized();
  const maxBytes = 9999999 * (1 << 20);
  SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
  runApp(MyApp());
```
改成9999999都没用。。。

**Comment by zmtzawqlp** [comment]
请认真查看

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  const maxBytes = 768  * (1 << 20);
  // Invoke both method names to ensure the correct one gets invoked.
  SystemChannels.skia.invokeMethod('setResourceCacheMaxBytes', maxBytes);
  SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes);
  runApp(MyApp());
}

**Comment by crazecoder** [comment]
我知道，SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', maxBytes)报错，所以我就删掉了

**Comment by zmtzawqlp** [comment]
那你肯定是版本不支持吧。。上master吧

**Comment by crazecoder** [comment]
Flutter 1.9.1+hotfix.5 • channel stable
不支持吗？

**Comment by zmtzawqlp** [comment]
我也不知道。。issue里面也有人提了。。这个就是引擎的问题。。所以说要不然你就升级试试

**Comment by crazecoder** [comment]
。。。切到beta分支一样没用，先close，慢慢研究吧
