### ISSUE TITLE
当设置图片大小比较小的时候，加载中动画会超出所设置的大小，造成错误

### ISSUE THREAD

**Issue by XQDD** [fluttercandies/extended_image#8]
![image](https://user-images.githubusercontent.com/20871761/57235270-16e2bc80-7055-11e9-814a-e37e7d40a5cd.png)
![image](https://user-images.githubusercontent.com/20871761/57235346-3c6fc600-7055-11e9-99a9-8d9b18ce1c2f.png)

**Comment by zmtzawqlp** [comment]
为啥要用默认的效果，如果你有特殊需求，应该是重写这个回调，请查看https://github.com/fluttercandies/extended_image/blob/master/example/lib/custom_image_demo.dart
