### ISSUE TITLE
flutter 最新版无法工作

### ISSUE THREAD

**Issue by hongliang211** [fluttercandies/extended_image#81]
../../../.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.1.5/lib/src/extended_network_image_provider.dart:60:24: Error: The method 'ExtendedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

**Comment by hongliang211** [comment]
cached_network_image   之前也有这样的问题  原因是flutter对image做了大的更改   希望尽快升级插件

**Comment by zmtzawqlp** [comment]
跟https://github.com/fluttercandies/extended_image/issues/80 相同

**Comment by demdog** [comment]
遇到同样的问题，无法在1.12.13 hotfix下运行
