### ISSUE TITLE
extend image not taking image picker gallery image

### ISSUE THREAD

**Issue by dileepjb2** [fluttercandies/extended_image#84]
HI I am facing issue with imagePicker gallery url not able to assign to crop extendImage.network

 File imagefile = await ImagePicker.pickImage(source: ImageSource.gallery);

ExtendedImage.network(
                                imagefile.path
                               fit: BoxFit.contain,
                                mode: type == 'editor'
                                    ? ExtendedImageMode.editor
                                    : ExtendedImageMode.none,
                                extendedImageEditorKey: editorKey,
                                cache: true,
                                enableMemoryCache: true,
                                clearMemoryCacheIfFailed: true);

Facing failed to load image
Please help on this issue,

Thanks in advance

**Comment by zmtzawqlp** [comment]
ExtendedImage.file(imagefile)

**Comment by dileepjb2** [comment]
@zmtzawqlp  thank you its working
