### ISSUE TITLE
add option to just change loading and error image assets

### ISSUE THREAD

**Issue by fmfuerte** [fluttercandies/extended_image#85]
hello, I am loving the library and its functionality but making a custom loading state is too much work, it also seems to overwrite gestures and other animations like swipe to dismiss.  I wish there was an option to only change the loading image asset and the error image asset.

**Comment by zmtzawqlp** [comment]
you just need to override loading/failed, if it's competeled state, you can return null

**Comment by fmfuerte** [comment]
I believe it should be made more clear in the documentation or at least a
sample of it

**Comment by zmtzawqlp** [comment]
ok, thanks for suggestion

**Comment by fmfuerte** [comment]
Thank you also for the library and the effort :)

**Comment by zmtzawqlp** [comment]
please check whether it's clear for you .thanks.

**Comment by fmfuerte** [comment]
Yes i tried your suggestion and it works.. thank you.. if possible please
add example of this in the documentaton

**Comment by zmtzawqlp** [comment]
i have add them in readme，and so add notice in example
