### ISSUE TITLE
图片切换后出现空白问题bug

### ISSUE THREAD

**Issue by qq329401134** [fluttercandies/extended_image#90]
运行example工程，
打开1.image crop rect 
2.点击一个张图
3.左滑到第二张图
4.点击退出当前图片浏览
5.第一张图会变成空白

**Comment by qq329401134** [comment]
升级flutter即可解决

**Comment by zmtzawqlp** [comment]
1.9.1+hotfix 6

**Comment by wtus** [comment]
> 1.9.1+hotfix 6

在使用 Hero 动画时，会出现 空白抖动（空白会闪一下）
flutter 1.10.15
