### ISSUE TITLE
Can i get tap position?

### ISSUE THREAD

**Issue by SergeShkurko** [fluttercandies/extended_image#91]
Can I get the position where the user clicked, relative to the image itself?

**Comment by zmtzawqlp** [comment]
What is your purpose？

**Comment by SergeShkurko** [comment]
@zmtzawqlp I need to determine the position of clicking on the image including the ability to zoom
![Без имени](https://user-images.githubusercontent.com/18213789/68187226-f249ac00-ffc7-11e9-8daf-04769498499c.png)

I already usage package https://github.com/renancaraujo/photo_view And for this function I had to add such an opportunity there: https://github.com/renancaraujo/photo_view/commit/6f0c3b1669a9840e07ad8ccce9d3714c27334599

I really liked the gallery in your package and I'm thinking about switching to your package
But I did not see similar functions. Do you think it would be possible to integrate something like that into your package?

**Comment by zmtzawqlp** [comment]
it seems like onDoubleTap in demo https://github.com/fluttercandies/extended_image/blob/master/example/lib/common/pic_swiper.dart
