### ISSUE TITLE
ExtendedImageGesturePageView动态切换scrollDirection手势问题

### ISSUE THREAD

**Issue by Unicellular-SU** [fluttercandies/extended_image#97]
当动态切换ExtendedImageGesturePageView的scrollDirection时，它还是原来方向的滑动手势才能翻页
比如，原本水平方向浏览图片，从右向左滑动切换到下一页，我动态改变成垂直方向，这时候还是要从右向左滑动才能切换到下一页，正确的手势应该是从下往上滑吧

**Comment by zmtzawqlp** [comment]
是否最新版本已经修复掉这个问题？

**Comment by Unicellular-SU** [comment]
现在对应方向滑动是可以了，但是之前方向仍然可以翻页

zmtzawqlp <notifications@github.com> 于2019年12月2日周一 上午9:32写道：

**Comment by zmtzawqlp** [comment]
没有明白。请提供一个简单的demo，和步骤

**Comment by Unicellular-SU** [comment]
> 没有明白。请提供一个简单的demo，和步骤

不好意思，我之前搞错了，已经解决了😅
